// Generated CC0/public-domain allowlist. See data/dcp/manifest.json.
pub const BUNDLED: &[(&str, &[u8])] = &[
    ("CANON EOS REBEL SL3", include_bytes!("../data/dcp/CANON_EOS_250D.dcp")),
    ("CANON EOS 800D", include_bytes!("../data/dcp/CANON_EOS_800D.dcp")),
    ("CANON EOS M50", include_bytes!("../data/dcp/CANON_EOS_M50.dcp")),
    ("CANON POWERSHOT G5 X MARK II", include_bytes!("../data/dcp/CANON_POWERSHOT_G5_X_MARK_II.dcp")),
    ("Canon EOS-1D X Mark III", include_bytes!("../data/dcp/Canon_EOS-1D_X_Mark_III.dcp")),
    ("Canon EOS-1Ds Mark II", include_bytes!("../data/dcp/Canon_EOS-1Ds_Mark_II.dcp")),
    ("Canon EOS 5D Mark II", include_bytes!("../data/dcp/Canon_EOS_5D_Mark_II.dcp")),
    ("CANON EOS 5D MARK IV", include_bytes!("../data/dcp/Canon_EOS_5D_Mark_IV.dcp")),
    ("CANON EOS M6 MARK II", include_bytes!("../data/dcp/Canon_EOS_M6_Mark_II.dcp")),
    ("CANON EOS R", include_bytes!("../data/dcp/Canon_EOS_R.dcp")),
    ("CANON EOS R5", include_bytes!("../data/dcp/Canon_EOS_R5.dcp")),
    ("CANON EOS R6", include_bytes!("../data/dcp/Canon_EOS_R6.dcp")),
    ("Canon EOS R8", include_bytes!("../data/dcp/Canon_EOS_R8.dcp")),
    ("Canon EOS RP", include_bytes!("../data/dcp/Canon_EOS_RP.dcp")),
    ("CANON POWERSHOT G1 X MARK II", include_bytes!("../data/dcp/Canon_PowerShot_G1_X_Mark_II.dcp")),
    ("FUJIFILM DBP for GX680", include_bytes!("../data/dcp/FUJIFILM_DBP_for_GX680.dcp")),
    ("FUJIFILM X-A5", include_bytes!("../data/dcp/FUJIFILM_X-A5.dcp")),
    ("FUJIFILM X-A7", include_bytes!("../data/dcp/FUJIFILM_X-A7.dcp")),
    ("FUJIFILM X-E3", include_bytes!("../data/dcp/FUJIFILM_X-E3.dcp")),
    ("FUJIFILM X-H1", include_bytes!("../data/dcp/FUJIFILM_X-H1.dcp")),
    ("FUJIFILM X-PRO3", include_bytes!("../data/dcp/FUJIFILM_X-Pro3.dcp")),
    ("FUJIFILM X-S10", include_bytes!("../data/dcp/FUJIFILM_X-S10.dcp")),
    ("FUJIFILM X-T3", include_bytes!("../data/dcp/FUJIFILM_X-T3.dcp")),
    ("FUJIFILM X-T4", include_bytes!("../data/dcp/FUJIFILM_X-T4.dcp")),
    ("NIKON D3300", include_bytes!("../data/dcp/NIKON_D3300.dcp")),
    ("NIKON D500", include_bytes!("../data/dcp/NIKON_D500.dcp")),
    ("NIKON D5300", include_bytes!("../data/dcp/NIKON_D5300.dcp")),
    ("NIKON D610", include_bytes!("../data/dcp/NIKON_D610.dcp")),
    ("NIKON D7100", include_bytes!("../data/dcp/NIKON_D7100.dcp")),
    ("NIKON D7500", include_bytes!("../data/dcp/NIKON_D7500.dcp")),
    ("NIKON D800", include_bytes!("../data/dcp/NIKON_D800.dcp")),
    ("NIKON D850", include_bytes!("../data/dcp/NIKON_D850.dcp")),
    ("NIKON Z 5", include_bytes!("../data/dcp/NIKON_Z_5.dcp")),
    ("NIKON Z 50", include_bytes!("../data/dcp/NIKON_Z_50.dcp")),
    ("NIKON Z 6", include_bytes!("../data/dcp/NIKON_Z_6.dcp")),
    ("NIKON Z 6_2", include_bytes!("../data/dcp/NIKON_Z_6_2.dcp")),
    ("NIKON Z 7", include_bytes!("../data/dcp/NIKON_Z_7.dcp")),
    ("NIKON Z 8", include_bytes!("../data/dcp/NIKON_Z_8.dcp")),
    ("NIKON Z 9", include_bytes!("../data/dcp/NIKON_Z_9.dcp")),
    ("NIKON Z F", include_bytes!("../data/dcp/NIKON_Z_F.dcp")),
    ("OLYMPUS E-M1", include_bytes!("../data/dcp/OLYMPUS_E-M1.dcp")),
    ("OLYMPUS E-M5MARKII", include_bytes!("../data/dcp/OLYMPUS_E-M5MarkII.dcp")),
    ("PANASONIC DC-S5M2", include_bytes!("../data/dcp/PANASONIC_DC-S5M2.dcp")),
    ("PANASONIC DMC-LX100", include_bytes!("../data/dcp/PANASONIC_DMC-LX100.dcp")),
    ("PENTAX K-50", include_bytes!("../data/dcp/PENTAX_K-50.dcp")),
    ("SONY DSC-RX100M6", include_bytes!("../data/dcp/SONY_DSC-RX100M6.dcp")),
    ("SONY ILCE-6400", include_bytes!("../data/dcp/SONY_ILCE-6400.dcp")),
    ("SONY ILCE-6600", include_bytes!("../data/dcp/SONY_ILCE-6600.dcp")),
    ("SONY ILCE-7", include_bytes!("../data/dcp/SONY_ILCE-7.dcp")),
    ("SONY ILCE-7C", include_bytes!("../data/dcp/SONY_ILCE-7C.dcp")),
    ("SONY ILCE-7M4", include_bytes!("../data/dcp/SONY_ILCE-7M4.dcp")),
    ("SONY ILCE-7RM4", include_bytes!("../data/dcp/SONY_ILCE-7RM4.dcp")),
    ("SONY ILCE-7SM3", include_bytes!("../data/dcp/SONY_ILCE-7SM3.dcp")),
    ("SONY ILCE-9", include_bytes!("../data/dcp/SONY_ILCE-9.dcp")),
    ("samsung SM-G930V", include_bytes!("../data/dcp/samsung_SM-G930V.dcp")),
];
pub const ALIASES: &[(&str, &str)] = &[
    ("CANON EOS 250D", "CANON EOS REBEL SL3"),
    ("CANON EOS 800D", "CANON EOS 800D"),
    ("CANON EOS M50", "CANON EOS M50"),
    ("CANON POWERSHOT G5 X MARK II", "CANON POWERSHOT G5 X MARK II"),
    ("Canon EOS-1D X Mark III", "Canon EOS-1D X Mark III"),
    ("Canon EOS-1Ds Mark II", "Canon EOS-1Ds Mark II"),
    ("Canon EOS 5D Mark II", "Canon EOS 5D Mark II"),
    ("Canon EOS 5D Mark IV", "CANON EOS 5D MARK IV"),
    ("Canon EOS M6 Mark II", "CANON EOS M6 MARK II"),
    ("Canon EOS R", "CANON EOS R"),
    ("Canon EOS R5", "CANON EOS R5"),
    ("Canon EOS R6", "CANON EOS R6"),
    ("Canon EOS R8", "Canon EOS R8"),
    ("Canon EOS RP", "Canon EOS RP"),
    ("Canon PowerShot G1 X Mark II", "CANON POWERSHOT G1 X MARK II"),
    ("FUJIFILM DBP for GX680", "FUJIFILM DBP for GX680"),
    ("FUJIFILM X-A5", "FUJIFILM X-A5"),
    ("FUJIFILM X-A7", "FUJIFILM X-A7"),
    ("FUJIFILM X-E3", "FUJIFILM X-E3"),
    ("FUJIFILM X-H1", "FUJIFILM X-H1"),
    ("FUJIFILM X-Pro3", "FUJIFILM X-PRO3"),
    ("FUJIFILM X-S10", "FUJIFILM X-S10"),
    ("FUJIFILM X-T3", "FUJIFILM X-T3"),
    ("FUJIFILM X-T4", "FUJIFILM X-T4"),
    ("NIKON D3300", "NIKON D3300"),
    ("NIKON D500", "NIKON D500"),
    ("NIKON D5300", "NIKON D5300"),
    ("NIKON D610", "NIKON D610"),
    ("NIKON D7100", "NIKON D7100"),
    ("NIKON D7500", "NIKON D7500"),
    ("NIKON D800", "NIKON D800"),
    ("NIKON D850", "NIKON D850"),
    ("NIKON Z 5", "NIKON Z 5"),
    ("NIKON Z 50", "NIKON Z 50"),
    ("NIKON Z 6", "NIKON Z 6"),
    ("NIKON Z 6 2", "NIKON Z 6_2"),
    ("NIKON Z 7", "NIKON Z 7"),
    ("NIKON Z 8", "NIKON Z 8"),
    ("NIKON Z 9", "NIKON Z 9"),
    ("NIKON Z F", "NIKON Z F"),
    ("OLYMPUS E-M1", "OLYMPUS E-M1"),
    ("OLYMPUS E-M5MarkII", "OLYMPUS E-M5MARKII"),
    ("PANASONIC DC-S5M2", "PANASONIC DC-S5M2"),
    ("PANASONIC DMC-LX100", "PANASONIC DMC-LX100"),
    ("PENTAX K-50", "PENTAX K-50"),
    ("SONY DSC-RX100M6", "SONY DSC-RX100M6"),
    ("SONY ILCE-6400", "SONY ILCE-6400"),
    ("SONY ILCE-6600", "SONY ILCE-6600"),
    ("SONY ILCE-7", "SONY ILCE-7"),
    ("SONY ILCE-7C", "SONY ILCE-7C"),
    ("SONY ILCE-7M4", "SONY ILCE-7M4"),
    ("SONY ILCE-7RM4", "SONY ILCE-7RM4"),
    ("SONY ILCE-7SM3", "SONY ILCE-7SM3"),
    ("SONY ILCE-9", "SONY ILCE-9"),
    ("samsung SM-G930V", "samsung SM-G930V"),
];
