[package]
name = "photocraft-raster"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
photocraft-geom = { workspace = true }
photocraft-color = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
