// Live Openverse acceptance: real search, remote thumbnails/download, editable
// document/background/reference imports and portable credit persistence.
const{chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const output=process.argv[2]||'qa-artifacts/studio-stock',base=process.env.LOCAL_REMOVE_TEST_URL||'http://127.0.0.1:51249';
fs.mkdirSync(output,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'}),page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>localStorage.setItem('local-image.hardware-guide.v1','1'));
 try{
  await page.goto(base+'/remove');await page.waitForFunction(()=>settingsLoaded);
  await page.locator('#project-file').setInputFiles('qa-artifacts/qwen/live-final/backpack-project.lremove');await page.waitForFunction(()=>session?.cutout?.enabled&&!busy);
  await page.locator('#studio-background-tab').click();await page.locator('#background-stock').click();await page.waitForFunction(()=>stockProviders.length===1&&!stockLoading);await page.locator('#stock-query').fill('forest');await page.locator('#stock-search').click();
  await page.waitForFunction(()=>!stockLoading&&stockResults.length>0,null,{timeout:90000});await page.waitForFunction(()=>document.querySelector('#stock-preview').complete&&document.querySelector('#stock-preview').naturalWidth>0,null,{timeout:60000});
  const result=await page.evaluate(()=>selectedStock());assert.equal(result.provider,'openverse');
  for(const[width,height]of[[1440,900],[1024,768],[800,600]]){await page.setViewportSize({width,height});await page.screenshot({path:path.join(output,'02-live-openverse-'+width+'.png'),animations:'disabled'});}
  await page.setViewportSize({width:1440,height:900});await page.locator('#stock-import-background').click();await page.waitForFunction(()=>session?.cutout?.background?.attribution?.provider==='openverse'&&!busy&&!stockImporting,null,{timeout:90000});
  const composite=await page.evaluate(()=>session);await page.screenshot({path:path.join(output,'03-live-stock-composite.png'),animations:'disabled'});
  const png=page.waitForEvent('download');await page.locator('#cutout-export').click();await(await png).saveAs(path.join(output,'stock-background-composite.png'));await page.waitForFunction(()=>!busy);
  const project=page.waitForEvent('download');await page.locator('#file-menu-trigger').click();await page.locator('#save-project').click();const projectPath=path.join(output,'stock-background-composite.lremove');await(await project).saveAs(projectPath);await page.waitForFunction(()=>!busy);const prior=await page.evaluate(()=>session.id);await page.locator('#project-file').setInputFiles(projectPath);await page.waitForFunction(id=>session?.id!==id&&!busy,prior);assert.equal(await page.evaluate(()=>session.cutout.background.attribution.provider),'openverse');
  await page.locator('#studio-background-tab').click();await page.locator('#background-stock').click();await page.waitForFunction(()=>!stockLoading);await page.locator('#stock-import-image').click();await page.waitForFunction(()=>session?.source_attribution?.provider==='openverse'&&!busy&&!stockImporting,null,{timeout:90000});const imported=await page.evaluate(()=>session);assert.equal(await page.evaluate(()=>hasWorkingLayers(session)),true);
  await page.locator('#file-menu-trigger').click();await page.locator('#image-credits').click();await page.screenshot({path:path.join(output,'04-live-stock-credits.png'),animations:'disabled'});await page.locator('#credits-close').click();
  const imageProject=page.waitForEvent('download');await page.locator('#file-menu-trigger').click();await page.locator('#save-project').click();await(await imageProject).saveAs(path.join(output,'imported-stock-image.lremove'));await page.waitForFunction(()=>!busy);
  await page.locator('#workspace-generate').click();await page.waitForFunction(()=>generationModels.length>0&&!generationLoading);await page.locator('#gen-reference-tab').click();await page.locator('#gen-stock').click();await page.waitForFunction(()=>!stockLoading);await page.locator('#stock-import-reference').click();await page.waitForFunction(()=>generationReferences.length===1&&!stockImporting&&!busy,null,{timeout:90000});await page.screenshot({path:path.join(output,'05-live-stock-reference.png'),animations:'disabled'});
  const evidence={query:'forest',provider:'openverse',result,composite_session:composite.id,imported_session:imported.id,source_attribution:imported.source_attribution,background_attribution:composite.cutout.background.attribution,reference:await page.evaluate(()=>generationReferences[0]),project_credit_roundtrip:true,errors};fs.writeFileSync(path.join(output,'live-stock-results.json'),JSON.stringify(evidence,null,2));assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:true,title:result.title,license:result.license,creator:result.creator,errors}));
 }catch(error){await page.screenshot({path:path.join(output,'live-failure.png'),animations:'disabled'});throw error;}finally{await page.unrouteAll({behavior:'ignoreErrors'});await browser.close();}
})().catch(error=>{console.error(error);process.exit(1)});
