// Focused UI acceptance: menu dispatch uses a stock error fixture; cutout
// selection, history, and PNG export use the actual isolated preview backend.
const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const base=process.env.LOCAL_REMOVE_TEST_URL||'http://127.0.0.1:51273';
const out=path.resolve(process.argv[2]||'qa-artifacts/ui-redesign/quiet-checks');
fs.mkdirSync(out,{recursive:true});
(async()=>{
 const runtime=await(await fetch(base+'/api/local-remove/runtime')).json();
 assert.match(runtime.data_root.replaceAll('\\','/'),/\/qa-artifacts\/ui-redesign\/(profile|layer-test-profile)$/i);
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 const page=await browser.newPage({viewport:{width:1600,height:1000}});
 const errors=[],checks=[],imports=[];page.on('pageerror',error=>errors.push(error.message));
 const record=name=>{checks.push(name);console.log('PASS: '+name);};
 try{
  await page.addInitScript(()=>{localStorage.setItem('local-image.hardware-guide.v1','1');localStorage.setItem('local-image.first-ai-setup.v1','1');localStorage.setItem('local-image.first-task.v1','1');});
  await page.goto(base+'/remove');await page.waitForFunction(()=>settingsLoaded&&initCompleted);
  assert.equal(await page.locator('#stock-more-actions').count(),1,'Quiet controls are part of the rendered app');
  const fixture=require('./helpers/image-fixture.cjs').imageFixture();
  await page.locator('#file').setInputFiles({name:'Quiet controls.png',mimeType:'image/png',buffer:fixture});
  await page.waitForFunction(()=>session?.layer_stack&&!busy&&ready);
  await page.locator('#workspace-cutout').click();
  await page.locator('#layer-actions').click();await page.locator('#stack-mask').click();
  await page.waitForFunction(()=>!busy&&LocalImageLayers.selected()?.kind==='cutout');
  assert.equal(await page.locator('#cutout-export').isVisible(),false);
  assert.equal(await page.locator('#cutout-undo').isVisible(),false);
  assert.equal(await page.locator('#cutout-redo').isVisible(),false);
  assert.equal(await page.locator('#studio-export').isVisible(),true);
  assert.equal(await page.locator('#cutout-panel>.studio-footer').isVisible(),false);
  assert.equal(await page.locator('#background-stock').isVisible(),false);
  assert.equal(await page.locator('#background-folder').isVisible(),false);
  await page.screenshot({path:path.join(out,'cutout-after.png')});
  record('Cutout has one toolbar for history/export and no repeated Background headings/actions');
  await page.locator('[data-tool=rectangle]').click();
  const box=await page.locator('#photo').boundingBox();
  await page.mouse.move(box.x+box.width*.4,box.y+box.height*.4);await page.mouse.down();
  await page.mouse.move(box.x+box.width*.5,box.y+box.height*.5,{steps:6});await page.mouse.up();
  await page.waitForFunction(()=>hasSelection&&!busy);
  assert.equal(await page.locator('#cutout-refine').isEnabled(),true);
  await page.locator('#studio-export').click();assert.equal(await page.evaluate(()=>hasSelection),true);assert.match(await page.locator('#message').textContent(),/Apply or clear/);
  assert.equal(await page.locator('#cutout-apply-selection').isVisible(),false,'No duplicate Apply in hidden panel');
  await page.locator('#studio-undo').click();await page.waitForFunction(()=>!hasSelection&&!busy);
  await page.locator('#studio-redo').click();await page.waitForFunction(()=>hasSelection&&!busy);
  const before=await page.evaluate(()=>session.revision);
  await page.locator('#cutout-refine').click();
  await page.waitForFunction(revision=>session.revision>revision&&!busy&&!hasSelection,before);
  assert.equal(await page.locator('#cutout-panel>.studio-footer').isVisible(),false);
  const downloadWait=page.waitForEvent('download');await page.locator('#studio-export').click();
  const download=await downloadWait;await download.saveAs(path.join(out,'cutout-toolbar-export.png'));
  const png=fs.readFileSync(path.join(out,'cutout-toolbar-export.png'));
  assert.equal(png.subarray(0,8).toString('hex'),'89504e470d0a1a0a');
  record('Pending selection stays visible; toolbar history, Apply and real PNG export work');
  await page.waitForFunction(()=>!busy);
  await page.evaluate(()=>{stockResults=[{id:'quiet-fixture',title:'Menu dispatch test',thumbnail_url:'/api/local-remove/session/'+session.id+'/preview',license:'CC0',source_url:'https://example.test/photo'}];stockSelectedId='quiet-fixture';stockLoading=false;renderStockResults();updateStockControls();});
  assert.equal(await page.locator('.stock-import-actions>button.primary').getAttribute('id'),'stock-import-background');
  await page.locator('#stock-more-actions').focus();await page.keyboard.press('ArrowDown');
  assert.equal(await page.locator('#stock-import-image').evaluate(node=>node===document.activeElement),true);
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#stock-more-actions').evaluate(node=>node===document.activeElement),true);
  assert.equal(await page.locator('#stock-import-menu').evaluate(node=>node.matches(':popover-open')),false);
  await page.locator('#stock-expand').click();await page.locator('#stock-more-actions').click();
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#stock-dialog').getAttribute('data-docked'),'false','Menu Escape does not collapse expanded stock');
  await page.locator('#stock-expand').click();
  await page.route('**/api/local-remove/stock/import',route=>{imports.push(route.request().postDataJSON());return route.fulfill({status:400,json:{detail:'UI dispatch probe'}});});
  await page.locator('#stock-more-actions').click();await page.locator('#stock-import-image').click();
  await page.waitForFunction(()=>!busy&&!stockImporting&&document.querySelector('#stock-status').textContent.includes('UI dispatch probe'));
  assert.equal(imports.at(-1).target,'image');
  await page.locator('#stock-import-background').click();
  await page.waitForFunction(()=>!busy&&!stockImporting);
  assert.equal(imports.at(-1).target,'background');
  assert.ok(imports.at(-1).session_id);
  await page.locator('#workspace-retouch').click();
  assert.equal(await page.locator('.stock-import-actions>button.primary').getAttribute('id'),'stock-import-image');
  record('Stock primary follows context; overflow keyboard/Escape and original import handlers remain functional');
  await page.locator('#stock-close').click();await page.locator('#workspace-cutout').click();
  await page.locator('#stack-background').click();assert.equal(await page.locator('#stack-background-folder').isVisible(),true);assert.equal(await page.locator('#stack-background-assets').isVisible(),true);
  record('Background commands remain discoverable when the Assets dock is hidden');
  assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,errors,stock:'Fixture validates action dispatch; does not claim a downloaded stock image.',export:'Actual backend PNG export after a manual cutout edit.'},null,2));
 }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
