// Generative editing uses real imported sessions. GPU responses are mocked.
const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const base=process.env.LOCAL_REMOVE_TEST_URL||'http://127.0.0.1:51273';
const output=path.resolve(process.argv[2]||'qa-artifacts/ui-redesign/generation-modes-test');fs.mkdirSync(output,{recursive:true});
const fixture=require('./helpers/image-fixture.cjs').imageFixture();
const models=['qwen','z-image-turbo','ernie-image'].map(id=>({id,label:{qwen:'Qwen Image 2.1','z-image-turbo':'Z-Image Turbo','ernie-image':'ERNIE Image'}[id],available:true,variants:[{id:'test',label:'Test precision',available:true}],capabilities:{text_to_image:true,image_reference:id==='qwen',image_to_image:id==='z-image-turbo',max_references:id==='qwen'?10:id==='z-image-turbo'?1:0,transparent:id==='qwen',negative_prompt:id==='qwen',denoise:id==='z-image-turbo',lora:id!=='ernie-image'},defaults:{variant:'test',width:1024,height:1024,steps:id==='qwen'?25:id==='z-image-turbo'?8:50,guidance:1},limits:{min_dimension:256,max_dimension:2048,dimension_step:32,max_pixels:4194304,min_steps:1,max_steps:100,min_guidance:1,max_guidance:id==='qwen'?10:1}}));
async function main(){
 const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'msedge'}),context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[],requests=[],saveRequests=[];
 let holdGeneration=false,releaseGeneration=null;
 page.on('pageerror',error=>errors.push(error.message));
 page.on('request',request=>{if(request.method()==='POST'&&/\/(save|export-project)$/.test(new URL(request.url()).pathname))saveRequests.push(request.url());});
 await context.addInitScript(()=>{localStorage.setItem('local-image.hardware-guide.v1','1');localStorage.setItem('local-image.first-ai-setup.v1','1');});
 await context.route('**/api/local-remove/generation/models**',route=>route.fulfill({json:{connected:true,default_model:'qwen',models}}));
 await context.route('**/api/local-remove/generator/download',route=>route.fulfill({json:{running:false,models:[]}}));
 await context.route('**/api/local-remove/generation/upscale/models',route=>route.fulfill({json:{enabled:false}}));
 await context.route('**/api/local-remove/generation',async route=>{
   const payload=route.request().postDataJSON();requests.push(payload);
   if(holdGeneration)await new Promise(resolve=>{releaseGeneration=resolve;});
   const response=await page.request.post(base+'/api/local-remove/import',{headers:{'x-local-remove-token':route.request().headers()['x-local-remove-token']},multipart:{file:{name:'Generated '+requests.length+'.png',mimeType:'image/png',buffer:fixture}}});
   const session=await response.json();session.generation=payload;
   await route.fulfill({json:{session,width:session.width,height:session.height,seed:17,model:payload.model}});
 });
 const readyMode=mode=>page.waitForFunction(mode=>LocalImageGenerationStudio.mode()===mode&&!LocalImageGenerationStudio.isModeBusy()&&!busy&&!generationLoading,mode);
 try{
   await page.goto(base+'/remove');await page.waitForFunction(()=>settingsLoaded);
   await page.locator('#file').setInputFiles({name:'Original A.png',mimeType:'image/png',buffer:fixture});await page.waitForFunction(()=>session&&!busy);
   const source=await page.evaluate(()=>({id:session.id,revision:session.revision}));
   await page.evaluate(()=>{mc.fillStyle='white';mc.fillRect(10,10,20,20);refreshMask();});
   const originalMask=await page.evaluate(()=>mask.toDataURL());
   await page.locator('#workspace-generate').click();await readyMode('edit');
   assert.equal(await page.locator('#generation-edit-tab').getAttribute('aria-selected'),'true');
   assert.equal(await page.locator('#gen-run').textContent(),'Apply edit');
   assert.match(await page.locator('#generation-edit-source').textContent(),/Original A/);
   assert.equal(await page.evaluate(()=>generationReferences[0].id),source.id);
   assert.equal(await page.locator('#gen-references [data-primary-source=true] button').isDisabled(),true);
   assert.equal(await page.locator('#gen-model option[value="ernie-image"]').isDisabled(),true,'Text-only models cannot silently ignore the edit source');
   await page.locator('#gen-prompt').fill('Change the red object to blue, preserve the scene');
   await page.locator('#gen-steps').fill('31');await page.locator('#gen-width').fill('1024');await page.locator('#gen-height').fill('1024');
   await page.locator('#generation-reference-file').setInputFiles({name:'Style B.png',mimeType:'image/png',buffer:fixture});await page.waitForFunction(()=>generationReferences.length===2&&!busy);
   const extra=await page.evaluate(()=>generationReferences[1].id);
   await page.screenshot({path:path.join(output,'edit-source-bound.png'),animations:'disabled'});
   await page.locator('#generation-create-tab').click();await readyMode('create');
   assert.equal(await page.locator('#generation-blank-canvas').isVisible(),true);
   assert.equal(await page.locator('#stage').isVisible(),false,'Create does not display source A under a new-image prompt');
   assert.deepEqual(await page.evaluate(()=>generationReferences),[]);
   assert.equal(await page.locator('#gen-prompt').inputValue(),'');
   assert.equal(await page.evaluate(()=>session.id),source.id,'Blank Create preserves the source session');
   for(const id of ['studio-export','save','save-project','save-project-as','undo','redo','merge','close-image','fit','before'])assert.equal(await page.locator('#'+id).isDisabled(),true,id+' cannot act on hidden source A');
   for(const id of ['save','return','save-unique','save-project','document-save'])await page.locator('#'+id).dispatchEvent('click');
   await page.keyboard.press('Control+s');assert.equal(saveRequests.length,0);
   await page.locator('#workspace-generate').click();await readyMode('create');
   assert.equal(await page.evaluate(()=>LocalImageGenerationStudio.isCreatingBlank()),true,'Clicking Generate again retains active mode');
   await page.locator('#gen-model').selectOption('z-image-turbo');await page.locator('#gen-prompt').fill('A fresh sunset over a city');
   holdGeneration=true;await page.locator('#gen-run').click();await page.waitForFunction(()=>busy);
   assert.equal(await page.locator('#generation-edit-tab').isDisabled(),true);
   await page.locator('#generation-edit-tab').dispatchEvent('click');assert.equal(await page.evaluate(()=>LocalImageGenerationStudio.mode()),'create','A pending response cannot switch into or overwrite another mode');
   while(!releaseGeneration)await new Promise(resolve=>setTimeout(resolve,10));holdGeneration=false;releaseGeneration();
   await page.waitForFunction(()=>!busy&&!LocalImageGenerationStudio.isCreatingBlank()&&!!session?.generation);
   const created=await page.evaluate(()=>session.id);
   assert.notEqual(created,source.id);assert.deepEqual(requests[0].reference_session_ids,[]);assert.equal(requests[0].model,'z-image-turbo');assert.equal(requests[0].steps,8);assert.equal(requests[0].denoise,undefined);
   assert.equal(await page.locator('#stage').isVisible(),true);assert.equal(await page.locator('#studio-export').isEnabled(),true);
   await page.locator('#generation-edit-tab').click();await readyMode('edit');
   assert.equal(await page.evaluate(()=>session.id),source.id,'Switching back restores the preserved edit document');
   assert.equal(await page.evaluate(()=>session.revision),source.revision);assert.equal(await page.evaluate(()=>mask.toDataURL()),originalMask,'Source selection/cache survives blank generation and return');
   assert.equal(await page.locator('#gen-prompt').inputValue(),'Change the red object to blue, preserve the scene');
   assert.equal(await page.locator('#gen-model').inputValue(),'qwen');assert.equal(await page.locator('#gen-steps').inputValue(),'31');
   assert.deepEqual(await page.evaluate(()=>generationReferences.map(reference=>reference.id)),[source.id,extra]);
   await page.locator('#gen-run').click();await page.waitForFunction(()=>!busy&&session?.generation?.model==='qwen');
   const edited=await page.evaluate(()=>session.id);
   assert.deepEqual(requests[1].reference_session_ids,[source.id,extra]);assert.equal(requests[1].steps,31);
   assert.deepEqual(await page.evaluate(()=>generationReferences.map(reference=>reference.id)),[edited,extra],'The next edit is bound to the visible edited result');
   assert.equal(await page.evaluate(id=>openDocuments.get(id).revision,source.id),source.revision,'Original source pixels/revision remain preserved');
   await page.locator('#generation-create-tab').click();await readyMode('create');
   assert.equal(await page.locator('#gen-prompt').inputValue(),'A fresh sunset over a city');assert.equal(await page.locator('#gen-model').inputValue(),'z-image-turbo');assert.deepEqual(await page.evaluate(()=>generationReferences),[]);assert.equal(await page.locator('#generation-blank-canvas').isVisible(),true);
   await page.screenshot({path:path.join(output,'create-preserves-edit.png'),animations:'disabled'});
   await page.locator('#generation-edit-tab').click();await readyMode('edit');assert.equal(await page.evaluate(()=>session.id),edited);
   await page.locator('#gen-model').selectOption('z-image-turbo');await page.locator('#gen-reference-tab').click();
   await page.locator('#gen-references .generation-reference').nth(1).locator('button').click();
   assert.equal(await page.locator('#gen-denoise-options').isVisible(),true,'Starting-image models retain variation strength');
   await page.locator('#gen-denoise').fill('45');await page.locator('#gen-denoise').dispatchEvent('input');
   await page.locator('#gen-prompt-tab').click();await page.locator('#gen-run').click();await page.waitForFunction(()=>!busy&&session?.generation?.model==='z-image-turbo');
   assert.deepEqual(requests[2].reference_session_ids,[edited]);assert.equal(requests[2].denoise,.45);
   const visible=await page.evaluate(()=>session.id),download=page.waitForEvent('download');
   await page.locator('#studio-export').click();await(await download).saveAs(path.join(output,'visible-edit-export.png'));await page.waitForFunction(()=>!busy);
   assert.ok(saveRequests.at(-1).includes('/session/'+visible+'/save'),'Shared Export uses the visible edit result');
   assert.equal(fs.readFileSync(path.join(output,'visible-edit-export.png')).subarray(1,4).toString(),'PNG');
   assert.deepEqual(errors,[]);
   console.log('PASS: automatic source-bound editing, independent Create/Edit settings and references, blank-canvas command safety, original document/selection preservation, visible-result continuation, model-dependent edit capability/strength, in-flight mode lock and real visible-result PNG export. GPU responses mocked.');
 }catch(error){await page.screenshot({path:path.join(output,'failure.png'),animations:'disabled'});throw error;}
 finally{if(releaseGeneration)releaseGeneration();await context.unrouteAll({behavior:'ignoreErrors'});await browser.close();}
}
main().catch(error=>{console.error(error);process.exitCode=1;});
