// Real Python-rendered production page + real local document IO. All inference
// and progress responses are controlled; this never submits a model/GPU job.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {execFileSync}=require('node:child_process'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),base=process.env.LOCAL_REMOVE_TEST_URL,profile=process.env.MIGRATION_REAL_PROFILE;
assert.ok(base&&profile);assert.equal(new URL(base).hostname,'127.0.0.1');assert.ok(path.resolve(profile).startsWith(path.join(root,'qa-artifacts')+path.sep));
const out=path.join(root,'qa-artifacts/migration/full-generation');fs.mkdirSync(out,{recursive:true});
if(fs.existsSync(path.join(out,'results.json'))){const archive=path.join(out,'report-history'),stamp=Date.now();fs.mkdirSync(archive,{recursive:true});fs.copyFileSync(path.join(out,'results.json'),path.join(archive,`results-${stamp}.json`));if(fs.existsSync(path.join(out,'failure.png')))fs.copyFileSync(path.join(out,'failure.png'),path.join(archive,`failure-${stamp}.png`));}
const hash=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
(async()=>{
 const runtime=await(await fetch(base+'/api/local-remove/runtime')).json();assert.equal(path.resolve(runtime.data_root),path.resolve(profile));
 const catalog=await(await fetch(base+'/api/local-remove/generation/models')).json();
 const models=catalog.models.filter(model=>['qwen','z-image-turbo','flux2-klein-4b'].includes(model.id)).map(model=>({...model,available:true,reason:'',variants:model.variants.map(value=>({...value,available:true,reason:''})),capabilities:{...model.capabilities,loras:true,lora:true}}));
 const browser=await chromium.launch({channel:'msedge',headless:true}),context=await browser.newContext({viewport:{width:1366,height:768},acceptDownloads:true}),page=await context.newPage();
 const checks=[],errors=[],requests=[],blocked=[],inference=[],outputs=[],assets=[],shots=[],cameras=[];let fixtureCatalog=false,next='success',release=null,passed=false,failure=null,htmlHash=null;
 page.setDefaultTimeout(15000);
 let progress={active:false,job_id:null,stage:'idle',stage_label:'',progress:null,elapsed_seconds:0};
 await context.route('**/*',async route=>{
  const request=route.request(),url=new URL(request.url());if(url.origin!==new URL(base).origin){blocked.push(url.href);return route.abort('blockedbyclient');}
  if(url.pathname==='/api/local-remove/generation/models'&&fixtureCatalog)return route.fulfill({json:{...catalog,models}});
  if(url.pathname==='/api/local-remove/generation/progress')return route.fulfill({json:progress});
  if(url.pathname==='/api/local-remove/generation'&&request.method()==='POST'){
   const payload=request.postDataJSON(),action=next;next='success';inference.push({payload,action});
   if(action==='failure')return route.fulfill({status:400,json:{detail:'Controlled model dependency is missing'}});
   if(action==='network')return route.abort('failed');
   progress={active:true,job_id:payload.operation_id||crypto.randomUUID(),model:payload.model,stage:'sampling',stage_label:'Generating image',progress:{value:7,max:40,percent:17.5},elapsed_seconds:4};
   if(action==='hold')await new Promise(resolve=>{release=resolve;});
   const value=JSON.parse(execFileSync(path.join(root,'.venv/Scripts/python.exe'),[path.join(root,'tests/helpers/seed_generation_response.py'),profile,base,JSON.stringify(payload),...(action==='library-failure'?['--skip-library']:[])],{encoding:'utf8',env:{...process.env,PYTHONIOENCODING:'utf-8'}}).trim().split(/\r?\n/).at(-1));outputs.push(value.session.id);
   progress={...progress,active:false,stage:'completed',stage_label:'Image ready',progress:null};return route.fulfill({json:value});
  }
  if(request.method()!=='GET'&&(/^\/api\/local-remove\/(?:generation\/upscale$|generator|qwen\/download|setup|loras\/download|stock\/import)/.test(url.pathname)||/\/cutout$|\/cutout\/generate-background$/.test(url.pathname))){blocked.push(url.pathname);return route.abort('blockedbyclient');}
  if(['/api/local-remove/stock/search','/api/local-remove/loras/search','/api/local-remove/loras/files'].includes(url.pathname)){blocked.push(url.pathname);return route.abort('blockedbyclient');}
  return route.continue();
 });
 await context.addInitScript(()=>{localStorage.setItem('local-image.hardware-guide.v1','1');localStorage.setItem('local-image.first-ai-setup.v1','1');localStorage.setItem('local-image.first-task.v1','1');window.__generationCsp=[];document.addEventListener('securitypolicyviolation',event=>window.__generationCsp.push({directive:event.violatedDirective,blocked:event.blockedURI}));});
 page.on('pageerror',error=>errors.push(error.stack));page.on('request',request=>{if(request.url().includes('/api/'))requests.push({method:request.method(),path:new URL(request.url()).pathname});});page.on('response',response=>{if(response.url().includes('/frontend-assets/'))void response.body().then(body=>assets.push({path:new URL(response.url()).pathname,sha256:hash(body),status:response.status()}));});
 const generation=page.getByRole('region',{name:'Image generation',exact:true});
 const state=()=>page.evaluate(()=>window.LocalImageReactFeatures.generation.getSnapshot());
 const idle=()=>page.waitForFunction(()=>!window.LocalImageEditor.getSnapshot().busy&&!window.LocalImageReactFeatures.generation.getSnapshot().working&&!window.LocalImageReactFeatures.generation.getSnapshot().loading&&!window.LocalImageReactFeatures.generation.getSnapshot().context.busy);
 const editor=()=>page.evaluate(()=>window.LocalImageEditor.getSnapshot());
 const menu=async(group,label)=>{await page.getByRole('menuitem',{name:group,exact:true}).click();await page.getByRole('menuitem',{name:new RegExp('^'+label.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'(?:\\s+Ctrl\\+.*)?$')}).click();};
 const choose=async(action,files)=>{const [chooser]=await Promise.all([page.waitForEvent('filechooser'),action()]);await chooser.setFiles(files);await idle();};
 const view=()=>page.evaluate(()=>{const state=window.LocalImageEditor.getSnapshot(),canvas=window.LocalImageEditor.canvas.getSnapshot(),viewport=document.querySelector('#viewport'),scale=canvas.photoZoom*state.document.width/canvas.previewWidth;return {zoom:canvas.photoZoom,x:(viewport.clientWidth/2-canvas.panX)/scale,y:(viewport.clientHeight/2-canvas.panY)/scale,canvas,editorCanvas:state.canvas,stageTransform:document.querySelector('#stage').style.transform};});
 const shot=async name=>{const file=path.join(out,name);await page.screenshot({path:file,animations:'disabled'});shots.push(file);};
 const sourceBytes=require('./helpers/image-fixture.cjs').imageFixture(1536,1024);
 const mutationCount=()=>requests.filter(item=>item.method!=='GET'&&/\/(save|export-project|close-sessions|stack\/undo|stack\/redo)$/.test(item.path)).length;
 try{
  const response=await page.goto(base+'/remove');htmlHash=hash(await response.body());await page.waitForFunction(()=>document.body.dataset.reactReady==='true'&&window.LocalImageReactFeatures?.generation);await idle();
  assert.equal(await page.evaluate(()=>typeof session),'undefined');assert.equal(await page.evaluate(()=>typeof LocalImageGenerationBridge),'undefined');
  assert.equal(await page.locator('#generation-panel,#generation-panel-scroll,#gen-run,#gen-prompt,#refine-dialog,#refine-draft-prompt,#refine-final-run').count(),0,'Old generation/refinement form copies are absent');
  await choose(()=>page.getByRole('button',{name:'Open image…',exact:true}).click(),{name:'Generation source.png',mimeType:'image/png',buffer:sourceBytes});const source=(await editor()).document;
  await page.getByRole('combobox',{name:'Image zoom',exact:true}).selectOption('0.5');
  await page.getByRole('button',{name:'Rectangle selection (R)',exact:true}).click();const photoBox=await page.locator('#photo').boundingBox();await page.mouse.move(photoBox.x+photoBox.width*.15,photoBox.y+photoBox.height*.15);await page.mouse.down();await page.mouse.move(photoBox.x+photoBox.width*.25,photoBox.y+photoBox.height*.25,{steps:5});await page.mouse.up();await page.waitForFunction(()=>window.LocalImageEditor.getSnapshot().canvas.hasSelection);
  await page.evaluate(()=>{window.__persistentStage=document.querySelector('#stage');window.__persistentPhoto=document.querySelector('#photo');});
  const preserve=()=>page.evaluate(()=>{const state=window.LocalImageEditor.getSnapshot();return {id:state.document.id,revision:state.document.revision,mask:document.querySelector('#selection').toDataURL(),undo:state.canvas.canUndoSelection};});
  const before=await preserve(),cameraBefore=await view();
  await page.locator('#workspace-generate').click();await idle();assert.equal((await state()).mode,'edit');assert.equal((await state()).drafts.edit.references[0].id,source.id);
  assert.equal(await generation.getByRole('button',{name:'Apply edit',exact:true}).isDisabled(),true,'Actual unavailable backend models block submission');
  fixtureCatalog=true;await generation.getByRole('button',{name:'Refresh models',exact:true}).click();await idle();
  await generation.getByLabel('Describe the changes',{exact:true}).fill('Edit draft stays independent');await generation.getByRole('tab',{name:'Create',exact:true}).click();await idle();await generation.getByLabel('Prompt',{exact:true}).fill('Controlled new image');
  await generation.getByLabel('Create new width',{exact:true}).fill('512');await generation.getByLabel('Create new width',{exact:true}).press('Tab');
  assert.equal((await state()).drafts.create.width,512);assert.equal((await state()).drafts.create.height,512);assert.equal((await state()).drafts.edit.prompt,'Edit draft stays independent');assert.equal((await state()).drafts.create.references.length,0);
  const writes=mutationCount();await page.keyboard.press('Control+z');await page.keyboard.press('Control+s');await page.keyboard.press('Control+Alt+s');await page.keyboard.press('Control+w');await page.evaluate(async()=>{const commands=window.LocalImageEditor.commands;await commands.overwrite();await commands.saveProject();await commands.closeImage();await commands.undo();});assert.equal(mutationCount(),writes,'Blank Create must not save, close or undo the hidden editor document');
  assert.deepEqual(await preserve(),before);assert.equal(await page.evaluate(()=>document.querySelector('#stage')===window.__persistentStage&&document.querySelector('#photo')===window.__persistentPhoto),true);
  await page.locator('#viewport').hover();await page.mouse.wheel(0,240);assert.equal((await editor()).canvas.photoZoom,cameraBefore.zoom,'Wheel over blank Create cannot change the hidden image camera');
  await page.locator('#workspace-retouch').click();await idle();await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));const restoredCamera=await view();cameras.push({before:cameraBefore,after:restoredCamera});for(const key of ['zoom','x','y'])assert.ok(Math.abs(restoredCamera[key]-cameraBefore[key])<.001,'Canvas '+key+' survives a blank generation roundtrip: '+JSON.stringify({before:cameraBefore,after:restoredCamera}));
  await page.locator('#workspace-generate').click();await idle();await generation.getByRole('tab',{name:'Create',exact:true}).click();await idle();
  checks.push('Actual metadata missing-model gating, independent Create/Edit drafts and explicit blank-view Save/Close/history guards preserve the mounted canvas and selection');
  await generation.getByRole('button',{name:'Browse create new models',exact:true}).click();const modelDialog=page.getByRole('dialog',{name:'Local image models',exact:true});await modelDialog.waitFor();await page.waitForFunction(()=>!window.LocalImageReactFeatures.models.getSnapshot().loading);await modelDialog.getByRole('button',{name:'Use this model',exact:true}).click();assert.equal((await state()).drafts.create.modelId,await page.evaluate(()=>window.LocalImageReactFeatures.models.getSnapshot().selectedModelId));
  await generation.getByRole('button',{name:/Styles \/ LoRAs/}).click();const loraDialog=page.getByRole('dialog',{name:'LoRA library',exact:true});await loraDialog.waitFor();await page.waitForFunction(()=>!window.LocalImageReactFeatures.models.getSnapshot().loading);assert.equal(await page.evaluate(()=>window.LocalImageReactFeatures.models.getSnapshot().context.modelId),(await state()).drafts.create.modelId);await page.keyboard.press('Escape');
  checks.push('React generation model selection and live LoRA context use feature ports without legacy form inputs');
  next='failure';await generation.getByRole('button',{name:'Generate image',exact:true}).click();await idle();assert.match((await state()).error,/Controlled model dependency/);assert.equal(inference.length,1);assert.equal((await editor()).document.id,source.id);
  next='hold';await generation.getByRole('button',{name:'Generate image',exact:true}).click();await page.waitForFunction(()=>window.LocalImageReactFeatures.generation.getSnapshot().progress?.stage==='sampling');assert.match(await generation.innerText(),/7 \/ 40/);assert.equal((await editor()).busy,true);assert.equal(await generation.getByRole('button',{name:'Stop generation',exact:true}).isDisabled(),true,'Stop stays disabled until the backend reports a cancellable job');await page.evaluate(()=>window.LocalImageReactFeatures.generation.stopWatching());assert.match((await state()).status,/has not been cancelled/);
  assert.equal(await page.locator('#workspace-retouch').isDisabled(),true);await page.evaluate(id=>window.LocalImageEditor.commands.openRecent(id),source.id);assert.equal((await editor()).document.id,source.id,'Document navigation remains reserved while inference is pending');
  const token=await page.evaluate(()=>window.__LOCAL_IMAGE_BOOTSTRAP__.token);const otherResponse=await page.request.post(base+'/api/local-remove/import',{headers:{'x-local-remove-token':token},multipart:{file:{name:'Independent reference.png',mimeType:'image/png',buffer:sourceBytes}}});assert.equal(otherResponse.status(),200);const other=await otherResponse.json();release();release=null;await idle();assert.equal(inference.length,2);assert.equal((await editor()).document.id,(await state()).modeDocuments.create.id);assert.equal((await state()).mode,'create');
  checks.push('Controlled failure is not retried; exact fixture sampler values appear; pausing updates keeps inference pending and shared busy ownership blocks document navigation until accepted preview');
  await generation.getByRole('tab',{name:'Create',exact:true}).click();await idle();next='network';await generation.getByRole('button',{name:'Generate image',exact:true}).click();await idle();assert.equal((await state()).uncertain,true);const count=inference.length;assert.equal(await generation.getByRole('button',{name:'Generate image',exact:true}).isDisabled(),true);await generation.getByRole('button',{name:'Check backend operation',exact:true}).click();await page.waitForFunction(()=>!window.LocalImageReactFeatures.generation.getSnapshot().uncertain);assert.equal(inference.length,count);
  await generation.getByRole('button',{name:'Generate image',exact:true}).click();await idle();const generated=(await editor()).document;assert.ok(generated.generation);assert.equal((await state()).modeDocuments.create.id,generated.id);assert.equal(await generation.getByRole('progressbar').count(),0,'Completed requests never leave an unfinished sampler bar');
  const [download]=await Promise.all([page.waitForEvent('download',{timeout:30000}),menu('File','Save project')]);const projectPath=path.join(out,'generated-settings.lremove');await download.saveAs(projectPath);assert.ok(fs.statSync(projectPath).size>0);await choose(()=>menu('File','Open project…'),projectPath);assert.equal((await state()).mode,'edit');assert.equal((await state()).drafts.edit.prompt,generated.generation.prompt);
  await generation.getByLabel('Describe the changes',{exact:true}).fill('Independent next edit instruction');await page.evaluate(()=>window.LocalImageEditor.commands.openRecent(window.LocalImageEditor.getSnapshot().document.id));await idle();assert.equal((await state()).drafts.edit.prompt,'Independent next edit instruction','Accepting the same document again must not replace its UI draft with stored generation metadata');
  checks.push('Controlled connection abort leaves uncertain outcome until explicit idle check; deliberate retry succeeds and real project export/reopen restores generation settings');
  await generation.getByRole('tablist',{name:'Generation mode',exact:true}).getByRole('tab',{name:'Refine',exact:true}).click();await idle();await generation.getByRole('button',{name:'Use current as draft',exact:true}).click();const draftId=(await state()).selectedDraftId;assert.ok(draftId);await generation.getByRole('tablist',{name:'Refinement step',exact:true}).getByRole('tab',{name:'Refine',exact:true}).click();const final=generation.getByRole('region',{name:'Refinement settings',exact:true});await final.getByLabel('Describe the changes',{exact:true}).fill('Controlled refine changes');await final.getByLabel('Refinement width',{exact:true}).fill('512');await final.getByLabel('Refinement width',{exact:true}).press('Tab');
  const sourceBefore=(await editor()).document.id,beforeWrites=mutationCount();await page.keyboard.press('Control+z');await page.evaluate(()=>window.LocalImageEditor.commands.undo());assert.equal(mutationCount(),beforeWrites);assert.equal((await editor()).document.id,sourceBefore);
  next='hold';await final.getByRole('button',{name:'Refine selected draft',exact:true}).click();await page.waitForFunction(()=>window.LocalImageReactFeatures.generation.getSnapshot().progress?.stage==='sampling');await page.evaluate(data=>window.LocalImageReactFeatures.generation.addDraft(data),other);release();release=null;await idle();const refinedState=await state();assert.ok(refinedState.resultImages.some(item=>item.draftId===draftId));assert.equal(refinedState.selectedDraftId,other.id);assert.equal(refinedState.selectedResultId,null);assert.equal(inference.at(-1).payload.reference_session_ids[0],draftId);
  await page.evaluate(id=>window.LocalImageReactFeatures.generation.selectDraft(id),draftId);const selectedResult=(await state()).selectedResultId;assert.ok(selectedResult);await page.keyboard.press('Control+w');const closeDialog=page.getByRole('alertdialog',{name:'Close image?',exact:true});await closeDialog.waitFor();await closeDialog.getByRole('button',{name:'Cancel',exact:true}).click();await idle();assert.equal((await editor()).document.id,selectedResult);assert.equal((await state()).mode,'edit');assert.equal((await page.request.get(base+'/api/local-remove/session/'+sourceBefore)).status(),200);
  checks.push('Refinement keeps selected draft first, associates late results with their original draft, blocks hidden history and routes cancelled Ctrl+W to the visible selected result');
  for(const [width,height]of [[800,560],[1366,768],[1920,1080]]){await page.setViewportSize({width,height});await shot(`generation-${width}-${height}.png`);assert.equal(await page.evaluate(()=>document.querySelector('#stage')===window.__persistentStage&&document.querySelector('#photo')===window.__persistentPhoto),true);const box=await generation.boundingBox();assert.ok(box.height>100&&box.width>150);}
  await page.setViewportSize({width:1366,height:768});await generation.getByRole('tablist',{name:'Generation mode',exact:true}).getByRole('tab',{name:'Refine',exact:true}).click();await idle();await shot('refinement.png');
  for(const workspace of ['retouch','cutout']){await page.locator('#workspace-'+workspace).click();await idle();assert.equal(await page.locator('#canvas-region').isVisible(),true);assert.equal((await editor()).document.id,selectedResult);await page.locator('#workspace-generate').click();await idle();await generation.getByRole('tablist',{name:'Generation mode',exact:true}).getByRole('tab',{name:'Refine',exact:true}).click();await idle();}
  checks.push('Refine to Retouch/Cutout restores the retained canvas without remounting it');
  await choose(()=>menu('File','Open images…'),{name:'Generated background target.png',mimeType:'image/png',buffer:sourceBytes});
  await menu('Layer','Add editable mask');await idle();const target=(await editor()).document,targetMask=(await editor()).selectedLayerId;assert.equal((await editor()).workspace,'cutout');
  await page.getByRole('button',{name:'Hide Original',exact:true}).click();await idle();await page.getByRole('button',{name:'Rectangle selection (R)',exact:true}).click();
  const targetBox=await page.locator('#photo').boundingBox();await page.mouse.move(targetBox.x+targetBox.width*.04,targetBox.y+targetBox.height*.05);await page.mouse.down();await page.mouse.move(targetBox.x+targetBox.width*.24,targetBox.y+targetBox.height*.25,{steps:5});await page.mouse.up();await page.waitForFunction(()=>window.LocalImageEditor.getSnapshot().canvas.hasSelection);
  await page.getByRole('button',{name:'Erase selection',exact:true}).click();await idle();const beforeBackground=(await editor()).document;
  await page.locator('#workspace-generate').click();await idle();await generation.getByRole('tab',{name:'Create',exact:true}).click();await idle();
  assert.equal((await state()).context.backgroundTarget.id,target.id);next='library-failure';await generation.getByRole('button',{name:'Generate image',exact:true}).click();await idle();
  const backgroundSource=(await editor()).document;assert.match((await state()).status,/library persistence failure/);
  const library=await(await page.request.get(base+'/api/local-remove/generation/library')).json();assert.equal(library.items.some(item=>item.id===backgroundSource.id),false);
  assert.match(await generation.locator('.li-generation-result-actions').innerText(),/Generated background target/);
  const beforeAttach=inference.length;await generation.getByRole('button',{name:'Use as background',exact:true}).click();await idle();const attached=(await editor()).document;
  assert.equal(attached.id,target.id);assert.equal((await editor()).workspace,'cutout');assert.equal(attached.revision,beforeBackground.revision+1);assert.equal(attached.layer_stack.length,beforeBackground.layer_stack.length+1);assert.equal(inference.length,beforeAttach);
  const selectedBackgroundId=(await editor()).selectedLayerId,backgroundLayer=attached.layer_stack.find(layer=>layer.id===selectedBackgroundId);assert.equal(backgroundLayer.kind,'image');assert.ok(attached.layer_stack.indexOf(backgroundLayer)<attached.layer_stack.findIndex(layer=>layer.id===targetMask));
  const pixel=await page.evaluate(async url=>{const response=await fetch(url),blob=await response.blob(),bitmap=await createImageBitmap(blob),canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;const drawing=canvas.getContext('2d');drawing.drawImage(bitmap,0,0);const value=[...drawing.getImageData(100,100,1,1).data];bitmap.close();return value;},`/api/local-remove/session/${encodeURIComponent(target.id)}/preview?full=true&revision=${attached.revision}`);assert.deepEqual(pixel,[120,80,150,255]);
  assert.equal((await page.request.get(base+'/api/local-remove/session/'+backgroundSource.id)).status(),200);await shot('generated-background-applied.png');
  checks.push('Named preserved cutout target receives actual generated-session pixels in a new layer below its mask, even when the controlled result has no library copy; no inference is resubmitted');
  assert.deepEqual(errors,[]);assert.deepEqual(await page.evaluate(()=>window.__generationCsp),[]);assert.deepEqual(blocked,[]);passed=true;
 }catch(error){failure=error.stack;if(release){release();release=null;}await shot('failure.png').catch(()=>{});throw error;}
 finally{fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({passed,failure,runtime,checks,errors,requests,blocked,inference,outputs,assets,htmlHash,shots,cameras,evidence:'Production composed page; actual local document/project APIs; controlled model availability/inference/progress responses; no model or GPU executed'},null,2));await browser.close();}
 console.log(`PASS React Generation: ${checks.length} composed groups; ${out}`);
})().catch(error=>{console.error(error);process.exitCode=1;});
