// Dock presentation contract only. Stock responses are fixtures; no GPU or downloads.
const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const base=process.env.LOCAL_REMOVE_TEST_URL||'http://127.0.0.1:51273';
const output=path.resolve(process.argv[2]||'qa-artifacts/ui-redesign/stock-contract');
fs.mkdirSync(output,{recursive:true});
(async()=>{
  const browser=await chromium.launch({headless:true,channel:'msedge'});
  const page=await browser.newPage({viewport:{width:1440,height:960}}),errors=[];
  let providerRequests=0,failProviders=true,importRequests=0;
  page.on('pageerror',error=>errors.push(error.message));
  await page.addInitScript(()=>{
    localStorage.setItem('local-image.hardware-guide.v1','1');
    localStorage.setItem('local-image.first-ai-setup.v1','1');
  });
  await page.route('**/api/local-remove/stock/providers',route=>{providerRequests++;return failProviders?route.fulfill({status:503,json:{detail:'Fixture provider temporarily unavailable'}}):route.fulfill({json:{providers:[{id:'openverse',label:'Openverse',available:true}],default_provider:'openverse'}});});
  await page.route('**/api/local-remove/stock/import',route=>{importRequests++;return route.fulfill({status:503,json:{detail:'Import should not be called during busy-state test'}});});
  await page.route('**/api/local-remove/stock/search**',route=>route.fulfill({json:{results:Array.from({length:12},(_,i)=>({id:'photo-'+i,title:i===1?'<img onerror="bad()">':'Landscape '+(i+1),creator:'Example creator',license:'CC BY 4.0',license_url:'https://creativecommons.org/licenses/by/4.0/',source_url:'https://example.com/photo',attribution:'Example photo by Example creator',width:1400,height:1000,thumbnail_url:i===2?'/fixture-stock-missing.png':'/fixture-stock-preview.png'})),next_page:null}}));
  await page.route('**/fixture-stock-missing.png',route=>route.fulfill({status:404,body:'Unavailable preview fixture'}));
  await page.route('**/fixture-stock-preview.png',route=>route.fulfill({contentType:'image/png',body:fs.readFileSync(path.join(__dirname,'../docs/images/examples/z-image-realism.png'))}));
  await page.route('**/api/local-remove/generation/models**',route=>route.fulfill({json:{connected:true,default_model:'qwen',models:[{id:'qwen',label:'Fixture Qwen',available:true,variants:[{id:'int8',label:'Fixture',available:true}],capabilities:{text_to_image:true,image_reference:true,max_references:1,transparent:true},defaults:{variant:'int8',steps:25,guidance:1,width:1024,height:1024},limits:{min_dimension:256,max_dimension:4096,dimension_step:32,max_pixels:4194304,min_steps:1,max_steps:100,min_guidance:1,max_guidance:1}}]}}));
  try{
    await page.goto(base+'/remove');await page.waitForFunction(()=>settingsLoaded&&!!window.LocalImageStockStudio);
    await page.waitForFunction(()=>!stockLoading&&document.getElementById('stock-status').textContent.includes('Could not load stock providers'));
    await page.locator('#stock-query').focus();
    await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
    assert.equal(providerRequests,1,'A failed request does not recursively retry on focus');
    failProviders=false;
    await page.evaluate(()=>{LocalImageStockStudio.close();LocalImageStockStudio.open();});
    await page.waitForFunction(()=>!stockLoading&&stockProviders.length);
    assert.equal(providerRequests,2,'Deliberately reopening retries provider discovery');
    const dock=page.locator('#studio-assets'),dialog=page.locator('#stock-dialog');
    assert.equal(await dock.isVisible(),true);
    assert.equal(await dialog.getAttribute('data-docked'),'true');
    assert.equal(await page.locator('#stock-expand').evaluate(e=>e.parentElement.classList.contains('studio-assets-header')),true,'Dock commands share the Assets header');
    assert.equal(await dialog.locator(':scope > .dialog-header').isVisible(),false,'No duplicated stock command row');
    assert.equal(await page.locator('#stock-provider-caption').textContent(),'Openverse');
    assert.equal(await dialog.evaluate(e=>e.matches(':modal')),false,'Dock never makes the canvas inert');
    assert.equal(await page.evaluate(()=>modalOpen()),false,'Dock does not block editor commands');
    await page.locator('#stock-query').fill('mountain');await page.locator('#stock-search').click();
    await page.waitForFunction(()=>stockResults.length===12&&!stockLoading);
    assert.equal(await page.locator('#stock-import-background').isEnabled(),false,'No document means no background import');
    await page.waitForFunction(()=>document.querySelector('.stock-preview-failed'));
    assert.equal(await page.locator('.stock-preview-failed .stock-preview-unavailable').textContent(),'Preview unavailable');
    await page.locator('.stock-preview-failed').click();await page.locator('#stock-info').click();
    await page.waitForFunction(()=>!document.querySelector('.stock-detail>.stock-preview-unavailable').hidden);
    assert.equal(await page.locator('#stock-source').isVisible(),true,'Unavailable thumbnail retains the original source and license');
    await page.keyboard.press('Escape');
    await page.locator('#file').setInputFiles(path.join(__dirname,'../docs/images/examples/z-image-realism.png'));
    await page.waitForFunction(()=>!!session&&!busy);
    assert.equal(await page.locator('#stock-import-background').isEnabled(),true,'Opening a document refreshes the persistent dock');
    await page.evaluate(()=>setWorkspace('cutout'));
    assert.equal(await page.locator('#stock-import-background').evaluate(e=>e.classList.contains('primary')),true,'Cutout selects the background import action');
    await page.evaluate(()=>setBusy(true));
    for(const id of ['stock-import-image','stock-import-background','stock-import-reference'])assert.equal(await page.locator('#'+id).isEnabled(),false,id+' is disabled while an editor job runs');
    await page.evaluate(async()=>{await importStock('image');await importStock('background');await importStock('reference');});
    assert.equal(importRequests,0,'Even stale/programmatic clicks cannot submit an import during another job');
    await page.evaluate(()=>setBusy(false));assert.equal(await page.locator('#stock-import-background').isEnabled(),true);
    await page.evaluate(()=>setWorkspace('retouch'));
    assert.equal(await page.locator('#stock-import-image').evaluate(e=>e.classList.contains('primary')),true,'Retouch restores image import as the primary action');
    await page.evaluate(()=>{void closeCurrentImage();});
    if(await page.locator('#close-dialog').isVisible())await page.locator('#close-discard').click();
    await page.waitForFunction(()=>!session&&!busy);
    assert.equal(await page.locator('#stock-import-background').isEnabled(),false,'Closing the document clears background import eligibility');
    await page.evaluate(()=>setWorkspace('generate'));
    await page.waitForFunction(()=>generationModels.length&&!generationLoading);
    assert.equal(await page.locator('#stock-import-reference').isEnabled(),true,'Generation context immediately permits a supported reference');
    assert.equal(await page.locator('#stock-import-reference').evaluate(e=>e.classList.contains('primary')),true);
    await page.evaluate(()=>{generationReferences.push({id:'capacity-fixture',name:'Capacity fixture',thumbnail:'/fixture-stock-preview.png'});updateGenerationControls();});
    assert.equal(await page.locator('#stock-import-reference').isEnabled(),false,'Changing reference capacity refreshes the dock without a new search');
    await page.evaluate(()=>{generationReferences=[];updateGenerationControls();});
    assert.equal(await page.locator('#stock-import-reference').isEnabled(),true);
    await page.evaluate(()=>{setWorkspace('retouch');LocalImageStockStudio.open();});
    await page.locator('.stock-result').first().focus();await page.keyboard.press('ArrowRight');
    assert.equal(await page.evaluate(()=>stockSelectedId),'photo-1');
    assert.equal(await page.locator('#stock-selected-name img').count(),0,'Provider text stays escaped');
    assert.equal(await page.locator('#stock-detail-panel').isVisible(),false);
    await page.locator('#stock-info').click();assert.equal(await page.locator('#stock-license').isVisible(),true);
    await page.keyboard.press('Escape');assert.equal(await page.locator('#stock-detail-panel').isVisible(),false);
    assert.equal(await page.evaluate(()=>document.activeElement.id),'stock-info');
    await page.screenshot({path:path.join(output,'fixture-docked.png')});
    const before=await page.evaluate(()=>({id:stockSelectedId,query:document.getElementById('stock-query').value,count:stockResults.length}));
    await page.locator('#stock-expand').click();assert.equal(await dialog.getAttribute('data-docked'),'false');
    assert.equal(await dialog.locator(':scope > .dialog-header').isVisible(),true,'Expanded browsing restores its own header');
    assert.equal(await dialog.evaluate(e=>e.parentElement===document.body),true);
    assert.equal(await page.locator('#stock-detail-panel').isVisible(),true);
    await page.setViewportSize({width:1024,height:768});
    const bounds=await dialog.boundingBox();assert.ok(bounds.x>=0&&bounds.x+bounds.width<=1024&&bounds.y+bounds.height<=768);
    await page.screenshot({path:path.join(output,'fixture-expanded.png')});
    await page.keyboard.press('Escape');
    assert.equal(await dialog.getAttribute('data-docked'),'true');
    assert.deepEqual(await page.evaluate(()=>({id:stockSelectedId,query:document.getElementById('stock-query').value,count:stockResults.length})),before);
    assert.equal(await dialog.evaluate(e=>e.parentElement.id),'studio-assets');
    await page.locator('#stock-close').click();assert.equal(await dock.isVisible(),false);
    await page.evaluate(()=>LocalImageStockStudio.open());assert.equal(await dock.isVisible(),true);
    assert.deepEqual(errors,[]);
    console.log('PASS: persistent nonmodal stock dock; busy-state import guards; real document open/close refresh; workspace action updates; provider failure/reopen retry without a focus loop; unavailable thumbnails retain source/license; selection, escaped metadata, info/Escape/focus, expanded resize and retained state. Fixture stock responses; real local document import; no GPU work.');
  }catch(error){await page.screenshot({path:path.join(output,'failure.png')});throw error;}
  finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
