// Real bundled adapter examples, offline browsing, focus restoration and UI scale.
// Only the GPU model inventory and online search are mocked. No models are run.
const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const base=process.env.LOCAL_REMOVE_TEST_URL||'http://127.0.0.1:51253';
const output=path.resolve(process.argv[2]||'qa-artifacts/focus-fixes/lora-gallery');fs.mkdirSync(output,{recursive:true});
const families=['qwen','z-image-turbo','flux2-klein-4b','flux2-klein-9b'];
const models=families.map(id=>({id,label:{qwen:'Qwen Image 2.1','z-image-turbo':'Z-Image Turbo','flux2-klein-4b':'FLUX.2 Klein 4B','flux2-klein-9b':'FLUX.2 Klein 9B'}[id],available:true,variants:[{id:id==='qwen'?'int8':id==='flux2-klein-9b'?'fp8':'bf16',label:'Test inventory',available:true}],capabilities:{text_to_image:true,image_reference:id!=='z-image-turbo',image_to_image:true,max_references:id==='qwen'?10:id==='z-image-turbo'?1:4,transparent:id==='qwen',lora:true},defaults:{variant:id==='qwen'?'int8':id==='flux2-klein-9b'?'fp8':'bf16',width:1024,height:1024,steps:id==='qwen'?25:id==='z-image-turbo'?8:4,guidance:1},limits:{min_dimension:256,max_dimension:4096,dimension_step:32,max_pixels:4194304,min_steps:1,max_steps:100,min_guidance:1,max_guidance:1}}));
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'}),page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[],modelQueries=[],results=[];let delay=0;
 page.on('pageerror',error=>errors.push(error.message));await page.addInitScript(()=>{localStorage.setItem('local-image.hardware-guide.v1','1');localStorage.setItem('local-image.first-ai-setup.v1','1');});
 await page.route('**/api/local-remove/generation/models**',async route=>{modelQueries.push(new URL(route.request().url()).searchParams.get('refresh')==='true');if(delay)await new Promise(resolve=>setTimeout(resolve,delay));return route.fulfill({json:{default_model:'qwen',models,connected:true}});});
 await page.route('**/api/local-remove/loras/search**',route=>route.fulfill({status:503,json:{detail:'Network unavailable for this offline test'}}));
 try{
  await page.goto(base+'/remove');await page.waitForFunction(()=>settingsLoaded);await page.locator('#workspace-generate').click();await page.waitForFunction(()=>generationModels.length===4&&!generationLoading);
  const queryStart=modelQueries.length;delay=60;await page.evaluate(async()=>{await Promise.all([loadGenerationModels(),loadGenerationModels(true)]);});delay=0;assert.deepEqual(modelQueries.slice(queryStart),[false,true],'A forced refresh queued during loading is executed after the current request');
  await page.locator('#model-browser').click();await page.waitForFunction(()=>document.querySelectorAll('#model-browser-list button').length===4);await page.locator('#model-browser-refresh').click();await page.waitForFunction(()=>!modelBrowserRequest&&!generationLoading);assert.equal(modelQueries.at(-1),true);await page.locator('#model-browser-close').click();
  await page.locator('#gen-lora-options > summary').click();
  for(const model of families){
   await page.locator('#gen-model').selectOption(model);await page.locator('#lora-library').click();await page.locator('#lora-browse-tab').click();await page.waitForFunction(()=>!loraLibraryBusy);
   const count=await page.locator('#lora-search-results .lora-example-tile').count();assert.ok(count>=2&&count<=3,model+' has 2–3 curated examples');assert.match(await page.locator('#lora-library-status').textContent(),/Recommended examples and installed adapters remain available/);
   await page.waitForFunction(()=>[...document.querySelectorAll('#lora-search-results .lora-example-preview img')].every(image=>image.naturalWidth>0));assert.equal(await page.locator('#lora-search-results .lora-example-preview img').count(),count,'Offline recommendations use actual bundled images');
   for(const [density,width,height]of [['compact',1440,900],['comfortable',1440,900],['large',1440,900],['large',800,600]]){
    await page.evaluate(value=>applyInterfaceDensity(value),density);await page.setViewportSize({width,height});await page.locator('#lora-dialog').evaluate(dialog=>dialog.scrollTop=0);assert.equal(await page.locator('#lora-dialog').evaluate(dialog=>dialog.scrollWidth>dialog.clientWidth),false,'Gallery does not overflow horizontally');const close=await page.locator('#lora-close').boundingBox();assert.ok(close.x>=0&&close.x+close.width<=width&&close.y>=0&&close.y+close.height<=height,'Sticky close remains accessible');
    await page.screenshot({path:path.join(output,'gallery-'+model+'-'+density+'-'+width+'.png'),animations:'disabled'});
   }
   const icon=page.locator('#lora-search-results .lora-info-button').first(),label=await icon.getAttribute('aria-label');await icon.focus();await icon.press('Enter');assert.equal(await page.locator('#lora-info-panel').isVisible(),true);assert.match(await page.locator('#lora-info-panel').textContent(),/Local test example/);assert.match(await page.locator('#lora-info-panel').textContent(),/Recommended for this exact model/);await page.screenshot({path:path.join(output,'info-'+model+'-large-800.png'),animations:'disabled'});await page.getByRole('button',{name:'Close adapter information',exact:true}).click();assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('aria-label')),label,'Closing information restores the originating i-button focus');
   results.push({model,examples:count,densities:['compact','comfortable','large'],smallViewport:'800×600',offline:true,focusRestored:true});await page.locator('#lora-close').click();await page.evaluate(()=>applyInterfaceDensity('compact'));await page.setViewportSize({width:1440,height:900});
  }
  await page.evaluate(()=>applyInterfaceDensity('large'));await page.setViewportSize({width:800,height:600});await page.locator('#draft-refine-open').click();await page.waitForFunction(()=>refineInitialized);for(const id of ['refine-draft-model','refine-draft-prompt','refine-draft-run','refine-final-model','refine-final-prompt','refine-final-width','refine-final-run']){if(id==='refine-draft-prompt')await page.locator('#generation-stage-draft-tab').click();if(id==='refine-final-prompt')await page.locator('#generation-stage-final-tab').click();await page.locator('#'+id).scrollIntoViewIfNeeded();const bounds=await page.locator('#'+id).boundingBox();assert.ok(bounds.x>=0&&bounds.x+bounds.width<=800&&bounds.y>=0&&bounds.y+bounds.height<=600,id+' is reachable at 200% text');}assert.equal(await page.locator('#refine-dialog').evaluate(dialog=>dialog.scrollWidth>dialog.clientWidth),false);await page.locator('#refine-dialog').evaluate(dialog=>dialog.scrollTop=0);await page.screenshot({path:path.join(output,'refine-large-800.png'),animations:'disabled'});await page.locator('.generation-return-create').click();
  assert.deepEqual(errors,[]);fs.writeFileSync(path.join(output,'results.json'),JSON.stringify({status:'passed',modelQueries,results,refineLargeControls:'reachable at 800×600',scope:'Actual bundled exact-adapter example PNGs; model inventory and external search mocked. No GPU work or model downloads.'},null,2));console.log('PASS: 10 real bundled LoRA previews, four families, offline curated gallery, i-button keyboard/focus restoration, three UI scales and 800px Large layout, explicit and queued model refresh, Draft & Refine controls reachable at 200% text.');
 }catch(error){await page.screenshot({path:path.join(output,'failure.png')});throw error;}finally{await page.unrouteAll({behavior:'ignoreErrors'});await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
