// Real browser, local uploads, alpha masks, batch snapshots and ZIP exports.
// No GPU service, installed user data, model downloads or external folders.
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const output=path.resolve(process.argv[2]||'qa-artifacts/focus-group-fixes/batch-ui');fs.mkdirSync(output,{recursive:true});
function storedZipEntries(file){const bytes=fs.readFileSync(file),end=bytes.lastIndexOf(Buffer.from([0x50,0x4b,0x05,0x06]));assert.ok(end>=0);let offset=bytes.readUInt32LE(end+16);const count=bytes.readUInt16LE(end+10),entries={};for(let index=0;index<count;index++){assert.equal(bytes.readUInt32LE(offset),0x02014b50);const size=bytes.readUInt32LE(offset+24),nameSize=bytes.readUInt16LE(offset+28),extra=bytes.readUInt16LE(offset+30),comment=bytes.readUInt16LE(offset+32),local=bytes.readUInt32LE(offset+42),name=bytes.subarray(offset+46,offset+46+nameSize).toString('utf8');assert.equal(bytes.readUInt16LE(local+8),0,'Batch ZIP stores image bytes unchanged');const data=local+30+bytes.readUInt16LE(local+26)+bytes.readUInt16LE(local+28);entries[name]=bytes.subarray(data,data+size);offset+=46+nameSize+extra+comment;}return entries;}
async function main(){
  const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'msedge'});
  const page=await browser.newPage({viewport:{width:1440,height:960}}),errors=[];
  await page.addInitScript(()=>{localStorage.setItem('local-image.hardware-guide.v1','1');localStorage.setItem('local-image.first-ai-setup.v1','1');});page.on('pageerror',error=>errors.push(error.message));
  const start=()=>page.evaluate(()=>window.LocalImageBatch.open());
  const trace=[];async function record(label){trace.push({label,...await page.evaluate(()=>({session:session?.name,collection:collection?.entries.map(entry=>({id:entry.id,name:entry.name})),selected:Array.from(document.querySelectorAll('#batch-rows input:checked')).map(input=>input.dataset.batchEntry),rows:document.querySelector('#batch-rows').textContent,history:document.querySelector('#batch-history-select').value}))});fs.writeFileSync(path.join(output,'trace.json'),JSON.stringify(trace,null,2));}
  async function done(){await page.waitForFunction(()=>!document.querySelector('#batch-export')?.disabled&&document.querySelector('#batch-cancel')?.hidden);}
  try{
    await page.goto(new URL('/remove',process.env.LOCAL_REMOVE_TEST_URL||'http://127.0.0.1:51256').href);await page.waitForFunction(()=>settingsLoaded&&window.LocalImageBatch);
    const fixtures=await page.evaluate(()=>[0,1].map(index=>{const canvas=document.createElement('canvas');canvas.width=index?640:800;canvas.height=index?480:600;const c=canvas.getContext('2d');c.fillStyle='#cabaa4';c.fillRect(0,0,canvas.width,canvas.height);c.fillStyle=index?'#cb6941':'#397c8e';c.fillRect(canvas.width*.28,canvas.height*.2,canvas.width*.4,canvas.height*.6);return{name:index?'Orange bottle.png':'Blue bottle.png',base64:canvas.toDataURL('image/png').split(',')[1]};}));
    await page.locator('#file').setInputFiles(fixtures.map(value=>({name:value.name,mimeType:'image/png',buffer:Buffer.from(value.base64,'base64')})));await page.waitForFunction(()=>session&&!busy&&collection?.entries.length===2);
    await page.locator('#file-menu-trigger').click();await page.locator('#batch-open').click();await page.waitForFunction(()=>document.querySelector('#batch-dialog').open&&document.querySelector('#batch-rows tr'));
    assert.equal(await page.locator('#batch-rows tr').count(),2);assert.equal(await page.locator('#batch-save-treatment').isEnabled(),false,'Treatment needs a subject cutout');
    await page.locator('#batch-format').selectOption('png');await page.locator('#batch-create').click();await done();
    assert.equal(await page.locator('#batch-format').inputValue(),'png');assert.equal(await page.locator('#batch-format').isEnabled(),false,'Reviewed format is immutable');assert.equal(await page.locator('#batch-treatment').isEnabled(),false,'Reviewed treatment is immutable');assert.match(await page.locator('#batch-queue-settings').textContent(),/PNG/);assert.equal(await page.locator('#batch-create').isVisible(),false);assert.equal(await page.locator('#batch-new-queue').isVisible(),true);
    assert.match(await page.locator('#batch-status').textContent(),/Review/);assert.equal(await page.locator('#batch-rows img').count(),2);assert.equal(await page.evaluate(()=>collection.entries.every(item=>item.session_id)),true,'Unopened browser collection items imported sequentially');
    await page.locator('#batch-rows input').first().uncheck();let requested=null;page.on('request',request=>{if(request.url().endsWith('/export'))requested=request.postDataJSON();});
    await page.locator('#batch-export').click();await page.waitForFunction(()=>!document.querySelector('#batch-download').hidden);assert.equal(requested.item_ids.length,1,'Only checked reviewed image is exported');
    const downloadPromise=page.waitForEvent('download');await page.locator('#batch-download').click();const download=await downloadPromise;await download.saveAs(path.join(output,'selected-export.zip'));assert.ok(fs.statSync(path.join(output,'selected-export.zip')).size>100);
    const exported=storedZipEntries(path.join(output,'selected-export.zip'));assert.deepEqual(Object.keys(exported).filter(name=>name!=='export-report.json'),['Orange bottle-local-image.png'],'ZIP suffix matches the visible fixed PNG choice');
    await page.locator('.batch-history > summary').click();await page.locator('#batch-clear-queue').click();await page.locator('#batch-confirm-yes').click();await page.waitForFunction(()=>document.querySelector('#batch-status').textContent.includes('Queue cache cleared'));assert.equal(await page.evaluate(()=>!!session&&collection.entries.every(entry=>entry.session_id)),true);
    await page.locator('#batch-close').click();
    // Pending mask on an inactive image, unfinished pen path on the active one.
    const pending=await page.evaluate(async()=>{mc.clearRect(0,0,mask.width,mask.height);mc.fillStyle='white';mc.fillRect(30,35,120,140);hasSelection=true;paintMask();rememberCurrentView();const first={id:session.id,mask:mask.toDataURL()};await openCollectionEntry(1);tool='pen';points=[{x:40,y:40},{x:90,y:55}];hasSelection=false;penDraft();rememberCurrentView();return{first,second:{id:session.id,points:points.map(point=>({...point}))}};});
    await start();await record('pending start');assert.equal(await page.locator('#batch-pending-warning').isVisible(),true);assert.match(await page.locator('#batch-pending-description').textContent(),/2 selected photos/);assert.equal(await page.locator('#batch-create').isEnabled(),false,'No batch can silently omit pending selections');
    await page.locator('#batch-rows input').first().uncheck();assert.match(await page.locator('#batch-pending-description').textContent(),/1 selected photo/);await page.locator('#batch-rows input').nth(1).uncheck();assert.equal(await page.locator('#batch-pending-warning').isVisible(),false,'Deselected pending images do not block another queue');await page.locator('#batch-rows input').first().check();await page.locator('#batch-applied-only').check();await record('pending selected');await page.locator('#batch-create').click();await done();await record('pending prepared');
    assert.equal(await page.locator('#batch-applied-only').isChecked(),true,'Preparation and export retain the explicit applied-only choice');await page.locator('#batch-export').click();await page.waitForFunction(()=>!document.querySelector('#batch-download').hidden);const pendingDownloadPromise=page.waitForEvent('download');await page.locator('#batch-download').click();const pendingDownload=await pendingDownloadPromise;await pendingDownload.saveAs(path.join(output,'applied-only.zip'));const applied=storedZipEntries(path.join(output,'applied-only.zip'));const appliedPng=Object.keys(applied).find(name=>name.endsWith('.png'));assert.ok(appliedPng);assert.equal(await page.evaluate(async image=>{const img=new Image();img.src='data:image/png;base64,'+image;await img.decode();const c=document.createElement('canvas');c.width=img.width;c.height=img.height;const context=c.getContext('2d');context.drawImage(img,0,0);return context.getImageData(0,0,1,1).data[3];},applied[appliedPng].toString('base64')),255,'Pending mask is excluded only by explicit choice');
    const pendingState=await page.evaluate(ids=>({current:session.id,first:viewStates.get(ids.first.id).mask,second:points.map(point=>({...point}))}),pending);assert.equal(pendingState.first,pending.first.mask);assert.deepEqual(pendingState.second,pending.second.points,'Batch does not finish or discard another photo’s pen path');await record('pending exported');
    await page.locator('#batch-new-queue').click();await page.locator('#batch-format').selectOption('tif');assert.equal(await page.locator('#batch-create').isEnabled(),false,'New queue requires a fresh pending-selection decision');await page.locator('#batch-applied-only').check();await page.locator('#batch-create').click();await done();assert.equal(await page.locator('#batch-format').inputValue(),'tif');await page.locator('#batch-export').click();await page.waitForFunction(()=>!document.querySelector('#batch-download').hidden);const tifPromise=page.waitForEvent('download');await page.locator('#batch-download').click();const tifDownload=await tifPromise;await tifDownload.saveAs(path.join(output,'reviewed-tiff.zip'));assert.ok(Object.keys(storedZipEntries(path.join(output,'reviewed-tiff.zip'))).some(name=>name.endsWith('.tif')),'Fresh TIFF previews export as the visible TIFF format');
    const tifQueueId=(await page.locator('#batch-download').getAttribute('href')).split('/jobs/')[1].split('/')[0];await page.locator('#batch-new-queue').click();await page.locator('#batch-format').selectOption('jpg');if(!await page.locator('#batch-load-queue').isVisible())await page.locator('.batch-history > summary').click();await page.locator('#batch-history-select').selectOption(tifQueueId);await page.locator('#batch-load-queue').click();await page.waitForFunction(()=>document.querySelector('#batch-format').disabled&&document.querySelector('#batch-format').value==='tif');assert.equal(await page.locator('#batch-format').inputValue(),'tif','History loading replaces unrelated controls with actual queue format');assert.equal(await page.locator('#batch-format').isEnabled(),false);
    await record('history loaded');await page.locator('#batch-return-apply').click();await page.waitForFunction(id=>session?.id===id&&!busy,pending.first.id);assert.equal(await page.evaluate(()=>hasSelection),true);assert.equal(await page.evaluate(()=>mask.toDataURL()),pending.first.mask,'Return to apply preserves every pending mask pixel');assert.deepEqual(await page.evaluate(id=>viewStates.get(id).points,pending.second.id),pending.second.points);
    await page.locator('#select-menu-trigger').click();await page.locator('#clear').click();await page.evaluate(()=>openCollectionEntry(1));await page.locator('#viewport').focus();await page.keyboard.press('Escape');await page.evaluate(()=>openCollectionEntry(0));
    // Give each image its own real manual cutout, with differing dimensions.
    await page.evaluate(async()=>{const c=collection;let current=null;for(const entry of c.entries){const data=await(await api('/api/local-remove/session/'+entry.session_id)).json();const canvas=document.createElement('canvas');canvas.width=data.width;canvas.height=data.height;const context=canvas.getContext('2d');context.fillStyle='white';context.fillRect(data.width*.25,data.height*.17,data.width*.46,data.height*.68);const next=await json('/api/local-remove/session/'+data.id+'/cutout/refine',{revision:data.revision,operation:'replace',mask:canvas.toDataURL('image/png').split(',')[1]});if(next.id===session.id)current=next;}await openSession(current,{collection:c,index:0});});
    const treatmentPending=await page.evaluate(()=>{mc.clearRect(0,0,mask.width,mask.height);mc.fillStyle='white';mc.fillRect(1,1,20,20);hasSelection=true;paintMask();return{mask:mask.toDataURL(),revision:session.revision};});await start();assert.equal(await page.locator('#batch-save-treatment').isEnabled(),false,'Saving a treatment also discloses pending edits');await page.locator('#batch-applied-only').check();await page.locator('#batch-save-treatment').click();await page.locator('#batch-treatment-name').fill('Warm studio '+Date.now());await page.locator('#batch-name-save').click();await page.waitForFunction(()=>document.querySelector('#batch-treatment').value&&document.querySelector('#batch-name-row').hidden);assert.equal(await page.evaluate(()=>mask.toDataURL()),treatmentPending.mask);assert.equal(await page.evaluate(()=>session.revision),treatmentPending.revision,'Treatment stores applied state without applying the pending area');await page.locator('#batch-return-apply').click();await page.locator('#select-menu-trigger').click();await page.locator('#clear').click();await start();
    await page.locator('#batch-create').click();await done();assert.equal(await page.locator('#batch-rows img').count(),2);assert.equal(await page.locator('#batch-rows .error').count(),0);
    await page.locator('.batch-inspect-button').first().click();await page.locator('#batch-inspect-image').evaluate(image=>image.decode());assert.equal(await page.locator('#batch-inspect-image').evaluate(image=>image.naturalWidth),800);await page.locator('#batch-inspect-zoom').selectOption('200');assert.equal(await page.locator('#batch-inspect-image').evaluate(image=>parseFloat(image.style.width)),1600);await page.locator('#batch-inspect-original').click();assert.equal(await page.locator('#batch-inspect-original').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#batch-inspect-original').textContent(),'Treatment');assert.match(await page.locator('#batch-inspect-image').getAttribute('alt'),/original/);await page.locator('#batch-inspect-back').click();await page.locator('.batch-inspect-button').nth(1).click();assert.equal(await page.locator('#batch-inspect-original').textContent(),'Original','Another photo resets the next action');assert.equal(await page.locator('#batch-inspect-original').getAttribute('aria-pressed'),'false');assert.match(await page.locator('#batch-inspect-image').getAttribute('alt'),/treatment.*Orange bottle/);await page.locator('#batch-inspect-original').click();assert.match(await page.locator('#batch-inspect-image').getAttribute('alt'),/original.*Orange bottle/);await page.locator('#batch-inspect-original').click();assert.match(await page.locator('#batch-inspect-image').getAttribute('alt'),/treatment/);await page.locator('#batch-inspect-back').click();
    for(const [width,height,density] of [[1440,960,'compact'],[1280,800,'comfortable'],[1024,768,'large'],[800,600,'comfortable']]){
      await page.setViewportSize({width,height});await page.evaluate(value=>applyInterfaceDensity(value),density);await page.screenshot({path:path.join(output,`${width}-${density}.png`)});
      const bounds=await page.locator('#batch-dialog').boundingBox();assert.ok(bounds.x>=0&&bounds.x+bounds.width<=width+1,'Dialog fits viewport');assert.equal(await page.locator('#batch-dialog').evaluate(element=>element.scrollWidth<=element.clientWidth+1),true,'No horizontal dialog overflow');
    }
    await page.locator('#batch-history-select').selectOption(tifQueueId);await page.locator('#batch-load-queue').click();await page.waitForFunction(()=>document.querySelector('#batch-format').value==='tif'&&document.querySelectorAll('#batch-rows tr').length===1);await page.locator('.batch-inspect-button').first().click();assert.equal(await page.locator('#batch-inspect-original').textContent(),'Original','Loading a previous queue resets comparison state');assert.match(await page.locator('#batch-inspect-image').getAttribute('alt'),/treatment/);
    assert.deepEqual(errors,[]);fs.writeFileSync(path.join(output,'results.json'),JSON.stringify({passed:true,checks:['two browser uploads including lazily opened image','flat table and checked review exports','real ZIP download','immutable reviewed treatment and PNG format match ZIP contents','explicit new TIFF queue matches TIFF ZIP contents','history loading synchronizes reviewed queue settings','current/inactive pending selections and unfinished path require explicit applied-only choice','deselecting pending images removes the warning','mask pixels and inactive path preserved; return to apply restores state','queue cache deletion preserves editor documents','saving a treatment requires pending acknowledgment and preserves exact selection pixels','saved treatment applies independent masks','full-size original/treatment review at200percent','comparison caption and alt track actual mode across two images and previous queue','four viewports and three text densities','zero browser errors'],errors},null,2));
    fs.rmSync(path.join(output,'failure-state.json'),{force:true});
    process.stdout.write(JSON.stringify({passed:true,output,errors}));
  }catch(error){fs.writeFileSync(path.join(output,'failure-state.json'),JSON.stringify(await page.evaluate(()=>({session_id:session?.id,busy,collection:collection?.entries.map(entry=>({id:entry.id,session_id:entry.session_id,name:entry.name,pending:pendingSelection(entry.session_id)})),message:document.querySelector('#message').textContent,batchStatus:document.querySelector('#batch-status').textContent,format:document.querySelector('#batch-format').value,history:document.querySelector('#batch-history-select').value,rows:document.querySelector('#batch-rows').textContent,dialogOpen:document.querySelector('#batch-dialog').open,warning:document.querySelector('#batch-pending-description').textContent})),null,2));throw error;}finally{await browser.close();}
}
main().catch(error=>{process.stderr.write(error.stack+'\n');process.exitCode=1;});
