// Frontend contract test. Stock network responses are deterministic fixtures;
// local image import, canvas display and cutout composition use the real backend.
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const base=process.env.LOCAL_REMOVE_TEST_URL||'http://127.0.0.1:51249',output=path.resolve(process.argv[2]||'qa-artifacts/studio-stock');fs.mkdirSync(output,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'}),page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',error=>errors.push(error.message));await page.addInitScript(()=>{localStorage.setItem('local-image.hardware-guide.v1','1');localStorage.setItem('local-image.first-ai-setup.v1','1');});
 try{
  await page.goto(base+'/remove');await page.waitForFunction(()=>settingsLoaded);
  const pixels=await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=640;canvas.height=480;const c=canvas.getContext('2d');c.fillStyle='#566773';c.fillRect(0,0,640,480);c.fillStyle='#a3b4b1';c.fillRect(0,290,640,190);c.fillStyle='#bd895f';c.fillRect(175,165,170,190);c.fillStyle='#cbb397';c.fillRect(200,355,14,68);c.fillRect(303,355,14,68);return canvas.toDataURL('image/png').split(',')[1];}),buffer=Buffer.from(pixels,'base64');
  const attribution={provider:'openverse',asset_id:'fixture-source',title:'Quiet studio',creator:'Fixture photographer',license:'CC BY 4.0',license_url:'https://creativecommons.org/licenses/by/4.0/',source_url:'https://example.com/photo',attribution:'Quiet studio by Fixture photographer · CC BY 4.0'};
  let searches=[],imports=[];
  await page.route('**/api/local-remove/stock/**',async route=>{const url=new URL(route.request().url());
   if(url.pathname.endsWith('/providers'))return route.fulfill({json:{providers:[{id:'openverse',label:'Openverse',available:true}],default_provider:'openverse'}});
   if(url.pathname.includes('/thumbnail/'))return route.fulfill({contentType:'image/png',body:buffer});
   if(url.pathname.endsWith('/search')){const query=url.searchParams.get('query'),number=Number(url.searchParams.get('page'));searches.push({query,page:number});if(query==='offline')return route.fulfill({status:503,json:{detail:'Provider is temporarily unavailable'}});return route.fulfill({json:{results:Array.from({length:9},(_,i)=>({...attribution,id:'photo-'+number+'-'+i,title:i===1?'<img src=x onerror=alert(1)>':i?'Studio view '+(i+1):'Quiet studio',width:640,height:480,thumbnail_url:'/api/local-remove/stock/thumbnail/'+i})),next_page:number===0?1:null,checked_at:new Date().toISOString()}});}
   if(url.pathname.endsWith('/import')){const payload=route.request().postDataJSON();imports.push(payload);const session=await page.evaluate(async({target,id,revision,pixels,attribution})=>{const file=new File([Uint8Array.from(atob(pixels),c=>c.charCodeAt(0))],'Stock studio.png',{type:'image/png'}),form=new FormData();form.append('file',file);if(target==='background'){const current=await(await api('/api/local-remove/session/'+id)).json();if(!current.cutout){const cutout=await json('/api/local-remove/session/'+id+'/cutout/refine',{revision,mask:pixels,operation:'restore'});revision=cutout.revision;}form.append('revision',String(revision));}const endpoint=target==='background'?'/api/local-remove/session/'+id+'/cutout/background':'/api/local-remove/import';const value=await(await api(endpoint,{method:'POST',body:form})).json();if(target==='background')value.cutout.background.attribution=attribution;else{value.source_attribution=attribution;value.dirty=true;}return value;},{target:payload.target,id:payload.session_id,revision:payload.revision,pixels,attribution});return route.fulfill({json:{session,target:payload.target,attribution}});}
   return route.abort();
  });
  await page.locator('#file-menu-trigger').click();await page.locator('#stock-open').click();await page.waitForFunction(()=>!stockLoading);
  assert.equal(await page.locator('#stock-provider').isVisible(),false,'A single provider does not create selector clutter');assert.match(await page.locator('#stock-title').textContent(),/Openverse/);assert.equal(await page.locator('#stock-search').isEnabled(),false);
  await page.locator('#stock-query').fill('studio');await page.locator('#stock-search').click();await page.waitForFunction(()=>stockResults.length===9&&!stockLoading);assert.equal(await page.locator('#stock-import-background').isEnabled(),false,'Background placement needs a current document');
  assert.match(await page.locator('#stock-attribution').textContent(),/Fixture photographer/);assert.match(await page.locator('#stock-license').getAttribute('href'),/creativecommons/);
  await page.locator('.stock-result').first().focus();await page.keyboard.press('ArrowRight');assert.equal(await page.locator('#stock-image-title').textContent(),'<img src=x onerror=alert(1)>');assert.equal(await page.locator('#stock-image-title img').count(),0,'Provider strings are text, never markup');
  await page.locator('#stock-next').click();await page.waitForFunction(()=>stockPage===1&&!stockLoading);assert.equal(await page.locator('#stock-next').isEnabled(),false);await page.locator('#stock-previous').click();await page.waitForFunction(()=>stockPage===0&&!stockLoading);
  await page.locator('#stock-query').fill('offline');await page.locator('#stock-search').click();await page.waitForFunction(()=>!stockLoading);assert.match(await page.locator('#stock-status').textContent(),/Search failed.*temporarily unavailable/);await page.locator('#stock-query').fill('studio');await page.locator('#stock-search').click();await page.waitForFunction(()=>!stockLoading);
  for(const [width,height]of[[1440,900],[1024,768],[800,600]]){await page.setViewportSize({width,height});const bounds=await page.locator('#stock-import-image').boundingBox();assert.ok(bounds.y+bounds.height<=height&&bounds.x+bounds.width<=width);assert.equal(await page.locator('body').evaluate(e=>e.scrollWidth>innerWidth),false);await page.screenshot({path:path.join(output,'fixture-stock-'+width+'.png')});}
  await page.locator('#stock-import-image').click();await page.waitForFunction(()=>session?.source_attribution&&!busy&&!stockImporting);assert.equal(await page.locator('#stock-dialog').isVisible(),false);assert.equal(await page.evaluate(()=>hasWorkingLayers(session)),true,'Unsaved stock image receives project/close protection');assert.equal(imports[0].target,'image');
  await page.locator('#file-menu-trigger').click();await page.locator('#image-credits').click();assert.match(await page.locator('#credits-list').textContent(),/Fixture photographer/);
  await page.evaluate(()=>{Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{window.copiedCredits=text;}}});});await page.locator('#credits-copy').click();assert.match(await page.evaluate(()=>window.copiedCredits),/Fixture photographer/);assert.match(await page.evaluate(()=>window.copiedCredits),/https:\/\/creativecommons.org\/licenses\/by\/4.0\//);assert.match(await page.locator('#credits-status').textContent(),/Credits copied/);
  const sid=await page.evaluate(()=>session.id);await page.evaluate(()=>{const original=HTMLAnchorElement.prototype.click;HTMLAnchorElement.prototype.click=function(){if(this.pathname.endsWith('/download-credits')){window.creditDownload={url:this.href,name:this.download};return;}return original.call(this);};});await page.locator('#credits-download').click();const handoff=await page.evaluate(()=>window.creditDownload);assert.equal(new URL(handoff.url).pathname,'/api/local-remove/session/'+sid+'/download-credits','Desktop exports use the trusted same-origin credits endpoint');assert.match(handoff.name,/-credits\.txt$/);assert.match(await page.locator('#credits-status').textContent(),/sharing alongside/);await page.locator('#credits-close').click();
  await page.locator('#workspace-cutout').click();await page.locator('#studio-background-tab').click();await page.locator('#background-stock').click();await page.waitForFunction(()=>!stockLoading);assert.equal(await page.locator('#stock-import-background').isEnabled(),true);await page.locator('#stock-import-background').click();await page.waitForFunction(()=>session?.cutout?.background?.attribution&&!busy&&!stockImporting);assert.equal(imports[1].target,'background');assert.equal(typeof imports[1].revision,'number');assert.equal(await page.locator('#workspace-cutout').getAttribute('aria-pressed'),'true');
  await page.locator('#workspace-generate').click();await page.waitForFunction(()=>generationModels.length>0&&!generationLoading);await page.locator('#gen-reference-tab').click();await page.locator('#gen-stock').click();await page.waitForFunction(()=>!stockLoading);await page.locator('#stock-import-reference').click();await page.waitForFunction(()=>generationReferences.length===1&&!stockImporting&&!busy);assert.equal(imports[2].target,'image');assert.equal(await page.locator('#workspace-generate').getAttribute('aria-pressed'),'true');
  assert.deepEqual(errors,[]);console.log('PASS: Openverse-only library, search/pagination/retry, escaped provider metadata, license/source credits, image/background/reference import, unsaved document protection, keyboard navigation and 1440/1024/800 layouts.');
 }catch(error){await page.screenshot({path:path.join(output,'failure.png')});throw error;}finally{await page.unrouteAll({behavior:'ignoreErrors'});await browser.close();}
})().catch(error=>{console.error(error);process.exit(1)});
