// Real batch preparation from an editable cutout mask; no provider/model jobs or exports.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {chromium}=require('playwright'),{imageFixture}=require('./helpers/image-fixture.cjs');
const root=path.resolve(__dirname,'..'),base=process.env.LOCAL_REMOVE_TEST_URL,profile=process.env.MIGRATION_REAL_PROFILE;
assert.ok(base&&profile);assert.equal(new URL(base).hostname,'127.0.0.1');assert.ok(path.resolve(profile).startsWith(path.join(root,'qa-artifacts')+path.sep));
const output=path.join(root,'qa-artifacts/migration/batch-inspection-layout'),hash=value=>crypto.createHash('sha256').update(value).digest('hex');
(async()=>{
 const runtime=await(await fetch(base+'/api/local-remove/runtime')).json();assert.equal(path.resolve(runtime.data_root),path.resolve(profile));fs.mkdirSync(output,{recursive:true});
 const sourceFile=path.join(root,'frontend/src/features/batch/batch.css'),sourceHash=hash(fs.readFileSync(sourceFile)),browser=await chromium.launch({channel:'msedge',headless:true}),context=await browser.newContext({viewport:{width:1366,height:768},deviceScaleFactor:1.75}),page=await context.newPage();
 const metrics=[],assets=[],errors=[],blocked=[],requests=[],reads=[];let passed=false,failure=null,queueId=null;
 await context.route('**/*',route=>{const request=route.request(),url=new URL(request.url());let allowed=request.method()==='GET';if(request.method()==='POST'){allowed=/^\/api\/local-remove\/import$/.test(url.pathname)||/^\/api\/local-remove\/session\/[^/]+\/(?:stack|cutout\/refine)$/.test(url.pathname);if(url.pathname==='/api/local-remove/batch/jobs'){const body=request.postDataJSON();allowed=body.prepare_cutouts===true&&!body.treatment_id;}}if(url.origin!==base||!allowed){blocked.push({method:request.method(),path:url.pathname});return route.abort('blockedbyclient');}return route.continue();});
 await context.addInitScript(()=>{for(const key of ['local-image.hardware-guide.v1','local-image.first-ai-setup.v1','local-image.first-task.v1'])localStorage.setItem(key,'1');window.__inspectionCsp=[];document.addEventListener('securitypolicyviolation',event=>window.__inspectionCsp.push(event.violatedDirective));});
 page.on('pageerror',error=>errors.push(error.stack));page.on('request',request=>{const url=new URL(request.url());if(url.pathname.startsWith('/api/'))requests.push({method:request.method(),path:url.pathname});});page.on('response',response=>{const url=new URL(response.url());if(url.pathname.startsWith('/frontend-assets/'))reads.push(response.body().then(body=>assets.push({path:url.pathname,status:response.status(),sha256:hash(body)})));});
 const settle=()=>page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
 try{
  await page.goto(base+'/remove');await page.waitForFunction(()=>document.body.dataset.reactReady==='true');const [chooser]=await Promise.all([page.waitForEvent('filechooser'),page.getByRole('button',{name:'Open image…',exact:true}).click()]);await chooser.setFiles({name:'Batch flow fixture.png',mimeType:'image/png',buffer:imageFixture(640,480)});await page.waitForFunction(()=>!!window.LocalImageEditor.getSnapshot().document&&!window.LocalImageEditor.getSnapshot().busy);
  await page.getByRole('button',{name:'Layer commands',exact:true}).click();await page.getByRole('menuitem',{name:'Add editable mask',exact:true}).click();await page.waitForFunction(()=>window.LocalImageEditor.getSnapshot().document.layer_stack.some(layer=>layer.kind==='cutout')&&!window.LocalImageEditor.getSnapshot().busy);
  await page.getByRole('button',{name:'Settings',exact:true}).click();const settings=page.getByRole('dialog',{name:'Settings',exact:true});await settings.getByRole('combobox',{name:'Interface size',exact:true}).selectOption('large');await settings.getByRole('button',{name:'Done',exact:true}).click();await settings.waitFor({state:'detached'});
  await page.locator('#workspace-cutout').click();await page.waitForFunction(()=>!window.LocalImageEditor.getSnapshot().busy);await page.getByRole('button',{name:'Remove backgrounds',exact:true}).click();await page.waitForFunction(()=>window.LocalImageReactFeatures.batch.getSnapshot().canPrepare);const [created]=await Promise.all([page.waitForResponse(response=>new URL(response.url()).pathname==='/api/local-remove/batch/jobs'&&response.request().method()==='POST'),page.locator('#batch-create').click()]);assert.equal(created.status(),200);const queue=await created.json();assert.equal(queue.prepare_cutouts,true);queueId=queue.id;
  await page.waitForFunction(()=>window.LocalImageReactFeatures.batch.getSnapshot().canExport&&!window.LocalImageReactFeatures.batch.getSnapshot().active.running);await page.getByRole('button',{name:'Inspect Batch flow fixture.png at full size',exact:true}).click();await page.locator('#batch-inspect-image').evaluate(image=>image.decode());
  for(const [width,height]of [[800,560],[1366,768],[2195,1164]])for(const zoom of ['fit','200']){
   await page.setViewportSize({width,height});await page.locator('#batch-inspect-zoom').selectOption(zoom);await settle();
   const geometry=await page.locator('#batch-dialog').evaluate(dialog=>{const rect=selector=>{const element=dialog.querySelector(selector),box=element.getBoundingClientRect();return{top:box.top,bottom:box.bottom,height:box.height,clientHeight:element.clientHeight,scrollHeight:element.scrollHeight}};return{font:parseFloat(getComputedStyle(dialog).fontSize),inspection:rect('.li-batch-inspection'),scroll:rect('#batch-inspect-scroll'),image:rect('#batch-inspect-image'),status:rect('.li-batch-status'),history:rect('.li-batch-history'),content:rect('.li-batch-content')};});
   assert.equal(geometry.font,28);assert.ok(geometry.inspection.bottom>=geometry.scroll.bottom-1,'Inspection owns the full preview viewport height');assert.ok(geometry.status.top>=geometry.inspection.bottom+1,'Status follows inspection rather than overlapping it');assert.ok(geometry.status.top>=Math.min(geometry.image.bottom,geometry.scroll.bottom),'Visible preview does not overlap status');assert.ok(geometry.history.top>=geometry.status.bottom+1,'History follows status in normal flow');
   const status=page.locator('.li-batch-status');await status.scrollIntoViewIfNeeded();await settle();const statusHit=await status.evaluate(element=>{const box=element.getBoundingClientRect(),hit=document.elementFromPoint(box.left+box.width/2,box.top+Math.min(box.height/2,20));return !!hit?.closest('.li-batch-status');});assert.equal(statusHit,true,'Status text can be reached without an image covering it');
   const history=page.locator('.li-batch-history').getByRole('button',{name:'Previous batches',exact:true});await history.click();assert.equal(await history.getAttribute('aria-expanded'),'true');await page.locator('#batch-load-queue').scrollIntoViewIfNeeded();assert.equal(await page.locator('#batch-load-queue').isVisible(),true);await history.click();assert.equal(await history.getAttribute('aria-expanded'),'false');
   metrics.push({width,height,zoom,...geometry,statusHit});await status.scrollIntoViewIfNeeded();await page.screenshot({path:path.join(output,`inspection-${width}-${height}-${zoom}.png`),animations:'disabled'});
  }
  await Promise.all(reads);assert.equal(hash(fs.readFileSync(sourceFile)),sourceHash);assert.deepEqual(errors,[]);assert.deepEqual(blocked,[]);assert.deepEqual(await page.evaluate(()=>window.__inspectionCsp),[]);passed=true;
 }catch(error){failure=error.stack;await page.screenshot({path:path.join(output,'failure.png'),animations:'disabled'}).catch(()=>{});throw error;}
 finally{await Promise.allSettled(reads);fs.writeFileSync(path.join(output,'results.json'),JSON.stringify({passed,failure,runtime,queueId,sourceHash,metrics,assets,requests,errors,blocked,evidence:'Actual editable-mask backend batch with real full-size preview; Large28px at three viewport sizes and fit/200% image zoom; no model/native actions'},null,2));await browser.close();}
 console.log(`PASS Batch inspection flow: ${metrics.length} layouts; ${output}`);
})().catch(error=>{console.error(error);process.exitCode=1;});
