// Delayed backend responses must never cross a LoRA model or window context.
const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const base=process.env.LOCAL_REMOVE_TEST_URL||'http://127.0.0.1:51253',output=path.resolve(process.argv[2]||'qa-artifacts/focus-fixes/lora-context');fs.mkdirSync(output,{recursive:true});
const names={qwen:'Qwen Image 2.1','flux2-klein-4b':'FLUX.2 Klein 4B'};
const models=Object.keys(names).map(id=>({id,label:names[id],available:true,variants:[{id:id==='qwen'?'int8':'bf16',label:'Test inventory',available:true}],capabilities:{text_to_image:true,image_reference:true,max_references:4,lora:true,transparent:id==='qwen'},defaults:{variant:id==='qwen'?'int8':'bf16',width:1024,height:1024,steps:4,guidance:1},limits:{min_dimension:256,max_dimension:4096,dimension_step:32,max_pixels:4194304,min_steps:1,max_steps:100,min_guidance:1,max_guidance:1}}));
const entry=model=>({id:'style-'+model,model,title:'Verified style for '+names[model],repo_id:'publisher/'+model+'-style',filename:model+'-style.safetensors',revision:'reviewed-'+model,description:'Watercolor wash for '+names[model],style:'Watercolor',compatibility:'curated',supported:true,preview_available:false,bytes:1234});
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'}),page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];let delayKind=null,pending=null,release=null,waitPending=null,nativeRequests=[];
 page.on('pageerror',error=>errors.push(error.message));await page.addInitScript(()=>{localStorage.setItem('local-image.hardware-guide.v1','1');localStorage.setItem('local-image.first-ai-setup.v1','1');});
 await page.route('**/api/local-remove/generation/models**',route=>route.fulfill({json:{default_model:'qwen',models,connected:true}}));await page.route('**/api/local-remove/generator/download',route=>route.fulfill({json:{running:false,models:[]}}));
 await page.route('**/api/local-remove/loras**',async route=>{
  const url=new URL(route.request().url()),model=url.searchParams.get('model')||'qwen',kind=url.pathname.endsWith('/search')?'search':url.pathname.endsWith('/files')?'files':url.pathname.endsWith('/download')?'poll':'inventory',item=entry(model);
  const body=kind==='inventory'?{installed:[item],curated:[item],job:{running:false}}:kind==='search'?{results:url.searchParams.get('query')?.startsWith('no-such')?[]:[{...item,repo_id:'community/'+model+'-new',title:'Community style for '+names[model],compatibility:'declared'}]}:kind==='files'?{repo_id:item.repo_id,revision:item.revision,compatibility:'curated',files:[{filename:item.filename,bytes:1234,compatibility:'curated',supported:true}]}:{running:false,phase:'idle',message:'No download in this fixture'};
  if(delayKind===kind&&model==='qwen'&&!pending){pending={model,kind};delayKind=null;waitPending?.();await new Promise(resolve=>release=resolve);}
  return route.fulfill({json:body});
 });
 async function arm(kind){delayKind=kind;pending=null;release=null;return new Promise(resolve=>waitPending=resolve);}
 async function open(model){await page.locator('#gen-model').selectOption(model);await page.locator('#lora-library').click();}
 async function settleOld(){release();await page.evaluate(async()=>{await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));});await page.waitForFunction(()=>document.querySelector('#lora-model-label').textContent.includes('Klein 4B'));}
 try{
  await page.goto(base+'/remove');await page.waitForFunction(()=>settingsLoaded);await page.locator('#workspace-generate').click();await page.waitForFunction(()=>!generationLoading&&generationModels.length===2);await page.locator('#gen-lora-options > summary').click();
  const waitingInventory=arm('inventory');await open('qwen');await waitingInventory;assert.equal(await page.locator('#lora-browse-tab').isEnabled(),false);await page.locator('#lora-close').click();await open('flux2-klein-4b');await page.waitForFunction(()=>loraInventory?.installed?.[0]?.model==='flux2-klein-4b');await settleOld();assert.match(await page.locator('#lora-installed-list').textContent(),/Klein 4B/);assert.doesNotMatch(await page.locator('#lora-installed-list').textContent(),/Qwen/);await page.locator('#lora-close').click();
  await open('qwen');await page.waitForFunction(()=>!document.querySelector('#lora-browse-tab').disabled);const waitingSearch=arm('search');await page.locator('#lora-browse-tab').click();await waitingSearch;await page.locator('#lora-close').click();await open('flux2-klein-4b');await page.locator('#lora-browse-tab').click();await page.waitForFunction(()=>!loraLibraryBusy&&document.querySelector('#lora-search-results').textContent.includes('Community style for FLUX.2 Klein 4B'));await settleOld();assert.doesNotMatch(await page.locator('#lora-search-results').textContent(),/Qwen/);assert.match(await page.locator('#lora-search-results').textContent(),/Klein 4B/);assert.equal(await page.locator('#lora-search').isEnabled(),true,'New context searches are not blocked by the previous request');await page.locator('#lora-close').click();
  await open('qwen');await page.locator('#lora-browse-tab').click();await page.waitForFunction(()=>!loraLibraryBusy);const waitingFiles=arm('files');await page.locator('#lora-search-results .lora-use-action').first().click();await waitingFiles;await page.locator('#lora-close').click();await open('flux2-klein-4b');await page.locator('#lora-browse-tab').click();await page.waitForFunction(()=>!loraLibraryBusy);await page.locator('#lora-search-results .lora-use-action').first().click();await page.waitForFunction(()=>loraFilesModelId==='flux2-klein-4b');await settleOld();assert.equal(await page.locator('#lora-file').inputValue(),'flux2-klein-4b-style.safetensors');assert.match(await page.locator('#lora-repo-title').textContent(),/flux2-klein-4b/);assert.doesNotMatch(await page.locator('#lora-repo-title').textContent(),/qwen/);
  assert.equal(await page.locator('#lora-download').isEnabled(),false,'Browser preview cannot start native installs');assert.match(await page.locator('#lora-download-availability').textContent(),/downloads need the desktop app/);assert.equal(await page.locator('#lora-download-availability').isVisible(),true,'A disabled download explains how to proceed');
  await page.evaluate(()=>{nativeSetup=true;window.loraContextNative=[];nativeRequest=async(action,files,details)=>{window.loraContextNative.push({action,...details});return{};};updateLoraDownloadButton();});await page.locator('#lora-download').click();await page.waitForFunction(()=>window.loraContextNative.length===1);nativeRequests=await page.evaluate(()=>window.loraContextNative);assert.equal(nativeRequests[0].model,'flux2-klein-4b');assert.equal(nativeRequests[0].filename,'flux2-klein-4b-style.safetensors');assert.equal(nativeRequests[0].revision,'reviewed-flux2-klein-4b');
  await page.locator('#lora-query').fill('no-such-style-example');await page.locator('#lora-search').click();await page.waitForFunction(()=>!loraLibraryBusy);assert.equal(await page.locator('#lora-search-results .lora-example-tile').count(),0);assert.match(await page.locator('#lora-search-results').textContent(),/No matching local styles/);await page.getByRole('button',{name:'Show recommended',exact:true}).click();await page.waitForFunction(()=>!loraLibraryBusy);assert.equal(await page.locator('#lora-query').inputValue(),'');assert.ok(await page.locator('#lora-search-results .lora-example-tile').count()>0);assert.doesNotMatch(await page.locator('#lora-search-results').textContent(),/Qwen/);
  await page.screenshot({path:path.join(output,'correct-context.png'),animations:'disabled'});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(output,'results.json'),JSON.stringify({status:'passed',checks:['Delayed inventory cannot cross models','Delayed live search cannot cross models','Delayed file metadata cannot cross models','New-context search stays enabled','Trusted download uses current model and pinned file','Query filters recommended styles','Show recommended clears the filter'],nativeRequests},null,2));console.log('PASS: delayed LoRA inventory/search/file responses stay within their model and dialog; current trusted download remains bound to pinned metadata; curated query filtering and Show recommended work.');
 }catch(error){await page.screenshot({path:path.join(output,'failure.png')});throw error;}finally{release?.();await page.unrouteAll({behavior:'ignoreErrors'});await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
