// UI integration uses real image imports, with mocked GPU and library responses.
const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const base=process.env.LOCAL_REMOVE_TEST_URL||'http://127.0.0.1:51249';
const output=path.resolve(process.argv[2]||'qa-artifacts/studio-refinement');fs.mkdirSync(output,{recursive:true});
const source=fs.readFileSync('qa-artifacts/v05/generation-flux/flux2-klein-4b-text.png');
const models=['qwen','z-image-turbo','flux2-klein-4b','flux2-klein-9b'].map(id=>({id,label:{qwen:'Qwen Image 2.1','z-image-turbo':'Z-Image Turbo','flux2-klein-4b':'FLUX.2 Klein 4B','flux2-klein-9b':'FLUX.2 Klein 9B'}[id],available:true,variants:(id==='qwen'?['int8','bf16']:[id==='flux2-klein-9b'?'fp8':'bf16']).map(id=>({id,label:id.toUpperCase(),available:true})),capabilities:{text_to_image:true,image_reference:id!=='z-image-turbo',image_to_image:id==='z-image-turbo',max_references:id==='qwen'?10:id==='z-image-turbo'?1:4,transparent:id==='qwen',negative_prompt:id==='qwen',denoise:id==='z-image-turbo'},defaults:{variant:id==='qwen'?'int8':id==='flux2-klein-9b'?'fp8':'bf16',width:1024,height:1024,steps:id==='qwen'?25:id==='z-image-turbo'?8:4,guidance:1},limits:{min_dimension:256,max_dimension:4096,dimension_step:32,max_pixels:4194304,min_steps:1,max_steps:100,min_guidance:1,max_guidance:id==='qwen'?10:1}}));
async function main(){
  const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'msedge'}),page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[],requests=[],upscales=[];let items=[],deleted=[],upscaleEnabled=false,upscaleFailure=false;
  page.on('pageerror',error=>errors.push(error.message));await page.addInitScript(()=>{localStorage.setItem('local-image.hardware-guide.v1','1');localStorage.setItem('local-image.first-ai-setup.v1','1');});
  await page.route('**/api/local-remove/generation/models',route=>route.fulfill({json:{connected:true,default_model:'qwen',models}}));
  await page.route('**/api/local-remove/generation/upscale/models',route=>route.fulfill({json:{enabled:upscaleEnabled,model:{id:'seedvr2',available:true,label:'SeedVR2 7B'},limits:{min_dimension:256,max_dimension:4096,max_pixels:16777216}}}));
  await page.route('**/api/local-remove/generation/upscale',async route=>{const payload=route.request().postDataJSON();upscales.push(payload);if(upscaleFailure)return route.fulfill({status:400,json:{detail:'Test upscale failure'}});const data=await importImage(route.request().headers()['x-local-remove-token'],null);data.width=payload.width;data.height=payload.height;data.upscale={model:'seedvr2',...payload};return route.fulfill({json:{session:data,upscale:data.upscale}});});
  const inventory=()=>({items,count:items.length,bytes:items.reduce((sum,item)=>sum+item.bytes,0)});
  async function importImage(token,parameters){const response=await page.request.post(base+'/api/local-remove/import',{headers:{'x-local-remove-token':token},multipart:{file:{name:'Red chair draft.png',mimeType:'image/png',buffer:source}}});assert.equal(response.status(),200);const data=await response.json();data.generation=parameters;data.dirty=true;return data;}
  await page.route('**/api/local-remove/generation',async route=>{const payload=route.request().postDataJSON();requests.push(payload);const data=await importImage(route.request().headers()['x-local-remove-token'],payload);data.width=payload.width;data.height=payload.height;items.unshift({id:crypto.randomUUID(),name:data.name,width:data.width,height:data.height,model:payload.model,variant:payload.variant,created_at:Date.now()/1000,bytes:1234567,generation:payload,thumbnail:'/api/local-remove/session/'+data.id+'/preview',session:data});await new Promise(resolve=>setTimeout(resolve,100));await route.fulfill({json:{session:data,model:payload.model,width:payload.width,height:payload.height,seed:payload.seed??123,reference_count:payload.reference_session_ids.length}});});
  await page.route('**/api/local-remove/generation/library**',async route=>{
    const address=new URL(route.request().url());
    if(address.pathname.endsWith('/delete')){const payload=route.request().postDataJSON();deleted.push(payload);const ids=payload.all?items.map(item=>item.id):payload.ids;items=items.filter(item=>!ids.includes(item.id));return route.fulfill({json:{...inventory(),deleted:ids,freed_bytes:ids.length*1234567}});}
    if(address.pathname.endsWith('/open')){const id=address.pathname.split('/').at(-2),item=items.find(item=>item.id===id);return route.fulfill({json:{session:await importImage(route.request().headers()['x-local-remove-token'],item.generation)}});}
    return route.fulfill({json:inventory()});
  });
  try{
    await page.goto(base+'/remove');await page.waitForFunction(()=>settingsLoaded);await page.locator('#file').setInputFiles({name:'Chair.png',mimeType:'image/png',buffer:source});await page.waitForFunction(()=>!!session&&!busy);
    const editorId=await page.evaluate(()=>session.id);await page.locator('#workspace-generate').click();await page.waitForFunction(()=>!generationLoading&&generationModels.length===4);await page.locator('#gen-prompt').fill('Main generator prompt remains unchanged');
    await page.locator('#draft-refine-open').click();await page.waitForFunction(()=>refineInitialized);assert.equal(await page.locator('#refine-dialog').isVisible(),true);assert.equal(await page.locator('#refine-final-model option[value="z-image-turbo"]').count(),0,'Variation-only Z cannot be chosen for semantic refinement');assert.equal(await page.locator('#refine-draft-model').inputValue(),'flux2-klein-4b');assert.equal(await page.locator('#refine-final-model').inputValue(),'flux2-klein-9b');
    assert.equal(await page.locator('#refine-upscale-options').isVisible(),false,'Unapproved upscale feature is hidden');assert.match(await page.locator('#refine-final-prompt').inputValue(),/Preserve.*composition/);assert.equal(await page.locator('#refine-final-run').isEnabled(),false);await page.locator('#refine-final-prompt').fill('Keep this exact red chair and room. Improve only fine fabric and natural light.');
    await page.locator('#refine-draft-prompt').fill('A red velvet chair beside a window in a minimal room');await page.locator('#refine-draft-options > summary').click();await page.locator('#refine-current-reference').click();await page.locator('#refine-draft-seed').fill('0');await page.locator('#refine-draft-run').click();await page.waitForFunction(()=>refineDrafts.length===1&&!refineJob);
    assert.equal(requests[0].model,'flux2-klein-4b');assert.equal(requests[0].steps,4);assert.equal(requests[0].seed,0);assert.deepEqual(requests[0].reference_session_ids,[editorId]);assert.equal(await page.evaluate(()=>session.id),editorId,'Generating in the dedicated window preserves the editor document');
    await page.locator('#refine-draft-options > summary').click();await page.locator('#refine-final-width').fill('4096');await page.locator('#refine-final-height').fill('4096');assert.equal(await page.locator('#refine-final-run').isEnabled(),false,'Refinement cannot silently exceed render pixel budget');await page.locator('#refine-final-width').fill('2048');await page.locator('#refine-final-height').fill('2048');await page.locator('#refine-final-steps').fill('6');
    await page.locator('#refine-final-run').click();await page.waitForFunction(()=>refineResults.length===1&&!refineJob);assert.equal(requests[1].model,'flux2-klein-9b');assert.equal(requests[1].variant,'fp8');assert.equal(requests[1].steps,6);assert.equal(requests[1].width,2048);assert.equal(requests[1].reference_session_ids.length,1);assert.notEqual(requests[1].reference_session_ids[0],editorId);assert.match(requests[1].prompt,/exact red chair/);
    await page.locator('#refine-final-model').selectOption('qwen');assert.equal(await page.locator('#refine-final-steps').inputValue(),'25');assert.equal(await page.locator('#refine-draft-model').inputValue(),'flux2-klein-4b','Independent model pickers');await page.locator('#refine-final-prompt').fill('A second editable refinement instruction');
    await page.locator('#refine-final-prompt').evaluate(element=>element.closest('.refine-settings').querySelector('details').open=true);await page.locator('#refine-include-references').check();await page.locator('#refine-final-guidance').fill('3');await page.locator('#refine-negative').fill('extra furniture');await page.locator('#refine-final-run').click();await page.waitForFunction(()=>refineResults.length===2&&!refineJob);assert.equal(requests[2].reference_session_ids.length,2);assert.equal(requests[2].negative_prompt,'extra furniture');assert.equal(requests[2].guidance,3);
    await page.locator('#refine-final-prompt').evaluate(element=>element.closest('.refine-settings').querySelector('details').open=false);
    for(const [width,height]of [[1440,900],[1024,768],[800,600]]){await page.setViewportSize({width,height});for(const id of ['refine-draft-run','refine-final-run','refine-close']){const bounds=await page.locator('#'+id).boundingBox();assert.ok(bounds.x>=0&&bounds.x+bounds.width<=width&&bounds.y+bounds.height<=height,id+' stays visible');}assert.equal(await page.locator('#refine-dialog').evaluate(element=>element.scrollWidth>element.clientWidth),false);await page.screenshot({path:path.join(output,'refinement-'+width+'.png'),animations:'disabled'});}
    await page.locator('#refine-close').click();assert.equal(await page.locator('#gen-prompt').inputValue(),'Main generator prompt remains unchanged');await page.locator('#draft-refine-open').click();await page.waitForFunction(()=>refineInitialized);assert.equal(await page.locator('#refine-final-prompt').inputValue(),'A second editable refinement instruction','Reopening keeps the experimental prompts and results');await page.locator('#refine-library').click();await page.waitForFunction(()=>!generatedLibraryBusy&&generatedLibrary.count===3);assert.equal(await page.locator('#refine-dialog').isVisible(),true);assert.equal(await page.locator('#generated-library-as-draft').isEnabled(),false);
    await page.locator('#generated-library-grid input').first().check();assert.equal(await page.locator('#generated-library-as-draft').isEnabled(),true);await page.locator('#generated-library-as-draft').click();await page.waitForFunction(()=>refineDrafts.length===2&&!generatedLibraryBusy);assert.equal(await page.locator('#generated-library-dialog').isVisible(),false);assert.equal(await page.locator('#refine-final-run').isEnabled(),true);
    await page.locator('#refine-library').click();await page.waitForFunction(()=>!generatedLibraryBusy);await page.locator('#generated-library-select-all').check();assert.equal(await page.locator('#generated-library-edit').isEnabled(),false,'Multi-selection cannot silently open an arbitrary image');
    for(const [width,height]of [[1440,900],[1024,768],[800,600]]){await page.setViewportSize({width,height});const bounds=await page.locator('#generated-library-clear').boundingBox();assert.ok(bounds.y+bounds.height<=height);await page.screenshot({path:path.join(output,'library-'+width+'.png'),animations:'disabled'});}
    await page.locator('#generated-library-delete').click();assert.equal(deleted.length,0,'Deletion needs the explicit final confirmation');await page.locator('#generated-library-cancel-delete').click();assert.equal(deleted.length,0);await page.locator('#generated-library-select-all').uncheck();await page.locator('#generated-library-grid input').first().check();await page.locator('#generated-library-delete').click();await page.locator('#generated-library-confirm-delete').click();await page.waitForFunction(()=>generatedLibrary.count===2&&!generatedLibraryBusy);assert.equal(deleted[0].ids.length,1);assert.equal(await page.evaluate(()=>session.id),editorId,'Deleting a library copy does not close active editor work');
    await page.locator('#generated-library-clear').click();await page.locator('#generated-library-confirm-delete').click();await page.waitForFunction(()=>generatedLibrary.count===0&&!generatedLibraryBusy);assert.deepEqual(deleted[1],{all:true});assert.match(await page.locator('#generated-library-status').textContent(),/Freed/);assert.equal(await page.locator('#generated-library-empty').isVisible(),true);
    await page.locator('#generated-library-close').click();await page.locator('#refine-close').click();upscaleEnabled=true;await page.locator('#draft-refine-open').click();await page.waitForFunction(()=>refineUpscaleStatus?.enabled);assert.equal(await page.locator('#refine-upscale-options').isVisible(),true);assert.equal(await page.locator('#refine-upscale').isChecked(),false,'Upscaling is optional and defaults off');
    const generationCount=requests.length;await page.locator('#refine-upscale-only').click();await page.waitForFunction(()=>!refineJob&&refineSelectedResult()?.session.upscale);assert.equal(requests.length,generationCount,'Direct upscaling does not perform a semantic edit');assert.equal(upscales.length,1);assert.equal(upscales[0].width,3840);assert.equal(upscales[0].height,3840);assert.equal(await page.evaluate(()=>hasWorkingLayers(refineSelectedResult().session)),true,'Upscaled photos receive unsaved-document protection');
    await page.locator('#refine-upscale').check();await page.locator('#refine-aspect').selectOption('16:9');assert.equal(await page.locator('#refine-upscale-width').inputValue(),'3840');assert.equal(await page.locator('#refine-upscale-height').inputValue(),'2160');await page.locator('#refine-final-run').click();await page.waitForFunction(()=>!refineJob&&refineSelectedResult()?.session.width===3840&&refineSelectedResult()?.session.height===2160);assert.equal(upscales.length,2);assert.equal(requests.at(-1).width*requests.at(-1).height<=4194304,true);assert.equal(upscales.at(-1).width,3840);assert.equal(upscales.at(-1).height,2160);
    await page.locator('#refine-upscale-width').fill('4096');await page.locator('#refine-upscale-height').fill('4096');assert.equal(await page.locator('#refine-final-run').isEnabled(),false,'Aspect-changing upscale is rejected before GPU work');await page.locator('#refine-upscale-preset').selectOption('3840');upscaleFailure=true;await page.locator('#refine-final-run').click();await page.waitForFunction(()=>!refineJob&&document.querySelector('#refine-status').textContent.includes('Upscale failed'));assert.match(await page.locator('#refine-status').textContent(),/Refinement saved/);assert.equal(await page.evaluate(()=>!!refineSelectedResult().session.upscale),false,'Successful unscaled refinement stays selected after upscale failure');
    await page.route('**/api/local-remove/generator/download',route=>route.fulfill({json:{model:'seedvr2',running:false,phase:'complete',message:'Model files verified',models:[]}}));await page.evaluate(()=>{refineUpscaleStatus.model.available=false;nativeSetup=true;window.upscaleNativeRequests=[];nativeRequest=async(action,files,details)=>{window.upscaleNativeRequests.push({action,...details});return{};};updateRefineControls();});await page.locator('#refine-upscale-download').click();await page.waitForFunction(()=>!refineUpscaleSetupBusy&&refineUpscaleStatus.model.available);assert.deepEqual(await page.evaluate(()=>window.upscaleNativeRequests),[{action:'setupDownloadGenerationModel',model:'seedvr2',variant:'fp16'}]);assert.equal(await page.locator('#refine-upscale-setup').isVisible(),false,'Completed download refreshes readiness');
    await page.evaluate(()=>{const ernie={...generationModels.find(model=>model.id==='qwen'),id:'ernie-image',label:'ERNIE Image',capabilities:{text_to_image:true,image_reference:false,image_to_image:false,max_references:0,transparent:false,lora:false},defaults:{variant:'bf16',width:1024,height:1024,steps:50,guidance:4},variants:[{id:'bf16',label:'BF16',available:true}]};generationModels.push(ernie);fillRefineModels('draft');fillRefineModels('final');});assert.equal(await page.locator('#refine-final-model option[value="ernie-image"]').count(),0);await page.locator('#refine-draft-model').selectOption('ernie-image');assert.equal(await page.locator('#refine-draft-steps').inputValue(),'50');assert.equal(await page.locator('#refine-add-reference').isEnabled(),false);await page.locator('#refine-draft-run').click();await page.waitForFunction(()=>!refineJob&&refineSelectedDraft()?.session.generation?.model==='ernie-image');assert.deepEqual(requests.at(-1).reference_session_ids,[],'A text-only draft model never receives hidden references');
    await page.setViewportSize({width:1440,height:900});await page.locator('.refine-settings').evaluateAll(elements=>elements.forEach(element=>element.scrollTop=0));await page.screenshot({path:path.join(output,'refinement-upscale-controls.png'),animations:'disabled'});
    assert.deepEqual(errors,[]);console.log('PASS: independent draft/refinement models, editable defaults, selected-reference handoff, resolution/sampling limits, extra refs, prompt persistence, library multiselect/open/delete/clear isolation, gated direct/chained 4K upscaling, failure retention and 1440/1024/800 layouts. GPU and library mutations mocked.');
  }catch(error){await page.screenshot({path:path.join(output,'failure.png'),animations:'disabled'});throw error;}finally{await page.unrouteAll({behavior:'ignoreErrors'});await browser.close();}
}
main().catch(error=>{console.error(error);process.exitCode=1;});
