// Studio navigation and generation request coverage; model execution is validated
// separately by the live ComfyUI acceptance runner.
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path');
const output=path.resolve(process.argv[2]||'qa-artifacts/studio-generation');fs.mkdirSync(output,{recursive:true});
const base=process.env.LOCAL_REMOVE_TEST_URL||'http://127.0.0.1:51249';
const models=['qwen','z-image-turbo','flux2-klein-4b','flux2-klein-9b'].map(id=>({id,label:{qwen:'Qwen Image 2.1','z-image-turbo':'Z-Image Turbo','flux2-klein-4b':'FLUX.2 Klein 4B','flux2-klein-9b':'FLUX.2 Klein 9B','hidream-o1':'HiDream O1 Full','flux2-dev':'FLUX.2 Dev'}[id],benefit:id==='qwen'?'Edits and transparent assets':id==='z-image-turbo'?'Fast image generation':'Reference editing',available:true,variants:(id==='qwen'?['int8','bf16']:[['flux2-dev','flux2-klein-9b','hidream-o1'].includes(id)?'fp8':'bf16']).map(id=>({id,label:id.toUpperCase(),available:true})),capabilities:{text_to_image:true,image_reference:id!=='z-image-turbo',image_to_image:true,max_references:['qwen','hidream-o1'].includes(id)?10:id==='z-image-turbo'?1:4,transparent:id==='qwen',negative_prompt:['qwen','hidream-o1'].includes(id),denoise:id==='z-image-turbo'},defaults:{variant:id==='qwen'?'int8':['flux2-dev','flux2-klein-9b','hidream-o1'].includes(id)?'fp8':'bf16',guidance:id==='hidream-o1'?5:id==='flux2-dev'?4:1,steps:id==='hidream-o1'?50:id==='qwen'?25:id==='z-image-turbo'?8:id==='flux2-dev'?20:4,width:id==='hidream-o1'?2048:1024,height:id==='hidream-o1'?2048:1024},limits:{min_dimension:256,max_dimension:4096,dimension_step:32,max_pixels:4194304,min_steps:1,max_steps:100,min_guidance:1,max_guidance:['qwen','hidream-o1','flux2-dev'].includes(id)?10:1}}));
models.splice(2,0,{id:'ernie-image',label:'ERNIE Image',benefit:'Posters and text',available:true,variants:[{id:'bf16',label:'BF16',available:true}],capabilities:{text_to_image:true,image_reference:false,image_to_image:false,max_references:0,transparent:false,negative_prompt:true,denoise:false,lora:false,loras:false},defaults:{variant:'bf16',width:1024,height:1024,steps:50,guidance:4},limits:{min_dimension:256,max_dimension:4096,dimension_step:32,max_pixels:4194304,min_steps:1,max_steps:100,min_guidance:1,max_guidance:10}});
for(const model of models){model.description=model.benefit;model.strengths=['Local image creation','Optional model-specific adapters'];model.limitations=['Quality depends on prompt and source images.'];model.hardware={vram_recommendation:model.id==='flux2-dev'?'48 GB recommended':'24 GB recommended',basis:'Planning recommendation, not a hard minimum.'};model.license={label:'Model license',url:'https://example.com/license'};for(const variant of model.variants){variant.total_bytes=20000000000;variant.missing_bytes=0;}}
async function main(){
  const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'msedge'}),page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  await page.route('**/api/local-remove/generation/models',route=>route.fulfill({json:{connected:true,default_model:'qwen',models}}));
  await page.route('**/api/local-remove/generator/download',route=>route.fulfill({json:{running:false,phase:'idle',models:[]}}));
  let searches=0,fileRevisions=[];
  await page.route('**/api/local-remove/loras**',async route=>{const address=new URL(route.request().url());
    if(address.pathname.endsWith('/search')){searches++;assert.equal(address.searchParams.get('model'),'z-image-turbo');return route.fulfill({json:{results:[{repo_id:'community/new-style',title:'New community style',compatibility:'unverified'},{repo_id:'community/custom-sampler',title:'Custom sampler adapter',compatibility:'unverified',supported:false,warning:'Requires a custom sampling workflow'}]}});}
    if(address.pathname.endsWith('/files')){fileRevisions.push(address.searchParams.get('revision'));return route.fulfill({json:{repo_id:'community/new-style',revision:'pinned-commit',compatibility:'declared',files:[{filename:'adapter.safetensors',bytes:123456,compatibility:'unverified'},{filename:'reviewed.safetensors',bytes:456789,compatibility:'curated',recommended_settings:{steps:8,guidance:1},description:'Reviewed watercolor treatment',style:'Watercolor',trigger_phrase:'watercolor detail',experimental:true,usage:'text-to-image'}]}});}
    if(address.pathname.endsWith('/download'))return route.fulfill({json:{running:false,phase:'complete',message:'Download complete.'}});
    return route.fulfill({json:{installed:[{id:'installed-style',model:'z-image-turbo',title:'Installed style',filename:'style.safetensors',compatibility:'curated',bytes:123456,recommended_strength:.7,description:'Reference texture study',usage:'reference-edit',trigger_phrase:'textured style',experimental:true}],curated:[{repo_id:'community/new-style',title:'Reviewed watercolor',filename:'reviewed.safetensors',revision:'reviewed-commit',compatibility:'curated',description:'Reviewed style adapter',style:'Watercolor',trigger_phrase:'watercolor detail',experimental:true}],job:{running:false}}});
  });
  try{
    await page.goto(base+'/remove');
    await page.waitForFunction(()=>document.querySelector('#hardware-dialog').open&&document.querySelectorAll('#hardware-profiles tr').length>=5);
    assert.match(await page.locator('#hardware-note').textContent(),/not hard minimum/i);
    await page.screenshot({path:path.join(output,'01-first-start-guide.png')});
    await page.locator('#hardware-continue').click();await page.reload();await page.waitForFunction(()=>settingsLoaded);
    assert.equal(await page.locator('#hardware-dialog').isVisible(),false,'Hardware guide appears only until explicitly continued');
    await page.locator('#help-menu-trigger').click();await page.locator('#hardware-guide').click();assert.equal(await page.locator('#hardware-dialog').isVisible(),true);await page.locator('#hardware-close').click();
    await page.locator('#workspace-generate').click();await page.waitForFunction(count=>generationModels.length===count&&!generationLoading,models.length);
    assert.equal(await page.locator('#gen-model option').count(),models.length);assert.match(await page.locator('#gen-model option').first().textContent(),/Edits & alpha/);
    await page.locator('#model-browser').click();await page.waitForFunction(count=>document.querySelectorAll('#model-browser-list button').length===count,models.length);assert.equal(await page.locator('#model-browser-dialog').isVisible(),true);
    await page.locator('#model-browser-list button').last().click();assert.match(await page.locator('#model-browser-memory').textContent(),/24 GB/);assert.match(await page.locator('#model-browser-size').textContent(),/18.6 GB.*already installed/);assert.equal(await page.locator('#model-browser-download').isEnabled(),false,'Already installed model files cannot be downloaded again');
    await page.locator('#model-browser-list button').first().focus();await page.keyboard.press('End');assert.equal(await page.locator('#model-browser-list button').last().getAttribute('aria-current'),'true');
    await page.evaluate(()=>{nativeSetup=true;window.modelNativeRequests=[];nativeRequest=async(action,files,details)=>{window.modelNativeRequests.push({action,...details});return action==='setupChooseModelDirectory'?{model_directory:'Chosen model folder',model_folder_connection:{status:'restart_required',message:'Folder saved. Restart ComfyUI to connect this folder.'}}:{};};const variant=browserModel().variants[0];variant.available=false;variant.missing_bytes=variant.total_bytes;renderModelBrowser();});
    await page.locator('#model-browser-download').click();await page.waitForFunction(()=>!modelBrowserRequest);assert.deepEqual(await page.evaluate(()=>window.modelNativeRequests[0]),{action:'setupDownloadGenerationModel',model:'flux2-klein-9b',variant:'fp8'});
    await page.locator('#model-browser-folder').click();await page.waitForFunction(()=>!modelBrowserRequest);assert.match(await page.locator('#model-browser-status').textContent(),/Restart ComfyUI/);assert.equal(await page.locator('#model-browser-path').textContent(),'Chosen model folder');
    await page.locator('#model-browser-list button').first().click();await page.locator('#model-browser-variant').selectOption('bf16');await page.screenshot({path:path.join(output,'05-model-browser.png')});await page.locator('#model-browser-use').click();assert.equal(await page.locator('#gen-variant').inputValue(),'bf16');await page.evaluate(()=>{nativeSetup=false;modelFolderConnection=null;});
    assert.equal(await page.locator('#retouch-panel').isVisible(),false);assert.equal(await page.locator('#cutout-panel').isVisible(),false);
    assert.equal(await page.locator('#gen-run').isEnabled(),false,'Empty prompts cannot generate');
    await page.locator('#gen-prompt').fill('A red ceramic vase on a pale studio table');assert.equal(await page.locator('#gen-run').isEnabled(),true);
    await page.locator('#gen-output-tab').focus();await page.keyboard.press('ArrowLeft');assert.equal(await page.locator('#gen-reference-tab').getAttribute('aria-selected'),'true','Studio tabs support arrow navigation');
    await page.locator('#gen-output-tab').click();assert.equal(await page.locator('#gen-steps').isVisible(),true,'Steps are exposed beside resolution without opening advanced sampling');assert.match(await page.locator('#gen-sampling-note').textContent(),/Recommended for this model: 25 steps/);await page.locator('#gen-aspect').selectOption('16:9');assert.equal(await page.locator('#gen-width').inputValue(),'1536');assert.equal(await page.locator('#gen-height').inputValue(),'864');
    assert.match(await page.locator('#gen-transparent-note').textContent(),/filled with white/);await page.locator('#gen-transparent').check();await page.locator('#gen-seed').fill('0');
    await page.locator('#gen-width').fill('4096');await page.locator('#gen-height').fill('4096');assert.equal(await page.locator('#gen-run').isEnabled(),false,'Pixel budget is validated before generation');
    await page.locator('#gen-aspect').selectOption('1:1');
    await page.locator('#gen-prompt-tab').click();await page.locator('#gen-model').selectOption('z-image-turbo');
    assert.equal(await page.locator('#gen-variant').isVisible(),false,'Single precision presets do not show a redundant selector');assert.equal(await page.locator('#gen-negative-options').isVisible(),false);
    await page.locator('#gen-output-tab').click();assert.equal(await page.locator('#gen-transparent-row').isVisible(),false,'Models without RGBA cannot request transparency');assert.equal(await page.locator('#gen-transparent-note').isVisible(),false,'White alpha fallback guidance is limited to models with alpha');
    await page.locator('#gen-reference-tab').click();assert.match(await page.locator('#gen-reference-note').textContent(),/starting image/);
    // Import a deterministic local reference using the real import endpoint.
    const bytes=await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=512;canvas.height=512;const ctx=canvas.getContext('2d');ctx.fillStyle='#d0c0ad';ctx.fillRect(0,0,512,512);ctx.fillStyle='#963f32';ctx.fillRect(180,100,150,300);return canvas.toDataURL('image/png').split(',')[1];});
    await page.locator('#generation-reference-file').setInputFiles({name:'Reference.png',mimeType:'image/png',buffer:Buffer.from(bytes,'base64')});await page.waitForFunction(()=>generationReferences.length===1&&!busy);
    assert.equal(await page.locator('#gen-denoise-options').isVisible(),true);assert.equal(await page.locator('#gen-add-reference').isEnabled(),false,'Z-Image accepts exactly one starting image');
    await page.locator('#gen-prompt-tab').click();await page.locator('#gen-lora-options > summary').click();await page.locator('#lora-library').click();
    const promptBeforeAdapter=await page.locator('#gen-prompt').inputValue();await page.locator('#lora-installed-list').getByRole('button',{name:'Use',exact:true}).click();assert.equal(await page.locator('#gen-selected-loras input').inputValue(),'0.7');assert.equal(await page.locator('#gen-prompt').inputValue(),promptBeforeAdapter,'Selecting an adapter does not rewrite a prompt');await page.locator('#lora-installed-list').getByRole('button',{name:'Add trigger',exact:true}).click();assert.match(await page.locator('#gen-prompt').inputValue(),/textured style/);await page.evaluate(()=>{window.adapterReferences=generationReferences;generationReferences=[];updateGenerationControls();});assert.equal(await page.locator('#gen-run').isEnabled(),false);assert.match(await page.locator('#gen-lora-note').textContent(),/requires an image/);await page.evaluate(()=>{generationReferences=window.adapterReferences;updateGenerationControls();});assert.equal(await page.locator('#gen-lora-count').textContent(),'1');
    await page.locator('#lora-browse-tab').click();await page.waitForFunction(()=>document.querySelector('#lora-last-checked').textContent.includes('Checked'));
    assert.match(await page.locator('#lora-search-results').textContent(),/compatibility unverified/);await page.locator('#lora-refresh').click();await page.waitForFunction(()=>!document.querySelector('#lora-refresh').disabled);assert.ok(searches>=2,'Browse refresh queries live search again');
    assert.equal(await page.getByRole('button',{name:'Unsupported',exact:true}).isEnabled(),false);await page.getByRole('button',{name:'View files',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#lora-file').value==='reviewed.safetensors');assert.equal(fileRevisions.at(-1),'reviewed-commit');assert.equal(await page.locator('#lora-file').inputValue(),'reviewed.safetensors','Curated style selects its exact reviewed file');assert.match(await page.locator('#lora-file-usage').textContent(),/Experimental.*Watercolor/);assert.match(await page.locator('#lora-file-trigger').textContent(),/watercolor detail/);await page.locator('#lora-add-trigger').click();assert.match(await page.locator('#gen-prompt').inputValue(),/watercolor detail/);await page.locator('#lora-file').selectOption('adapter.safetensors');
    await page.evaluate(()=>{nativeSetup=true;window.loraNativeRequests=[];nativeRequest=async(action,files,details)=>{window.loraNativeRequests.push({action,...details});return{};};});
    await page.locator('#lora-unverified').dispatchEvent('change');assert.equal(await page.locator('#lora-download').isEnabled(),false,'Unverified adapters require explicit model assignment');
    await page.locator('#lora-file').selectOption('reviewed.safetensors');assert.equal(await page.locator('#lora-unverified-row').isVisible(),false);assert.equal(await page.locator('#lora-download').isEnabled(),true);await page.locator('#lora-apply-settings').click();assert.equal(await page.locator('#gen-steps').inputValue(),'8');
    await page.locator('#lora-file').selectOption('adapter.safetensors');assert.equal(await page.locator('#lora-download').isEnabled(),false,'New files in a reviewed repository do not inherit trust');
    await page.locator('#lora-unverified').check();assert.equal(await page.locator('#lora-download').isEnabled(),true);await page.locator('#lora-download').click();
    await page.waitForFunction(()=>window.loraNativeRequests.length===1);const native=await page.evaluate(()=>window.loraNativeRequests[0]);assert.equal(native.model,'z-image-turbo');assert.equal(native.allow_unverified,true);assert.equal(native.revision,'pinned-commit');
    assert.equal(await page.locator('#gen-lora-count').textContent(),'1','Downloaded adapters are not automatically enabled');await page.screenshot({path:path.join(output,'02-lora-browser.png')});await page.locator('#lora-close').click();
    await page.locator('#gen-selected-loras input').fill('0.75');await page.locator('#gen-selected-loras input').dispatchEvent('change');
    let sent=null;
    await page.route('**/api/local-remove/generation',async route=>{sent=route.request().postDataJSON();const reference=await page.evaluate(async()=>await(await api('/api/local-remove/session/'+(generationReferences[0]?.id||session.id))).json());reference.generation={...sent};reference.dirty=true;await route.fulfill({json:{session:reference,model:sent.model,variant:sent.variant,seed:sent.seed??42,width:sent.width,height:sent.height,reference_count:sent.reference_session_ids.length}});});
    await page.locator('#gen-run').click();await page.waitForFunction(()=>!!session?.generation&&!busy);
    assert.equal(sent.model,'z-image-turbo');assert.equal(sent.transparent,false);assert.equal(sent.seed,0);assert.equal(sent.reference_session_ids.length,1);assert.equal(sent.denoise,.65);assert.equal(sent.negative_prompt,undefined);assert.deepEqual(sent.loras,[{id:'installed-style',strength:.75}]);
    assert.equal(await page.locator('#generated-retouch').isEnabled(),true);assert.equal(await page.evaluate(()=>hasWorkingLayers(session)),true,'Unsaved generated output receives close/save protection');
    await page.locator('#generated-retouch').click();assert.equal(await page.locator('#workspace-retouch').getAttribute('aria-pressed'),'true');
    await page.locator('#workspace-generate').click();await page.locator('#gen-prompt-tab').click();await page.locator('#gen-model').selectOption('qwen');assert.equal(await page.locator('#gen-variant').inputValue(),'bf16');assert.equal(await page.locator('#gen-lora-count').textContent(),'0','Adapters cannot leak across model families');
    await page.locator('#gen-output-tab').click();await page.locator('#gen-sampling-options > summary').click();await page.locator('#gen-guidance').fill('4');await page.locator('#gen-steps').fill('8');await page.locator('#gen-run').click();await page.waitForFunction(()=>!busy&&session?.generation?.model==='qwen');assert.equal(sent.steps,8);assert.equal(sent.guidance,4);assert.equal(sent.negative_prompt,'');await page.locator('#gen-reference-tab').click();assert.match(await page.locator('#gen-reference-note').textContent(),/up to 10/);assert.equal(await page.locator('#gen-denoise-options').isVisible(),false,'Semantic references do not expose unsupported strength');
    await page.locator('#gen-prompt-tab').click();
    for(const [width,height]of [[1440,900],[1024,768],[800,600]]){await page.setViewportSize({width,height});const bounds=await page.locator('#gen-run').boundingBox();assert.ok(bounds.x>=0&&bounds.x+bounds.width<=width&&bounds.y+bounds.height<=height,'Generate remains visible');assert.equal(await page.locator('body').evaluate(element=>element.scrollWidth>innerWidth),false);await page.screenshot({path:path.join(output,'generation-'+width+'.png')});}
    // Reopen a generated document with stored metadata, as portable projects do.
    await page.evaluate(async()=>{const reopened={...session,generation:{model:'qwen',variant:'bf16',prompt:'Saved project prompt',negative_prompt:'unwanted text',width:768,height:1024,seed:0,steps:31,guidance:3.5,transparent:true,reference_count:2,loras:[{id:'missing-project-adapter',strength:.8}]}};viewStates.delete(reopened.id);openDocuments.delete(reopened.id);session=null;await openSession(reopened);});
    assert.equal(await page.locator('#gen-model').inputValue(),'qwen');assert.equal(await page.locator('#gen-variant').inputValue(),'bf16');assert.equal(await page.locator('#gen-prompt').inputValue(),'Saved project prompt');assert.equal(await page.locator('#gen-seed').inputValue(),'0');assert.equal(await page.locator('#gen-width').inputValue(),'768');assert.equal(await page.locator('#gen-steps').inputValue(),'31');assert.equal(await page.locator('#gen-guidance').inputValue(),'3.5');assert.equal(await page.locator('#gen-transparent').isChecked(),true);
    assert.match(await page.locator('#gen-reference-note').textContent(),/Reattach.*0 attached/);assert.match(await page.locator('#gen-result-note').textContent(),/unavailable/);assert.equal(await page.locator('#gen-run').isEnabled(),false,'Missing portable-project adapters cannot run silently');
    await page.locator('#gen-prompt-tab').click();await page.locator('#gen-selected-loras button').click();assert.equal(await page.locator('#gen-run').isEnabled(),true);
    await page.locator('#gen-prompt').fill('A new unsaved prompt draft');await page.locator('#workspace-retouch').click();await page.locator('#workspace-generate').click();assert.equal(await page.locator('#gen-prompt').inputValue(),'A new unsaved prompt draft','Persona switching preserves generation drafts');
    await page.locator('#gen-prompt-tab').click();await page.locator('#gen-model').selectOption('flux2-klein-9b');assert.equal(await page.locator('#gen-variant').inputValue(),'fp8');assert.equal(await page.locator('#gen-steps').inputValue(),'4');assert.equal(await page.locator('#gen-guidance').inputValue(),'1');assert.equal(await page.locator('#gen-negative-options').isVisible(),false);
    await page.evaluate(()=>addGenerationReference(session));await page.locator('#gen-model').selectOption('ernie-image');assert.equal(await page.locator('#gen-reference-tab').isVisible(),false,'T2I-only models hide the References tab');assert.equal(await page.locator('#gen-lora-options').isVisible(),false);assert.equal(await page.locator('#gen-steps').inputValue(),'50');assert.equal(await page.locator('#gen-guidance').inputValue(),'4');assert.equal(await page.locator('#gen-run').isEnabled(),true,'Retained reference drafts do not block a text-only model');await page.locator('#gen-prompt-tab').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.locator('#gen-output-tab').getAttribute('aria-selected'),'true','Studio keyboard navigation skips unsupported tabs');await page.locator('#gen-run').click();await page.waitForFunction(()=>!busy&&session?.generation?.model==='ernie-image');assert.deepEqual(sent.reference_session_ids,[]);assert.deepEqual(sent.loras,[]);assert.equal(sent.steps,50);assert.equal(sent.guidance,4);assert.equal(sent.transparent,false);
    await page.waitForFunction(()=>!generationLoading);await page.evaluate(async()=>{generationModels=generationModels.filter(model=>model.id!=='flux2-dev');await restoreGenerationSettings({model:'flux2-dev',variant:'fp8',prompt:'Historical Dev project',steps:20,guidance:4,width:1024,height:1024,seed:456});});assert.equal(await page.locator('#gen-model').inputValue(),'flux2-dev');assert.match(await page.locator('#gen-model-state').textContent(),/historical model/);assert.equal(await page.locator('#gen-run').isEnabled(),false,'Historical model metadata never silently switches to another generator');assert.equal(await page.locator('#gen-setup-options').isVisible(),false,'Retired model weights are not offered for download');
    assert.deepEqual(errors,[]);console.log('PASS: hardware guide, Studio keyboarding, model catalog capabilities, resolution/seed validation, references, per-file LoRA trust and download, adapter payload, FLUX sampling, generated handoff, project settings/missing assets, draft preservation and three layouts.');
  }catch(error){await page.screenshot({path:path.join(output,'failure.png')});throw error;}finally{await page.unrouteAll({behavior:'ignoreErrors'});await browser.close();}
}
main().catch(error=>{console.error(error);process.exitCode=1;});
