// Production UI and backend; model responses are CPU fixtures in an isolated profile.
const assert=require('node:assert/strict'), fs=require('node:fs'), path=require('node:path');
const {execFileSync}=require('node:child_process'), {chromium}=require('playwright');
const {imageFixture}=require('./helpers/image-fixture.cjs');
const root=path.resolve(__dirname,'..'), base=process.env.LOCAL_REMOVE_TEST_URL, profile=process.env.MIGRATION_REAL_PROFILE, python=process.env.LOCAL_IMAGE_TEST_PYTHON;
assert.equal(new URL(base).hostname,'127.0.0.1'); assert.ok(path.resolve(profile).startsWith(path.join(root,'qa-artifacts')+path.sep));
const out=path.join(root,'qa-artifacts/migration/composition-export'); fs.mkdirSync(out,{recursive:true});
(async()=>{
 const runtime=await(await fetch(base+'/api/local-remove/runtime')).json(); assert.equal(path.resolve(runtime.data_root),path.resolve(profile));
 const catalog=await(await fetch(base+'/api/local-remove/generation/models')).json();
 const models=catalog.models.filter(m=>m.id==='qwen').map(m=>({...m,available:true,reason:'',variants:m.variants.map(v=>({...v,available:true,reason:''}))}));
 const browser=await chromium.launch({headless:true}), context=await browser.newContext({viewport:{width:1366,height:768},acceptDownloads:true}), page=await context.newPage();
 const errors=[], blocked=[], requests=[], checks=[], timings=[], generated=[]; let passed=false, failure=null;
 await context.addInitScript(()=>{for(const key of ['local-image.hardware-guide.v1','local-image.first-ai-setup.v1','local-image.first-task.v1'])localStorage.setItem(key,'1');});
 await context.route('**/*',async route=>{
  const r=route.request(),u=new URL(r.url()); if(u.origin!==base){blocked.push(u.href);return route.abort();}
  if(u.pathname==='/api/local-remove/generation/models')return route.fulfill({json:{...catalog,models}});
  if(u.pathname==='/api/local-remove/generation/progress')return route.fulfill({json:{active:false,job_id:null}});
  if(u.pathname==='/api/local-remove/generation'&&r.method()==='POST'){
   const result=JSON.parse(execFileSync(python,[path.join(root,'tests/helpers/seed_generation_response.py'),profile,base,JSON.stringify(r.postDataJSON())],{encoding:'utf8'}).trim().split(/\r?\n/).at(-1)); generated.push(result.session.id);return route.fulfill({json:result});
  }
  if(r.method()!=='GET'&&!/^\/api\/local-remove\/(?:import$|session\/[^/]+\/(?:stack(?:\/.*)?|cutout\/refine|cutout\/white-background|save|export-project)$)/.test(u.pathname)){blocked.push(u.pathname);return route.abort();}
  return route.continue();
 });
 page.on('pageerror',e=>errors.push(e.stack));page.on('request',r=>{const u=new URL(r.url());if(u.pathname.startsWith('/api/'))requests.push({method:r.method(),path:u.pathname,query:u.search});});
 page.setDefaultTimeout(15000);
 const state=()=>page.evaluate(()=>window.LocalImageEditor.getSnapshot());
 const idle=()=>page.waitForFunction(()=>!window.LocalImageEditor.getSnapshot().busy&&!window.LocalImageReactFeatures.generation.getSnapshot().working);
 const settle=()=>page.evaluate(async()=>{await Promise.all(document.getAnimations().filter(a=>a.effect?.getComputedTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{})));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));});
 const command=(name,...args)=>page.evaluate(({name,args})=>window.LocalImageEditor.commands[name](...args),{name,args});
 async function upload(name,w,h){await idle(); const trigger=async()=>{if(await page.getByRole('button',{name:'Open image…',exact:true}).count())await page.getByRole('button',{name:'Open image…',exact:true}).click();else await page.keyboard.press('Control+o');};const [chooser]=await Promise.all([page.waitForEvent('filechooser'),trigger()]);await chooser.setFiles({name,mimeType:'image/png',buffer:imageFixture(w,h)});await page.waitForFunction(()=>!!window.LocalImageEditor.getSnapshot().document&&!window.LocalImageEditor.getSnapshot().busy);}
 async function refresh(){await page.getByRole('menuitem',{name:'View',exact:true}).click();await page.getByRole('menuitem',{name:'Refresh preview',exact:true}).click();await idle();}
 async function exportOpen(){await page.getByRole('button',{name:'Export',exact:true}).click();const d=page.getByRole('dialog',{name:'Export image',exact:true});await d.waitFor();await settle();return d;}
 try{
  await page.goto(base+'/remove');await page.waitForFunction(()=>document.body.dataset.reactReady==='true');await upload('Composition.png',320,240); const source=(await state()).document;
  await page.evaluate(async sid=>{const token=window.__LOCAL_IMAGE_BOOTSTRAP__.token,post=async(tail,body)=>{const r=await fetch('/api/local-remove/session/'+sid+tail,{method:'POST',headers:{'content-type':'application/json','x-local-remove-token':token},body:JSON.stringify(body)});if(!r.ok)throw Error(await r.text());return r.json();};await post('/stack',{revision:0});const c=document.createElement('canvas');c.width=320;c.height=240;const g=c.getContext('2d');g.fillStyle='white';g.fillRect(80,60,160,120);const result=await post('/cutout/refine',{revision:0,mask:c.toDataURL('image/png').split(',')[1],operation:'replace'});await fetch('/api/local-remove/session/'+sid+'/stack/layer/original',{method:'PATCH',headers:{'content-type':'application/json','x-local-remove-token':token},body:JSON.stringify({revision:result.revision,visible:false})});},source.id);
  await refresh();await command('setWorkspace','cutout');await idle();await page.getByRole('button',{name:'Add background',exact:true}).click();await page.getByRole('menuitem',{name:'Plain white',exact:true}).click();await idle();
  await page.locator('#stage').screenshot({path:path.join(out,'white-background-preview.png')});const uiCorner=JSON.parse(execFileSync(python,['-c','from PIL import Image;import json,sys;print(json.dumps(Image.open(sys.argv[1]).convert("RGB").getpixel((10,10))))',path.join(out,'white-background-preview.png')],{encoding:'utf8'}));assert.deepEqual(uiCorner,[255,255,255]);const white=(await state()).document;assert.deepEqual(white.layer_stack.map(l=>l.kind),['original','image','cutout']);assert.equal(white.layer_stack[1].name,'White background');checks.push('Plain white adds an undoable background below the cutout');
  const saves=()=>requests.filter(r=>r.path.endsWith('/save')).length;const before=saves();let dialog=await exportOpen();assert.equal(saves(),before,'Opening Export renders no file');await dialog.getByLabel('Filename',{exact:true}).fill('Product');await dialog.getByLabel('Scale (%)',{exact:true}).fill('50');assert.equal(await dialog.getByLabel('Width (px)',{exact:true}).inputValue(),'160');
  const [download]=await Promise.all([page.waitForEvent('download'),dialog.getByRole('button',{name:'Export',exact:true}).click()]);assert.equal(download.suggestedFilename(),'Product.png');await download.saveAs(path.join(out,'Product.png'));await idle();
  const pixels=JSON.parse(execFileSync(python,['-c','from PIL import Image;import json,sys;i=Image.open(sys.argv[1]);print(json.dumps({"size":i.size,"corner":i.convert("RGBA").getpixel((0,0))}))',path.join(out,'Product.png')],{encoding:'utf8'}));assert.deepEqual(pixels,{size:[160,120],corner:[255,255,255,255]});assert.deepEqual([(await state()).document.width,(await state()).document.height],[320,240]);checks.push('Export waits for confirmation, uses filename and scale, produces white pixels without resizing composition');
  dialog=await exportOpen();const count=saves();await dialog.getByRole('button',{name:'Cancel',exact:true}).click();await dialog.waitFor({state:'detached'});assert.equal(saves(),count);checks.push('Cancel exports nothing');
  await page.getByRole('menuitem',{name:'File',exact:true}).click();assert.equal(await page.getByRole('menuitem',{name:'Copy format',exact:true}).count(),0);await page.keyboard.press('Escape');
  await command('actualSize');await settle();await page.evaluate(()=>{window.__sharedNodes=['#photo','#viewport','.li-layers'].map(s=>document.querySelector(s));});const camera=(await state()).canvas;
  for(const workspace of ['retouch','cutout','generate']){await command('setWorkspace',workspace);await idle();await page.waitForFunction(w=>window.LocalImageEditor.getSnapshot().workspace===w,workspace);assert.equal((await state()).document.id,source.id);await page.getByRole('region',{name:'Layers',exact:true}).waitFor({state:'visible'});assert.equal(await page.evaluate(()=>window.__sharedNodes.every(n=>n&&n.isConnected)),true);assert.equal((await state()).canvas.photoZoom,camera.photoZoom);}
  await page.evaluate(()=>window.LocalImageReactFeatures.generation.setMode('refine'));await idle();await page.getByRole('region',{name:'Image generation',exact:true}).waitFor();assert.equal((await state()).document.id,source.id);assert.equal(await page.evaluate(()=>window.__sharedNodes.every(n=>n&&n.isConnected)),true);checks.push('Retouch, Cutout, Create/Edit and Refine retain the canvas, camera and Layers nodes');
  await page.evaluate(()=>{const g=window.LocalImageReactFeatures.generation;g.setDraft('draft',{prompt:'CPU fixture layer'});return g.run('draft');});await idle();let after=(await state()).document;assert.equal(after.id,source.id);assert.equal(after.layer_stack.at(-1).generated_session_id,generated[0]);assert.equal(after.layer_stack.length,white.layer_stack.length+1);checks.push('Generation adds a selected top layer to the existing composition');
  await command('setWorkspace','retouch');await idle();await page.setViewportSize({width:800,height:560});await page.evaluate(()=>window.LocalImageReactFeatures.settings.setDensity('large'));
  dialog=await exportOpen();const box=await dialog.boundingBox();assert.ok(box.x>=0&&box.y>=0&&box.x+box.width<=801&&box.y+box.height<=561);const buttons=await dialog.getByRole('button',{name:'Export',exact:true}).boundingBox();assert.ok(buttons.y+buttons.height<=561);await page.screenshot({path:path.join(out,'export-800-large.png')});await dialog.getByRole('button',{name:'Cancel',exact:true}).click();await dialog.waitFor({state:'detached'});await command('setWorkspace','generate');await idle();await page.screenshot({path:path.join(out,'shared-viewer-800-large.png')});checks.push('Large density export controls fit at 800 × 560');
  await page.setViewportSize({width:1366,height:768});await page.evaluate(()=>window.LocalImageReactFeatures.settings.setDensity('comfortable'));await command('setWorkspace','retouch');await idle();await upload('Visibility 4000.png',4000,3000);await page.getByRole('button',{name:'New retouch layer',exact:true}).click();await idle();after=(await state()).document;const layer='original';
  await command('patchLayer',layer,{visible:false});await idle();await command('patchLayer',layer,{visible:true});await idle();const start=requests.length;
  timings.push(...await page.evaluate(async layer=>{const times=[];for(let i=0;i<12;i++){const t=performance.now();await window.LocalImageEditor.commands.patchLayer(layer,{visible:i%2!==0});assertVisible();times.push(performance.now()-t);function assertVisible(){if(window.LocalImageEditor.getSnapshot().document.layer_stack.find(l=>l.id===layer).visible!==(i%2!==0))throw Error('Visibility did not commit');}}return times;},layer));
  const hot=requests.slice(start);assert.equal(hot.filter(r=>r.path.endsWith('/preview')||r.path.endsWith('/display')).length,0,'Hot visibility uses cached layer images');checks.push('4000 × 3000 visibility toggles cause no full preview or layer image reloads');
  await page.screenshot({path:path.join(out,'shared-viewer-1366.png')});assert.deepEqual(errors,[]);assert.deepEqual(blocked,[]);passed=true;
 }catch(e){failure=e.stack;await page.screenshot({path:path.join(out,'failure.png')}).catch(()=>{});throw e;}
 finally{fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({passed,failure,checks,timings,generated,requests,errors,blocked},null,2));await browser.close();}
 console.log('PASS composition/export: '+checks.length+' checks; visibility median '+[...timings].sort((a,b)=>a-b)[Math.floor(timings.length/2)].toFixed(1)+' ms');
})().catch(e=>{console.error(e);process.exitCode=1;});
