// Composed-page regression for readable Layers at narrow + Large density.
// Uses one own synthetic document, UI layer selection and wheel scrolling.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {chromium}=require('playwright'),{imageFixture}=require('./helpers/image-fixture.cjs');
const root=path.resolve(__dirname,'..'),base=process.env.LOCAL_REMOVE_TEST_URL,profile=process.env.MIGRATION_REAL_PROFILE;
assert.ok(base&&profile);assert.equal(new URL(base).hostname,'127.0.0.1');assert.ok(path.resolve(profile).startsWith(path.join(root,'qa-artifacts')+path.sep));
const output=path.join(root,'qa-artifacts/migration/narrow-large-layers'),hash=value=>crypto.createHash('sha256').update(value).digest('hex');
(async()=>{
 const runtime=await(await fetch(base+'/api/local-remove/runtime')).json();assert.equal(path.resolve(runtime.data_root),path.resolve(profile));fs.mkdirSync(output,{recursive:true});
 const sourceHash=hash(fs.readFileSync(path.join(root,'frontend/src/editor.css'))),browser=await chromium.launch({channel:'msedge',headless:true}),context=await browser.newContext({viewport:{width:800,height:560},deviceScaleFactor:1.75}),page=await context.newPage();
 const metrics=[],toggleMetrics=[],assets=[],errors=[],blocked=[],requests=[],reads=[];let passed=false,failure=null,sessionId=null,generationLayout=null;
 await context.route('**/*',route=>{const request=route.request(),url=new URL(request.url()),write=request.method()==='POST'&&(/^\/api\/local-remove\/import$/.test(url.pathname)||/^\/api\/local-remove\/session\/[^/]+\/stack(?:\/layers)?$/.test(url.pathname));if(url.origin!==base||request.method()!=='GET'&&!write){blocked.push({method:request.method(),path:url.pathname});return route.abort('blockedbyclient');}return route.continue();});
 await context.addInitScript(()=>{for(const key of ['local-image.hardware-guide.v1','local-image.first-ai-setup.v1','local-image.first-task.v1'])localStorage.setItem(key,'1');window.__layersCsp=[];document.addEventListener('securitypolicyviolation',event=>window.__layersCsp.push(event.violatedDirective));});
 page.on('pageerror',error=>errors.push(error.stack));page.on('request',request=>{const url=new URL(request.url());if(url.pathname.startsWith('/api/'))requests.push({method:request.method(),path:url.pathname});});page.on('response',response=>{const url=new URL(response.url());if(url.pathname.startsWith('/frontend-assets/'))reads.push(response.body().then(body=>assets.push({path:url.pathname,status:response.status(),sha256:hash(body)})));});
 const settle=()=>page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
 const inspector=page.locator('#inspector-root'),rows=page.locator('.li-layer-row');
 const canvasView=()=>page.evaluate(()=>{const rect=selector=>{const node=document.querySelector(selector),box=node.getBoundingClientRect();return{height:box.height,width:box.width,hidden:node.hidden,display:getComputedStyle(node).display};};const state=window.LocalImageEditor.getSnapshot();return{width:innerWidth,height:innerHeight,layout:rect('#editor-layout'),canvas:rect('#canvas-region'),viewport:rect('#viewport'),photo:rect('#photo'),inspector:rect('#inspector-root'),generation:rect('#react-generation-root'),documentId:state.document.id,revision:state.document.revision,hasSelection:state.canvas.hasSelection,mask:document.querySelector('#selection').toDataURL()};});
 const geometry=()=>page.evaluate(()=>{const rect=element=>{const value=element.getBoundingClientRect();return{left:value.left,right:value.right,top:value.top,bottom:value.bottom,width:value.width,height:value.height,scrollHeight:element.scrollHeight,scrollTop:element.scrollTop}};const root=document.querySelector('#inspector-root'),list=root.querySelector('.li-layer-list'),row=list.querySelector('.li-layer-row'),name=row.querySelector('.li-layer-name'),input=root.querySelector('input[aria-label="Layer opacity percent"]');const box=input.getBoundingClientRect(),hit=document.elementFromPoint((box.left+box.right)/2,(box.top+box.bottom)/2);return{width:innerWidth,height:innerHeight,dpr:devicePixelRatio,density:document.documentElement.dataset.uiDensity,layout:rect(document.querySelector('#editor-layout')),inspector:rect(root),list:rect(list),row:rect(row),name:rect(name),font:parseFloat(getComputedStyle(name).fontSize),opacity:rect(input),opacityHit:hit===input||!!hit?.closest('.li-properties'),selected:window.LocalImageEditor.getSnapshot().selectedLayerId};});
 try{
  await page.goto(base+'/remove');await page.waitForFunction(()=>document.body.dataset.reactReady==='true');
  const [chooser]=await Promise.all([page.waitForEvent('filechooser'),page.getByRole('button',{name:'Open image…',exact:true}).click()]);await chooser.setFiles({name:'Narrow Layers fixture.png',mimeType:'image/png',buffer:imageFixture(320,240)});await page.waitForFunction(()=>!!window.LocalImageEditor.getSnapshot().document&&!window.LocalImageEditor.getSnapshot().busy);
  sessionId=await page.evaluate(()=>window.LocalImageEditor.getSnapshot().document.id);await page.getByRole('button',{name:'New retouch layer',exact:true}).click();await page.waitForFunction(()=>window.LocalImageEditor.getSnapshot().document.layer_stack.length===2&&!window.LocalImageEditor.getSnapshot().busy);
  for(const [density,width,height]of [['comfortable',800,560],['large',800,560],['large',800,569],['large',767,396],['comfortable',1366,768]]){
   await page.setViewportSize({width,height});await page.getByRole('button',{name:'Settings',exact:true}).click();const settings=page.getByRole('dialog',{name:'Settings',exact:true});await settings.getByRole('combobox',{name:'Interface size',exact:true}).selectOption(density);await settings.getByRole('button',{name:'Done',exact:true}).click();await settings.waitFor({state:'detached'});await settle();
   await inspector.evaluate(root=>{root.scrollTop=0;root.querySelector('.li-layer-list').scrollTop=0;});await settle();const initial=await geometry();
   assert.equal(initial.font,density==='large'?28:14);assert.ok(initial.list.height>=initial.row.height,'Layer list retains at least one complete row height');
   assert.ok(initial.inspector.top>=initial.layout.top-1&&initial.inspector.bottom<=initial.layout.bottom+1,'Inspector remains within the editor layout at the actual client height');
   if(height>=560)assert.ok(initial.name.top>=Math.max(initial.list.top,initial.inspector.top)-1&&initial.name.bottom<=Math.min(initial.list.bottom,initial.inspector.bottom)+1,'First layer name is readable immediately in the inspector');
   const firstId=await rows.first().getAttribute('data-layer-id');await rows.last().locator('.li-layer-label').click();assert.notEqual(await page.evaluate(()=>window.LocalImageEditor.getSnapshot().selectedLayerId),firstId);
   await rows.first().locator('.li-layer-label').click();await page.waitForFunction(id=>window.LocalImageEditor.getSnapshot().selectedLayerId===id,firstId);
   const selectedView=await geometry();assert.ok(selectedView.name.top>=Math.max(selectedView.list.top,selectedView.inspector.top)-1&&selectedView.name.bottom<=Math.min(selectedView.list.bottom,selectedView.inspector.bottom)+1,'Selected first layer name is visible through both scroll regions');
   await page.screenshot({path:path.join(output,`layers-${density}-${width}-${height}.png`),animations:'disabled'});
   let final=await geometry();
   for(let attempt=0;attempt<5&&!(final.opacity.top>=final.inspector.top&&final.opacity.bottom<=final.inspector.bottom&&final.opacityHit);attempt++){
    const bounds=await inspector.boundingBox(),delta=final.opacity.top<final.inspector.top?-Math.min(120,final.inspector.top-final.opacity.top+8):Math.min(120,final.opacity.bottom-final.inspector.bottom+8);await page.mouse.move(bounds.x+bounds.width-24,bounds.y+bounds.height-12);await page.mouse.wheel(0,delta);await page.waitForTimeout(100);final=await geometry();
   }
   assert.ok(final.opacity.top>=Math.max(final.inspector.top,final.layout.top)-1&&final.opacity.bottom<=Math.min(final.inspector.bottom,final.layout.bottom)+1&&final.opacityHit,'Opacity is fully reachable through the editor clip and hit-testable after wheel scrolling');
   if(density==='large'){assert.ok(final.inspector.scrollTop>0,'The narrow Large inspector owns vertical scrolling');assert.ok(initial.row.height>=72,'Large row sizing is preserved');}
   metrics.push({density,width,height,initial,afterScroll:final});await page.screenshot({path:path.join(output,`properties-${density}-${width}-${height}.png`),animations:'disabled'});
  }
  for(const [width,height]of [[767,396],[800,560]]){
   await page.setViewportSize({width,height});await page.getByRole('button',{name:'Settings',exact:true}).click();const settings=page.getByRole('dialog',{name:'Settings',exact:true});await settings.getByRole('combobox',{name:'Interface size',exact:true}).selectOption('large');await settings.getByRole('button',{name:'Done',exact:true}).click();await settings.waitFor({state:'detached'});
   const toggle=page.getByRole('button',{name:'Inspector',exact:true});if(await toggle.getAttribute('aria-pressed')==='true')await toggle.click();
   await page.getByRole('button',{name:'Rectangle selection (R)',exact:true}).click();
   const bounds=await page.locator('#photo').evaluate(async node=>{let prior='',stable=0;for(let frame=0;frame<12;frame++){await new Promise(requestAnimationFrame);const box=node.getBoundingClientRect().toJSON(),key=JSON.stringify(box);stable=key===prior?stable+1:0;prior=key;if(stable>=2)return box;}throw Error('Canvas did not settle before selection');});
   await page.mouse.move(bounds.x+bounds.width*.2,bounds.y+bounds.height*.2);await page.mouse.down();await page.mouse.move(bounds.x+bounds.width*.6,bounds.y+bounds.height*.6,{steps:4});await page.mouse.up();await page.waitForFunction(()=>window.LocalImageEditor.getSnapshot().canvas.hasSelection);
   const preserved=await canvasView();await toggle.click();await settle();const shown=await canvasView();
   assert.ok(Math.abs(shown.canvas.height-shown.layout.height*.52)<1,'Visible inspector retains the52/48 layout');
   await toggle.click();await settle();const hidden=await canvasView();assert.ok(hidden.inspector.hidden&&hidden.generation.hidden);
   assert.ok(Math.abs(hidden.canvas.height-hidden.layout.height)<1,'Both hidden side panels let canvas reclaim full available height');
   assert.ok(hidden.viewport.height>shown.viewport.height+20&&hidden.photo.height>shown.photo.height,'Hiding Inspector grows viewport and fitted preview');
   await toggle.click();await settle();const restored=await canvasView();assert.ok(Math.abs(restored.canvas.height-shown.canvas.height)<1,'Toggling back restores the split height');
   for(const value of [shown,hidden,restored]){assert.equal(value.documentId,preserved.documentId);assert.equal(value.revision,preserved.revision);assert.equal(value.hasSelection,true);assert.equal(value.mask,preserved.mask,'Inspector layout changes retain actual selection pixels');}
   const safe=value=>{const {mask,...rest}=value;return{...rest,maskSha256:hash(mask)};};toggleMetrics.push({width,height,shown:safe(shown),hidden:safe(hidden),restored:safe(restored)});
   await toggle.click();await settle();await page.screenshot({path:path.join(output,`inspector-hidden-${width}-${height}.png`),animations:'disabled'});await toggle.click();await settle();
  }
  const beforeGenerate=await canvasView();await page.locator('#workspace-generate').click();await page.waitForFunction(()=>window.LocalImageEditor.getSnapshot().workspace==='generate');await settle();const generate=await canvasView();
  assert.equal(generate.generation.hidden,false);assert.ok(Math.abs(generate.canvas.height-generate.layout.height*.52)<1,'Visible generation pane keeps the existing split');
  await page.getByRole('region',{name:'Image generation',exact:true}).getByRole('tab',{name:'Refine',exact:true}).click();await settle();const refine=await canvasView();assert.equal(refine.canvas.display,'none');assert.equal(refine.generation.hidden,false);assert.ok(Math.abs(refine.generation.height-refine.layout.height)<1,'Visible Refine remains full-height');
  await page.locator('#workspace-retouch').click();await settle();const returned=await canvasView();assert.equal(returned.documentId,beforeGenerate.documentId);assert.equal(returned.mask,beforeGenerate.mask);assert.equal(returned.hasSelection,true);
  const safe=value=>{const {mask,...rest}=value;return{...rest,maskSha256:hash(mask)};};generationLayout={generate:safe(generate),refine:safe(refine),returned:safe(returned)};
  await Promise.all(reads);assert.equal(hash(fs.readFileSync(path.join(root,'frontend/src/editor.css'))),sourceHash);assert.deepEqual(errors,[]);assert.deepEqual(blocked,[]);assert.deepEqual(await page.evaluate(()=>window.__layersCsp),[]);passed=true;
 }catch(error){failure=error.stack;await page.screenshot({path:path.join(output,'failure.png'),animations:'disabled'}).catch(()=>{});throw error;}
 finally{await Promise.allSettled(reads);fs.writeFileSync(path.join(output,'results.json'),JSON.stringify({passed,failure,runtime,sessionId,sourceHash,metrics,toggleMetrics,generationLayout,assets,errors,blocked,requests,evidence:'Actual source backend UI at DPR1.75; layer selection and wheel reachability, Inspector toggle with real selection pixels, visible Generate/Refine flow; no native/provider/model actions'},null,2));await browser.close();}
 console.log(`PASS narrow Layers: ${metrics.length} layouts, ${toggleMetrics.length} Inspector roundtrips, Generate/Refine flow; ${output}`);
})().catch(error=>{console.error(error);process.exitCode=1;});
