// Real full React Batch acceptance. No queue/image API is mocked.
// Does not start services, install, run model inference, download models or contact providers.
const assert = require('node:assert/strict'), fs = require('node:fs'), path = require('node:path'), crypto = require('node:crypto');
const {execFileSync} = require('node:child_process');
const {chromium} = require('playwright');
const {imageFixture} = require('./helpers/image-fixture.cjs');
const root = path.resolve(__dirname, '..'), base = process.env.LOCAL_REMOVE_TEST_URL, profile = process.env.MIGRATION_REAL_PROFILE;
assert.ok(base && profile, 'Specify isolated backend URL and expected profile');
const origin = new URL(base); assert.equal(origin.hostname, '127.0.0.1'); assert.equal(origin.protocol, 'http:');
const insideQa = file => path.resolve(file).toLowerCase().startsWith(path.join(root, 'qa-artifacts').toLowerCase() + path.sep);
assert.ok(insideQa(profile));
const out = path.resolve(process.env.MIGRATION_REAL_OUTPUT || path.join(root, 'qa-artifacts/migration/full-batch')); assert.ok(insideQa(out)); fs.mkdirSync(out, {recursive: true});
const backendKind = process.env.MIGRATION_BACKEND_KIND || 'source'; assert.ok(['source', 'packaged'].includes(backendKind));
const hash = value => crypto.createHash('sha256').update(value).digest('hex');
const evidence = file => ({path: path.relative(root, file).replaceAll('\\', '/'), bytes: fs.statSync(file).size, sha256: hash(fs.readFileSync(file))});
const files = dir => fs.readdirSync(dir, {withFileTypes: true}).flatMap(entry => entry.isDirectory() ? files(path.join(dir, entry.name)) : [path.join(dir, entry.name)]);
const sources = [...files(path.join(root, 'frontend/src')), ...files(path.join(root, 'backend/frontend_dist')), ...fs.readdirSync(path.join(root, 'backend')).filter(name => /\.(py|html)$/.test(name)).map(name => path.join(root, 'backend', name)), path.join(root, 'backend/frontend/react.html'), path.join(root, 'frontend/package-lock.json'), __filename];
const sourceInventory = sources.map(evidence), fingerprint = () => hash(sources.map(file => hash(fs.readFileSync(file))).join(':')), beforeFingerprint = fingerprint();
const baseRevision = execFileSync('git', ['rev-parse', 'HEAD'], {cwd: root, encoding: 'utf8'}).trim();
const workingTreeStatus = execFileSync('git', ['status', '--porcelain=v1'], {cwd: root, encoding: 'utf8'}).trim();
function zipEntries(bytes) {
  const end = bytes.lastIndexOf(Buffer.from('504b0506', 'hex')); assert.ok(end >= 0); let offset = bytes.readUInt32LE(end + 16); const result = {};
  for (let count = 0; count < bytes.readUInt16LE(end + 10); count++) {
    assert.equal(bytes.readUInt32LE(offset), 0x02014b50); assert.equal(bytes.readUInt16LE(offset + 10), 0, 'ZIP stores rendered bytes unchanged');
    const size = bytes.readUInt32LE(offset + 24), length = bytes.readUInt16LE(offset + 28), extra = bytes.readUInt16LE(offset + 30), comment = bytes.readUInt16LE(offset + 32), local = bytes.readUInt32LE(offset + 42);
    const name = bytes.subarray(offset + 46, offset + 46 + length).toString('utf8'), data = local + 30 + bytes.readUInt16LE(local + 26) + bytes.readUInt16LE(local + 28);
    assert.ok(!(name in result), 'No duplicate archive entry'); result[name] = bytes.subarray(data, data + size); offset += 46 + length + extra + comment;
  }
  return result;
}
async function main() {
  const runtimeResponse = await fetch(base + '/api/local-remove/runtime'); assert.equal(runtimeResponse.status, 200);
  const runtime = await runtimeResponse.json(); assert.equal(path.resolve(runtime.data_root).toLowerCase(), path.resolve(profile).toLowerCase());
  const browser = await chromium.launch({channel: 'msedge', headless: true}), context = await browser.newContext({viewport: {width: 1366, height: 768}, acceptDownloads: true});
  const page = await context.newPage(), startedAt = new Date().toISOString();
  const checks = [], errors = [], violations = [], requests = [], responses = [], blocked = [], snapshots = [], outputs = [], screenshots = [], ownedQueues = [], loadedAssetHashes = [], assetReads = [];
  let passed = false, failure = null, pageHash = null, csp = null;
  const record = text => {checks.push(text); console.log('PASS: ' + text);};
  const state = () => page.evaluate(() => window.LocalImageEditor.getSnapshot());
  const idle = () => page.waitForFunction(() => window.LocalImageEditor?.getSnapshot().document && !window.LocalImageEditor.getSnapshot().busy);
  const menu = async (group, label) => {await page.getByRole('menuitem', {name: group, exact: true}).click(); await page.getByRole('menuitem', {name: new RegExp('^' + label + '(?:\\s+Ctrl\\+.*)?$')}).click();};
  const choose = async value => {const [chooser] = await Promise.all([page.waitForEvent('filechooser'), menu('File', 'Open images…')]); await chooser.setFiles(value); await idle();};
  const open = async () => {await page.getByRole('button', {name: 'Batch', exact: true}).click(); await page.getByRole('dialog', {name: 'Batch treatment and export'}).waitFor(); await page.waitForFunction(() => !document.querySelector('#batch-treatment').disabled);};
  const close = async () => {await page.locator('#batch-close').click(); await page.getByRole('dialog', {name: 'Batch treatment and export'}).waitFor({state: 'hidden'});};
  const ready = () => page.waitForFunction(() => !document.querySelector('#batch-export').disabled && !document.querySelector('#batch-cancel'), null, {timeout: 60000});
  const prepare = async () => {
    const [response] = await Promise.all([page.waitForResponse(response => new URL(response.url()).pathname === '/api/local-remove/batch/jobs' && response.request().method() === 'POST'), page.locator('#batch-create').click()]);
    assert.equal(response.status(), 200); const value = await response.json(); assert.equal(value.prepare_cutouts, false); ownedQueues.push(value.id); return value.id;
  };
  const queue = async (id, name) => {const value = await page.evaluate(async id => {const response = await fetch('/api/local-remove/batch/jobs/' + encodeURIComponent(id)); if (!response.ok) throw Error('Queue read ' + response.status); return response.json();}, id); snapshots.push({name, queue: value}); return value;};
  const review = async id => {if (!(await page.locator('.li-batch-history').evaluate(node => node.open))) await page.locator('.li-batch-history > summary').click(); await page.locator('#batch-history-select').selectOption(id); await page.locator('#batch-load-queue').click(); await page.waitForFunction(id => window.LocalImageReactFeatures.batch.getSnapshot().active?.id === id && !window.LocalImageReactFeatures.batch.getSnapshot().working, id);};
  const downloadZip = async name => {await page.locator('#batch-download').waitFor({state: 'visible', timeout: 60000}); const [download] = await Promise.all([page.waitForEvent('download'), page.locator('#batch-download').click()]); const file = path.join(out, name); await download.saveAs(file); assert.equal(await download.failure(), null); outputs.push(evidence(file)); return zipEntries(fs.readFileSync(file));};
  const rectangle = async () => {
    await page.getByRole('button', {name: 'Rectangle selection (R)', exact: true}).click();
    const box = await page.locator('#photo').evaluate(async node => {let previous = '', stable = 0; for (let i = 0; i < 12; i++) {await new Promise(requestAnimationFrame); const rect = node.getBoundingClientRect().toJSON(), key = JSON.stringify([rect.x, rect.y, rect.width, rect.height]); stable = key === previous ? stable + 1 : 0; previous = key; if (stable >= 2) return rect;} throw Error('Canvas did not settle');});
    await page.mouse.move(box.x + box.width * .1, box.y + box.height * .12); await page.mouse.down(); await page.mouse.move(box.x + box.width * .4, box.y + box.height * .44, {steps: 6}); await page.mouse.up();
    await page.waitForFunction(() => window.LocalImageEditor.getSnapshot().canvas.hasSelection);
  };
  const density = async value => {await page.getByRole('button', {name: 'Settings', exact: true}).click(); await page.getByRole('combobox', {name: 'Interface size', exact: true}).selectOption(value); await page.getByRole('button', {name: 'Done', exact: true}).click();};
  const shot = async name => {const file = path.join(out, name); await page.screenshot({path: file, animations: 'disabled'}); screenshots.push(evidence(file));};
  const readableBatch = async () => {
    const result = await page.locator('#batch-dialog').evaluate(dialog => ({
      selects: [...dialog.querySelectorAll('.li-batch-settings select')].map(select => {const style = getComputedStyle(select); return {id: select.id, height: select.getBoundingClientRect().height, clientHeight: select.clientHeight, lineHeight: parseFloat(style.lineHeight), fontSize: parseFloat(style.fontSize), padding: parseFloat(style.paddingTop) + parseFloat(style.paddingBottom)};}),
      headers: [...dialog.querySelectorAll('th')].map(cell => {const box = cell.getBoundingClientRect(), walker = document.createTreeWalker(cell, NodeFilter.SHOW_TEXT), ranges = []; while (walker.nextNode()) {if (!walker.currentNode.textContent.trim()) continue; const range = document.createRange(); range.selectNodeContents(walker.currentNode); const text = range.getBoundingClientRect(); ranges.push({left: text.left, right: text.right});} return {text: cell.textContent, left: box.left, right: box.right, ranges};}),
    }));
    for (const select of result.selects) assert.ok(select.clientHeight - select.padding >= Math.min(select.lineHeight || Infinity, select.fontSize * 1.2) - 1, 'Select text has sufficient height: ' + JSON.stringify(select));
    for (const header of result.headers) assert.ok(header.ranges.every(text => text.left >= header.left - 1 && text.right <= header.right + 1), 'Table heading stays inside its own column: ' + JSON.stringify(header));
    return result;
  };
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => {let payload; if (request.headers()['content-type']?.includes('application/json')) {try {payload = JSON.parse(request.postData() || '{}'); if (payload.mask) payload.mask = '[' + payload.mask.length + ' base64 characters]';} catch {}} requests.push({method: request.method(), path: new URL(request.url()).pathname, ...(payload ? {payload} : {})});});
  page.on('response', response => {const url = new URL(response.url()); responses.push({path: url.pathname, method: response.request().method(), status: response.status()}); if (url.pathname.startsWith('/frontend-assets/')) assetReads.push(response.body().then(bytes => loadedAssetHashes.push({path: url.pathname, bytes: bytes.length, sha256: hash(bytes), status: response.status()})));});
  await context.route('**/*', route => {
    const request = route.request(), url = new URL(request.url()); let forbidden = url.origin !== origin.origin && !['data:', 'blob:'].includes(url.protocol);
    if (request.method() !== 'GET') {
      forbidden ||= /^\/api\/local-remove\/(?:generation(?:\/|$)|generator|qwen\/download|setup|loras\/download|stock\/import)/.test(url.pathname) || /\/cutout$|\/cutout\/generate-background$|\/remove$/.test(url.pathname);
      if (url.pathname === '/api/local-remove/batch/jobs') {try {forbidden ||= JSON.parse(request.postData() || '{}').prepare_cutouts === true;} catch {forbidden = true;}}
    }
    if (forbidden) {blocked.push({url: url.href, method: request.method()}); return route.abort('blockedbyclient');} return route.continue();
  });
  await context.addInitScript(() => {for (const key of ['local-image.hardware-guide.v1', 'local-image.first-ai-setup.v1', 'local-image.first-task.v1']) localStorage.setItem(key, '1'); window.__batchCsp = []; document.addEventListener('securitypolicyviolation', event => window.__batchCsp.push({directive: event.violatedDirective, uri: event.blockedURI}));});
  try {
    const response = await page.goto(base + '/remove'); pageHash = hash(await response.body()); csp = response.headers()['content-security-policy']; await page.waitForFunction(() => document.body.dataset.reactReady === 'true' && !!window.LocalImageEditor);
    assert.doesNotMatch(csp, /unsafe-inline|unsafe-eval/); assert.equal(await page.evaluate(() => typeof session), 'undefined'); assert.equal(await page.locator('dialog#batch-dialog').count(), 0);
    await choose([{name: 'Blue test.png', mimeType: 'image/png', buffer: imageFixture(320, 240)}, {name: 'Red test.png', mimeType: 'image/png', buffer: imageFixture(256, 192)}]);
    assert.equal((await state()).collection.entries.length, 2); const canvas = await page.locator('#photo').elementHandle();
    await open(); assert.equal(await page.locator('#batch-rows tr').count(), 2); await page.locator('#batch-format').selectOption('png'); const firstQueue = await prepare(); await ready();
    assert.equal(await page.locator('#batch-format').isDisabled(), true); assert.equal(await page.locator('#batch-treatment').isDisabled(), true); assert.ok((await state()).collection.entries.every(item => item.session_id));
    const reviewed = await queue(firstQueue, 'reviewed-png'); assert.equal(reviewed.phase, 'review'); assert.ok(reviewed.items.every(item => item.status === 'ready')); record('Owned browser upload lazily resolves both images; durable reviewed settings are immutable');
    await page.getByRole('checkbox', {name: 'Select Blue test.png', exact: true}).uncheck(); await page.locator('#batch-export').click();
    const zip = await downloadZip('selected-real-export.zip'), images = Object.keys(zip).filter(name => name.endsWith('.png')); assert.deepEqual(images, ['Red test-local-image.png']); assert.equal(zip[images[0]].subarray(0, 8).toString('hex'), '89504e470d0a1a0a'); assert.equal(zip[images[0]].readUInt32BE(16), 256); assert.equal(zip[images[0]].readUInt32BE(20), 192); record('Selected-only export creates an actual PNG ZIP with the expected dimensions');
    await page.locator('#batch-new-queue').click(); await page.locator('#batch-format').selectOption('tif'); const tifQueue = await prepare(); await ready(); await page.locator('#batch-export').click(); const tif = await downloadZip('new-format-real-export.zip'); assert.equal(Object.keys(tif).filter(name => /\.tif$/.test(name)).length, 1); assert.equal((await queue(tifQueue, 'exported-tiff')).format, 'tif'); record('Changing format creates a separate reviewed queue and real TIFF output');
    await close(); await rectangle(); const pending = await page.locator('#selection').evaluate(node => node.toDataURL()), pendingRevision = (await state()).document.revision;
    await open(); assert.equal(await page.locator('#batch-create').isDisabled(), true); await page.getByRole('checkbox', {name: 'Use applied pixels only; keep pending selections', exact: true}).check(); await prepare(); await ready(); assert.equal(await page.locator('#selection').evaluate(node => node.toDataURL()), pending); assert.equal((await state()).document.revision, pendingRevision); await page.locator('#batch-return-apply').click(); await page.getByRole('dialog', {name: 'Batch treatment and export'}).waitFor({state: 'hidden'}); assert.equal(await page.locator('#selection').evaluate(node => node.toDataURL()), pending); record('Real pointer selection requires explicit applied-pixel consent and survives preparation and return');
    await menu('Select', 'Clear selection'); await page.getByRole('button', {name: 'Layer commands', exact: true}).click(); await page.getByRole('menuitem', {name: 'Add editable mask', exact: true}).click(); await idle(); await rectangle(); const beforeErase = (await state()).document.revision; await page.getByRole('button', {name: 'Erase selection', exact: true}).click(); await page.waitForFunction(revision => {const s = window.LocalImageEditor.getSnapshot(); return !s.busy && s.document.revision > revision && !s.canvas.hasSelection;}, beforeErase);
    const editorBefore = (await state()).document; await open(); await page.locator('#batch-format').selectOption('png'); const maskQueue = await prepare(); await ready(); assert.equal(await page.locator('#batch-rows .li-batch-error').count(), 0); assert.ok((await queue(maskQueue, 'detached-modern-stack')).items.every(item => item.status === 'ready')); assert.equal((await state()).document.revision, editorBefore.revision); record('Actual editable cutout stack sources and masks survive detached batch preparation without changing the document');
    await page.getByRole('button', {name: 'Inspect Blue test.png at full size', exact: true}).click(); await page.locator('#batch-inspect-image').evaluate(image => image.decode()); assert.equal(await page.locator('#batch-inspect-image').evaluate(image => image.naturalWidth), 320); await page.locator('#batch-inspect-zoom').selectOption('200'); assert.equal(await page.locator('#batch-inspect-image').evaluate(image => parseFloat(image.style.width)), 640); await page.locator('#batch-inspect-original').click(); assert.equal(await page.locator('#batch-inspect-original').getAttribute('aria-pressed'), 'true'); assert.match(await page.locator('#batch-inspect-image').getAttribute('alt'), /original/); await page.locator('#batch-inspect-back').click(); record('Full-size treatment/original inspection and 200% image zoom use actual detached preview bytes');
    for (const [width, height] of [[800, 560], [1366, 768], [1920, 1080]]) {await page.setViewportSize({width, height}); await shot(`batch-${width}x${height}-comfortable.png`); const box = await page.locator('#batch-dialog').boundingBox(); assert.ok(box.x >= 0 && box.x + box.width <= width + 1); assert.equal(await page.locator('#batch-dialog').evaluate(node => node.scrollWidth <= node.clientWidth + 1), true); snapshots.push({name: `comfortable-${width}-readability`, geometry: await readableBatch()});}
    await close(); await page.setViewportSize({width: 1366, height: 768}); await density('large'); await open(); await review(maskQueue); await page.locator('.li-batch-settings').scrollIntoViewIfNeeded(); await shot('batch-1366x768-large.png'); assert.equal(await page.locator('#batch-dialog').evaluate(node => node.scrollWidth <= node.clientWidth + 1), true); snapshots.push({name: 'large-readability', geometry: await readableBatch()}); await close(); await density('comfortable'); record('Batch text and table headings fit their controls at 800, 1366 and 1920 widths and the real Large interface setting');
    await open(); await review(maskQueue); await page.locator('#batch-clear-queue').click(); await page.locator('#batch-confirm-yes').click(); await page.waitForFunction(() => document.querySelector('#batch-status').textContent.includes('Queue cache cleared')); assert.equal((await state()).document.id, editorBefore.id); assert.equal((await state()).document.revision, editorBefore.revision); assert.equal(await canvas.evaluate(node => node === document.querySelector('#photo')), true); await close(); record('Explicit queue cache removal preserves the active document revision and persistent canvas node');
    const large = imageFixture(2048, 1536); await choose(Array.from({length: 8}, (_, index) => ({name: `Queue ${String(index + 1).padStart(2, '0')}.png`, mimeType: 'image/png', buffer: large})));
    await open(); await page.locator('#batch-treatment').selectOption(''); await page.locator('#batch-format').selectOption('png'); const resumable = await prepare(); await page.locator('#batch-cancel').click(); await page.locator('#batch-resume').waitFor({state: 'visible', timeout: 60000}); const paused = await queue(resumable, 'paused-prepare'); assert.equal(paused.phase, 'paused'); assert.equal(paused.running, false); assert.ok(paused.items.some(item => item.status === 'pending')); const completedBefore = paused.items.filter(item => item.status === 'ready').map(item => item.id);
    await close(); await open(); await review(resumable); await page.locator('#batch-resume').click(); await ready(); const resumed = await queue(resumable, 'resumed-prepare'); assert.ok(resumed.items.every(item => item.status === 'ready')); assert.ok(completedBefore.every(id => resumed.items.some(item => item.id === id && item.status === 'ready'))); record('Cancellation persists a real paused prepare queue; reopening and explicit Resume retain completed item identities');
    await page.locator('#batch-export').click();
    // Observe a real published output before cancelling. No backend delay or
    // response substitution: the remaining real CPU images provide the window.
    const deadline = Date.now() + 30000; let published;
    do {published = await queue(resumable, 'export-progress-observation'); if (published.running && published.items.some(item => item.status === 'exported')) break; assert.ok(published.running && Date.now() < deadline, 'Observe an already published output while further exports remain'); await new Promise(resolve => setTimeout(resolve, 50));} while (true);
    await page.locator('#batch-cancel').click(); await page.locator('#batch-resume').waitFor({state: 'visible', timeout: 60000}); const pausedExport = await queue(resumable, 'paused-export'); assert.equal(pausedExport.phase, 'paused'); assert.ok(pausedExport.items.some(item => item.status === 'ready')); const exportedBefore = pausedExport.items.filter(item => item.status === 'exported').map(item => item.output_name); assert.ok(exportedBefore.length > 0, 'Cancellation must exercise retention of already published outputs');
    await page.locator('#batch-resume').click(); const resumedZip = await downloadZip('resumed-real-export.zip'), exported = await queue(resumable, 'resumed-export'); assert.ok(exported.items.every(item => item.status === 'exported')); const resumedNames = Object.keys(resumedZip).filter(name => name.endsWith('.png')); assert.equal(resumedNames.length, 8); assert.equal(new Set(resumedNames).size, 8); assert.ok(exportedBefore.every(name => resumedNames.includes(name))); assert.equal(requests.filter(item => item.method === 'POST' && item.path === `/api/local-remove/batch/jobs/${resumable}/cancel`).length, 2); assert.equal(requests.filter(item => item.method === 'POST' && item.path === `/api/local-remove/batch/jobs/${resumable}/resume`).length, 2); record('Actual export cancellation and explicit Resume retain completed names and produce eight unique image outputs');
    violations.push(...await page.evaluate(() => window.__batchCsp)); await Promise.all(assetReads); assert.deepEqual(errors, []); assert.deepEqual(violations, []); assert.deepEqual(blocked, []); assert.equal(fingerprint(), beforeFingerprint, 'Application, test and bundle source remained unchanged during acceptance'); passed = true;
  } catch (error) {failure = error.stack; await shot('failure.png').catch(() => {}); throw error;}
  finally {
    await Promise.allSettled(assetReads); fs.writeFileSync(path.join(out, 'results.json'), JSON.stringify({passed, failure, startedAt, finishedAt: new Date().toISOString(), baseRevision, workingTreeStatus, sourceInventory, sourceUnchanged: fingerprint() === beforeFingerprint, base, expectedProfile: profile, command: process.argv, browser: browser.version(), node: process.version, backendKind, runtime, checks, errors, violations, blocked, requests, responses, snapshots, ownedQueues, outputs, screenshots, pageHash, csp, loadedAssetHashes, transport: 'Actual isolated ' + backendKind + ' Python backend through installed headless Edge. No API mocks, model inference, model downloads or live provider requests.', limits: 'Browser ZIP downloads; native folder/dialog success is not tested. Paused queues are reopened through the UI without a backend process restart.'}, null, 2)); await browser.close();
  }
  console.log(`PASS full React Batch: ${checks.length} real integration groups; ${out}`);
}
main().catch(error => {console.error(error); process.exitCode = 1;});
