// Real composed Assets page. Stock provider transport is controlled; local
// folder/library pixels and their backend mutations are actual owned fixtures.
// Native registration HTTP is exercised; native picker UI is not certified.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {execFileSync}=require('node:child_process'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),base=process.env.LOCAL_REMOVE_TEST_URL,profile=process.env.MIGRATION_REAL_PROFILE;
assert.ok(base&&profile);assert.equal(new URL(base).hostname,'127.0.0.1');assert.ok(path.resolve(profile).startsWith(path.join(root,'qa-artifacts')+path.sep));
const out=path.join(root,'qa-artifacts/migration/full-assets');fs.mkdirSync(out,{recursive:true});
if(fs.existsSync(path.join(out,'results.json'))){const archive=path.join(out,'report-history'),stamp=Date.now();fs.mkdirSync(archive,{recursive:true});fs.copyFileSync(path.join(out,'results.json'),path.join(archive,`results-${stamp}.json`));if(fs.existsSync(path.join(out,'failure.png')))fs.copyFileSync(path.join(out,'failure.png'),path.join(archive,`failure-${stamp}.png`));}
const hash=buffer=>crypto.createHash('sha256').update(buffer).digest('hex');
(async()=>{
 const runtime=await(await fetch(base+'/api/local-remove/runtime')).json();assert.equal(path.resolve(runtime.data_root),path.resolve(profile));
 const fixture=JSON.parse(execFileSync(path.join(root,'.venv/Scripts/python.exe'),[path.join(root,'tests/helpers/seed_assets_fixture.py'),profile,base],{encoding:'utf8',env:{...process.env,PYTHONIOENCODING:'utf-8'}}).trim().split(/\r?\n/).at(-1));
 const secret=fs.readFileSync(path.join(profile,'state/launcher.key'),'utf8').trim();
 const registration=await fetch(base+'/api/local-remove/backgrounds/register-folder',{method:'POST',headers:{'Content-Type':'application/json','x-local-launcher':secret},body:JSON.stringify({path:fixture.backgroundDirectory})});assert.equal(registration.status,200);const folder=await registration.json();
 const browser=await chromium.launch({channel:'msedge',headless:true}),context=await browser.newContext({viewport:{width:1366,height:768}}),page=await context.newPage();
 const errors=[],requests=[],checks=[],blocked=[],shots=[],assetReads=[],servedAssets=[];let passed=false,failure=null,stockImports=0,stockError=false,connection=false,htmlHash=null,csp=null,cspViolations=[];
 const stock={id:'a'.repeat(32),provider:'openverse',title:'Controlled ocean',creator:'Fixture photographer',creator_url:fixture.attribution.creator_url,source_url:fixture.attribution.source_url,license:fixture.attribution.license,license_url:fixture.attribution.license_url,attribution:fixture.attribution.attribution,thumbnail_url:'/qa/assets-stock.png',width:256,height:256};
 await context.route('**/*',async route=>{
  const request=route.request(),url=new URL(request.url());if(url.origin!==new URL(base).origin){blocked.push(url.href);return route.abort('blockedbyclient');}
  if(url.pathname==='/qa/assets-stock.png')return route.fulfill({contentType:'image/png',body:fs.readFileSync(fixture.source)});
  if(url.pathname==='/api/local-remove/stock/providers')return route.fulfill({json:{providers:[{id:'openverse',label:'Openverse',available:true},{id:'pexels',label:'Pexels',available:connection,needs_key:true,connect_url:'https://example.invalid/key'}],default_provider:'openverse'}});
  if(url.pathname==='/api/local-remove/stock/search')return route.fulfill(stockError?{status:503,json:{detail:'Controlled provider unavailable'}}:{json:{results:[stock],page:0,next_page:null}});
  if(url.pathname==='/api/local-remove/stock/connection/pexels'){connection=true;return route.fulfill({json:{connected:true}});}
  if(url.pathname==='/api/local-remove/stock/import'){const payload=request.postDataJSON();assert.equal(payload.target,'image');return route.fulfill({json:{session:fixture.stockSessions[Math.min(stockImports++,1)],attribution:fixture.attribution}});}
  if(request.method()!=='GET'&&(/^\/api\/local-remove\/(?:generation$|generation\/upscale$|generator|qwen\/download|setup|loras\/download)/.test(url.pathname)||/\/cutout$|\/cutout\/generate-background$/.test(url.pathname))){blocked.push(url.pathname);return route.abort('blockedbyclient');}
  return route.continue();
 });
 await context.addInitScript(()=>{localStorage.setItem('local-image.hardware-guide.v1','1');localStorage.setItem('local-image.first-ai-setup.v1','1');localStorage.setItem('local-image.first-task.v1','1');window.__assetCsp=[];document.addEventListener('securitypolicyviolation',event=>window.__assetCsp.push({directive:event.violatedDirective,blocked:event.blockedURI}));});
 page.on('pageerror',error=>errors.push(error.stack));page.on('request',request=>{if(request.url().includes('/api/'))requests.push({method:request.method(),path:new URL(request.url()).pathname});});
 page.on('response',response=>{if(response.url().includes('/frontend-assets/'))assetReads.push(response.body().then(body=>servedAssets.push({path:new URL(response.url()).pathname,sha256:hash(body),status:response.status()})));});
 const assets=page.locator('.li-assets'),idle=()=>page.waitForFunction(()=>!window.LocalImageEditor.getSnapshot().busy&&!window.LocalImageReactFeatures.assets.getSnapshot().working&&!window.LocalImageReactFeatures.assets.getSnapshot().loading);
 const shot=async name=>{const file=path.join(out,name);await page.screenshot({path:file,animations:'disabled'});shots.push(file);};
 try{
  const response=await page.goto(base+'/remove');htmlHash=hash(await response.body());csp=response.headers()['content-security-policy'];await page.waitForFunction(()=>document.body.dataset.reactReady==='true'&&window.LocalImageReactFeatures?.assets);
  assert.equal(await page.evaluate(()=>typeof session),'undefined');assert.equal(await page.evaluate(()=>typeof LocalImageLegacyEditor),'undefined');
  assert.equal(await page.locator('#stock-dialog,#generated-library-dialog,#stock-search-form,#background-grid,#background-library,#stack-background-folders,#stock-import-menu').count(),0,'Migrated legacy asset controls are absent');
  await page.getByRole('button',{name:'Assets',exact:true}).click();await idle();await assets.getByRole('textbox',{name:'Search stock photos'}).fill('ocean');await assets.getByRole('button',{name:'Search stock photos',exact:true}).click();await idle();
  await assets.getByRole('button',{name:'Controlled ocean',exact:true}).click();await assets.getByRole('button',{name:'Credits',exact:true}).click();assert.match(await assets.innerText(),/Controlled fixture credit/);assert.equal(await assets.getByRole('link',{name:'Fixture photographer',exact:true}).getAttribute('href'),fixture.attribution.creator_url);
  await assets.getByRole('button',{name:'Open image',exact:true}).click();await idle();assert.equal(await page.evaluate(()=>window.LocalImageEditor.getSnapshot().document.id),fixture.stockSessions[0].id);assert.equal(await page.evaluate(()=>window.LocalImageEditor.getSnapshot().document.source_attribution.attribution),fixture.attribution.attribution);
  checks.push('Sole React Stock owner uses controlled provider search/import with real seeded document handoff and visible attribution');
  await assets.getByRole('combobox',{name:'Stock source'}).selectOption('pexels');await assets.getByRole('button',{name:'Connection',exact:true}).click();await assets.getByLabel('Pexels API key',{exact:true}).fill('CONTROLLED-NOT-A-REAL-KEY');await assets.getByRole('button',{name:'Connect',exact:true}).click();await idle();assert.equal(await assets.getByLabel('Pexels API key',{exact:true}).inputValue(),'');assert.equal(await page.evaluate(()=>JSON.stringify(window.LocalImageReactFeatures.assets.getSnapshot()).includes('CONTROLLED-NOT-A-REAL-KEY')),false);
  stockError=true;await assets.getByRole('button',{name:'Search stock photos',exact:true}).click();await idle();assert.match(await assets.getByRole('alert').innerText(),/Controlled provider unavailable/);stockError=false;
  checks.push('Controlled key transport clears secret drafts; provider failure is visible without retry');
  await assets.getByRole('tab',{name:'Folders',exact:true}).click();await idle();await assets.getByRole('combobox',{name:'Background folder'}).selectOption(folder.id);await assets.getByRole('button',{name:'photo2.png',exact:true}).click();const before=await page.evaluate(()=>{const doc=window.LocalImageEditor.getSnapshot().document;return {id:doc.id,revision:doc.revision,count:doc.layer_stack.length};});await assets.getByRole('button',{name:'Add background',exact:true}).click();await idle();const after=await page.evaluate(()=>{const state=window.LocalImageEditor.getSnapshot(),doc=state.document;return {id:doc.id,revision:doc.revision,count:doc.layer_stack.length,selected:doc.layer_stack.find(layer=>layer.id===state.selectedLayerId)?.kind};});assert.equal(after.id,before.id);assert.equal(after.revision,before.revision+1);assert.equal(after.count,before.count+1);assert.equal(after.selected,'image');
  assert.equal(await assets.locator('img').first().getAttribute('loading'),'lazy');
  await assets.getByLabel('Choose background folder',{exact:true}).setInputFiles(fixture.backgroundDirectory);await page.waitForFunction(()=>window.LocalImageReactFeatures.assets.getSnapshot().folderSelected==='browser-files');const names=await assets.locator('.li-asset-tile').allTextContents();assert.ok(names[0].includes('photo2')&&names[1].includes('photo10'));
  checks.push('Actual registered-folder thumbnails/background mutation and browser folder fallback preserve document identity and lazy natural-sorted previews');
  for(const [width,height]of [[800,560],[1366,768],[1920,1080]]){await page.setViewportSize({width,height});await shot(`folders-${width}-${height}.png`);const box=await assets.boundingBox(),canvas=await page.locator('#viewport').boundingBox();assert.ok(box.width>100&&box.height>100);assert.ok(canvas.width>50&&canvas.height>100);}
  await page.setViewportSize({width:1366,height:768});await assets.getByRole('tab',{name:'Generated',exact:true}).click();await idle();await assets.getByRole('textbox',{name:'Filter generated images'}).fill(fixture.generatedName);await assets.getByRole('button',{name:fixture.generatedName,exact:true}).click();await assets.getByRole('button',{name:'Open image',exact:true}).click();await idle();const copyId=await page.evaluate(()=>window.LocalImageEditor.getSnapshot().document.id);assert.notEqual(copyId,fixture.generatedId);assert.equal(await page.evaluate(()=>window.LocalImageEditor.getSnapshot().document.reference_attributions[0].attribution),fixture.attribution.attribution);
  const sourceStatePath=path.join(profile,'state/sessions',copyId,'session.json'),sourceStateHash=hash(fs.readFileSync(sourceStatePath));
  await page.locator('#workspace-retouch').click();await idle();await assets.getByRole('button',{name:'Use as draft',exact:true}).click();await idle();assert.equal(await page.evaluate(()=>window.LocalImageEditor.getSnapshot().workspace),'generate');assert.equal(await page.evaluate(()=>window.LocalImageEditor.getSnapshot().refining),true);assert.ok(await page.evaluate(name=>window.LocalImageReactFeatures.generation.getSnapshot().draftImages.some(item=>item.session.name===name),fixture.generatedName));
  checks.push('Actual generated library Open creates an independent credited working copy; owned-busy handoff opens a separate refinement draft');
  await assets.getByRole('button',{name:'Select',exact:true}).click();await assets.getByRole('button',{name:fixture.generatedName,exact:true}).click();await assets.getByRole('button',{name:'Delete selected…',exact:true}).click();assert.equal(await assets.getByRole('button',{name:'Delete copies',exact:true}).isVisible(),true);await assets.getByRole('button',{name:'Delete copies',exact:true}).click();await idle();
  const library=await(await page.request.get(base+'/api/local-remove/generation/library')).json();assert.equal(library.items.some(item=>item.id===fixture.generatedId),false);assert.equal(hash(fs.readFileSync(fixture.source)),fixture.sourceSha256);assert.equal(hash(fs.readFileSync(sourceStatePath)),sourceStateHash);assert.equal((await page.request.get(base+'/api/local-remove/session/'+copyId)).status(),200);
  checks.push('Actual confirmed cache deletion removes only its library copy; original fixture and accepted working session remain byte-identical');
  await shot('generated-refinement.png');const refineSelection=await page.evaluate(()=>{const feature=window.LocalImageReactFeatures.generation;return (feature.selectedResult()??feature.selectedDraft())?.session.id??null;});assert.ok(refineSelection,'Refine has a selected draft to show when leaving');await page.locator('#workspace-retouch').click();await idle();assert.equal(await page.locator('#canvas-region').isVisible(),true,'Leaving Refine restores the retained canvas');assert.equal(await page.evaluate(()=>window.LocalImageEditor.getSnapshot().document.id),refineSelection,'Leaving Refine shows the draft selected in Refine');assert.ok(await page.evaluate(id=>window.LocalImageEditor.getSnapshot().openDocuments.some(item=>item.id===id),copyId),'The credited working copy stays open as a document tab');checks.push('Leaving Refine shows the selected draft on the retained image canvas through typed workspace state');
  cspViolations=await page.evaluate(()=>window.__assetCsp);assert.deepEqual(errors,[]);assert.deepEqual(cspViolations,[]);assert.deepEqual(blocked,[]);passed=true;
 }catch(error){failure=error.stack;await shot('failure.png').catch(()=>{});throw error;}
 finally{await Promise.all(assetReads);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({passed,failure,runtime,fixture,checks,errors,csp,cspViolations,htmlHash,servedAssets,requests,blocked,shots,stockTransport:'controlled fixtures; no provider requests or saved real keys',nativeScope:'owned registration HTTP only; no picker UI'},null,2));await browser.close();}
 console.log(`PASS React Assets: ${checks.length} composed checks; ${out}`);
})().catch(error=>{console.error(error);process.exitCode=1;});
