[package]
name = "photocraft-format-fuzz"
version = "0.0.0"
publish = false
edition = "2024"
license = "MIT OR Apache-2.0"

[package.metadata]
cargo-fuzz = true

[workspace]

[dependencies]
libfuzzer-sys = "0.4"
photocraft-format = { path = ".." }

[[bin]]
name = "load"
path = "fuzz_targets/load.rs"
test = false
doc = false
bench = false
