// One focused dialog for repeatable product work. The editor owns the familiar
// workspace; this module owns only treatment metadata and detached batch queues.
(()=>{
  'use strict';
  const PREFIX='/api/local-remove/batch',get=id=>document.getElementById(id);
  let selected=new Set(),treatments=[],queues=[],active=null,poll=null,working=false,opener=null,inspected=null,pendingFingerprint='',viewVersion=0;
  const html=`<div class="dialog-header"><h2 id="batch-title">Batch treatment & export</h2><button id="batch-close" aria-label="Close batch window">×</button></div>
    <div class="batch-toolbar"><label>Treatment<select id="batch-treatment"><option value="">Current edits only</option></select></label><button id="batch-save-treatment" class="secondary">Save current treatment…</button><button id="batch-delete-treatment" class="secondary" disabled>Remove treatment</button><label>Export format<select id="batch-format"><option value="original">Original precision & format</option><option value="png">PNG · 8-bit with alpha</option><option value="jpg">JPEG · 8-bit opaque</option><option value="tif">TIFF · preserve 16-bit</option><option value="webp">WebP · lossless 8-bit</option></select></label></div>
    <div id="batch-name-row" class="batch-name-row" hidden><label>Name<input id="batch-treatment-name" maxlength="80" placeholder="Warm studio / marketplace"></label><button id="batch-name-save" class="primary">Save treatment</button><button id="batch-name-cancel" class="secondary">Cancel</button></div>
    <p id="batch-treatment-description" class="batch-note">Current edits exports each image’s own layers and cutout. Saved treatments reuse backdrop, placement and shadow; each product keeps its own cutout.</p>
    <p id="batch-queue-settings" class="batch-note" hidden></p>
    <div id="batch-pending-warning" class="batch-pending-warning" hidden><p id="batch-pending-description"></p><div><label><input type="checkbox" id="batch-applied-only"> Use applied pixels only; keep pending selections</label><button id="batch-return-apply" class="secondary">Return to apply selection</button></div></div>
    <div class="batch-selection-tools"><label><input type="checkbox" id="batch-all"> Select all</label><span id="batch-selection-count"></span><label class="batch-prepare-option"><input type="checkbox" id="batch-prepare-cutouts"><span id="batch-prepare-label">Prepare missing cutouts with Qwen</span></label><select id="batch-qwen-variant" aria-label="Qwen cutout variant" disabled hidden><option value="int8">Qwen INT8</option><option value="bf16">Qwen BF16</option></select></div>
    <div class="batch-table-scroll" id="batch-table-scroll"><table class="batch-table"><thead><tr><th scope="col">Select</th><th scope="col">Photo</th><th scope="col">Preview</th><th scope="col">Status</th></tr></thead><tbody id="batch-rows"></tbody></table><p id="batch-empty" class="batch-note">Open a folder or multiple photos to prepare a batch.</p></div>
    <div id="batch-inspector" hidden><div class="batch-inspector-toolbar"><button id="batch-inspect-back" class="secondary">Back to images</button><strong id="batch-inspect-name"></strong><button id="batch-inspect-original" class="secondary" aria-pressed="false">Original</button><label>Zoom<select id="batch-inspect-zoom"><option value="fit">Fit</option><option value="100">100%</option><option value="200">200%</option></select></label></div><div id="batch-inspect-scroll"><img id="batch-inspect-image" alt=""></div></div>
    <div class="batch-progress-row"><p id="batch-status" role="status"></p><progress id="batch-progress" max="1" value="0" hidden></progress></div>
    <details class="batch-history"><summary>Previous queues & cache</summary><div class="batch-history-controls"><select id="batch-history-select" aria-label="Previous batch queue"></select><button id="batch-load-queue" class="secondary">Review queue</button><button id="batch-clear-queue" class="secondary" disabled>Clear queue cache</button><span id="batch-cache-size"></span></div></details>
    <div id="batch-confirm-row" class="batch-confirm-row" hidden><span id="batch-confirm-text"></span><button id="batch-confirm-yes" class="danger">Remove</button><button id="batch-confirm-no" class="secondary">Cancel</button></div>
    <div class="batch-footer"><span class="batch-note">Original files and editor documents stay intact. Exports always use new filenames.</span><button id="batch-cancel" class="secondary" hidden>Cancel batch</button><button id="batch-resume" class="secondary" hidden>Resume</button><a id="batch-download" class="secondary" hidden>Download ZIP</a><button id="batch-new-queue" class="secondary" hidden>New queue…</button><button id="batch-export" class="secondary" disabled>Export reviewed…</button><button id="batch-create" class="primary">Prepare selected</button></div>`;
  const dialog=document.createElement('dialog');dialog.id='batch-dialog';dialog.className='batch-dialog';dialog.setAttribute('aria-labelledby','batch-title');dialog.innerHTML=html;document.body.append(dialog);
  const button=document.createElement('button');button.id='batch-open';button.setAttribute('role','menuitem');button.setAttribute('aria-haspopup','dialog');button.textContent='Batch treatment & export…';get('file-menu').insertBefore(button,get('file-menu').querySelector('.menu-separator'));
  const bytes=value=>value<1024**2?(value/1024).toFixed(0)+' KB':value<1024**3?(value/1024**2).toFixed(1)+' MB':(value/1024**3).toFixed(2)+' GB';
  const entries=()=>collection?.entries|| (session?[{id:session.id,name:session.name,session_id:session.id}]:[]);
  const selectedRows=()=> (active?active.items:entries()).filter(entry=>selected.has(entry.id));
  function pendingRows(){const values=selectedRows().filter(entry=>entry.session_id&&pendingSelection(entry.session_id));if(!get('batch-name-row').hidden&&session&&pendingSelection(session.id)&&!values.some(entry=>entry.session_id===session.id))values.push({name:session.name,session_id:session.id});return values;}
  function pendingAllowed(){return !pendingRows().length||get('batch-applied-only').checked;}
  function pendingWarning(){const values=pendingRows(),fingerprint=values.map(entry=>{const state=viewStates.get(entry.session_id);return entry.session_id+'|'+(state?.mask||'')+'|'+JSON.stringify(state?.points||[]);}).join('\n');if(fingerprint!==pendingFingerprint){get('batch-applied-only').checked=false;pendingFingerprint=fingerprint;}get('batch-pending-warning').hidden=!values.length;get('batch-pending-description').textContent=values.length+' selected photo'+(values.length===1?' has':'s have')+' an unapplied selection or unfinished path: '+values.slice(0,3).map(value=>value.name).join(', ')+(values.length>3?' and '+(values.length-3)+' more':'')+'. Batch preparation and export include applied pixels only.';get('batch-pending-description').title=values.map(value=>value.name).join('\n');}
  function showQueueSettings(){const note=get('batch-queue-settings');note.hidden=!active;if(!active)return;const preset=get('batch-treatment');if(active.treatment_id&&!Array.from(preset.options).some(option=>option.value===active.treatment_id))preset.add(new Option((active.treatment_name||'Saved treatment')+' · queue copy',active.treatment_id));preset.value=active.treatment_id||'';get('batch-format').value=active.format;get('batch-prepare-cutouts').checked=!!active.prepare_cutouts;get('batch-qwen-variant').value=active.qwen_variant||'int8';note.textContent='Reviewed queue: '+(active.treatment_name||'Current edits only')+' · '+get('batch-format').selectedOptions[0].textContent+'. These settings are fixed for its previews and exports. Choose New queue to change them.';}
  function status(text,error=false){get('batch-status').textContent=text;get('batch-status').classList.toggle('error',error);}
  async function request(tail,body,method='POST'){return body===undefined?(await api(PREFIX+tail,{method})).json():json(PREFIX+tail,body,method);}
  function update(){
    const running=!!active?.running,locked=working||running;
    showQueueSettings();pendingWarning();
    get('batch-create').disabled=locked||!!active||!selected.size||!pendingAllowed();get('batch-create').hidden=!!active;
    get('batch-new-queue').hidden=!active;get('batch-new-queue').disabled=locked;
    for(const id of ['batch-treatment','batch-format','batch-name-save'])get(id).disabled=locked||!!active;
    get('batch-name-save').disabled=locked||!!active||!pendingAllowed();
    get('batch-load-queue').disabled=locked;
    get('batch-save-treatment').disabled=locked||!!active||!session?.cutout?.enabled||!pendingAllowed();
    get('batch-delete-treatment').disabled=locked||!!active||!get('batch-treatment').value;
    const qwenAvailable=!!qwenStatus?.connected&&qwenStatus?.variants?.some(variant=>variant.available);
    get('batch-prepare-cutouts').disabled=locked||!!active||!get('batch-treatment').value||!qwenAvailable;
    get('batch-prepare-label').textContent='Prepare missing cutouts with Qwen'+(!qwenAvailable?' · AI setup needed':'');
    for(const option of get('batch-qwen-variant').options){const available=qwenStatus?.variants?.find(variant=>variant.id===option.value);option.disabled=available?.available===false;option.textContent='Qwen '+option.value.toUpperCase()+(available?.available===false?' · not installed':'');}
    if(!active&&get('batch-qwen-variant').selectedOptions[0]?.disabled&&qwenAvailable)get('batch-qwen-variant').value=qwenStatus.variants.find(variant=>variant.available).id;
    get('batch-prepare-cutouts').parentElement.hidden=!get('batch-treatment').value;
    get('batch-qwen-variant').disabled=locked||!!active||!get('batch-prepare-cutouts').checked||!get('batch-treatment').value;
    get('batch-qwen-variant').hidden=!get('batch-prepare-cutouts').checked||!get('batch-treatment').value;
    get('batch-export').disabled=locked||!pendingAllowed()||!active?.items.some(item=>item.status==='ready'&&selected.has(item.id));
    get('batch-export').textContent=nativeReady?'Export reviewed to folder…':'Export reviewed as ZIP';
    get('batch-cancel').hidden=!running;get('batch-resume').hidden=running||active?.phase!=='paused';
    get('batch-clear-queue').disabled=locked||!get('batch-history-select').value;
    get('batch-selection-count').textContent=selected.size+' selected · up to 100 per queue';
    const available=active?active.items:entries();get('batch-all').checked=!!available.length&&selected.size===available.length;get('batch-all').disabled=locked||available.length>100;
    for(const input of dialog.querySelectorAll('[data-batch-entry]'))input.disabled=locked;
    get('batch-progress').hidden=!running;get('batch-progress').value=active?.items.length?active.items.filter(item=>active.mode==='prepare'?!['pending','preparing'].includes(item.status):['exported','failed','conflict','needs-cutout'].includes(item.status)).length/active.items.length:0;
    const download=get('batch-download');download.hidden=!active?.download||running;if(active?.download){download.href=active.download;download.download='Local Image batch.zip';}
  }
  function rows(){
    const tbody=get('batch-rows');tbody.replaceChildren();
    const source=active?active.items:entries();get('batch-empty').hidden=!!source.length;
    for(const entry of source){const row=document.createElement('tr'),cell=document.createElement('td'),check=document.createElement('input');check.type='checkbox';check.dataset.batchEntry=entry.id;check.checked=selected.has(entry.id);check.setAttribute('aria-label','Select '+entry.name);check.onchange=()=>{check.checked?selected.add(entry.id):selected.delete(entry.id);update();};cell.append(check);row.append(cell);
      const name=document.createElement('td');name.textContent=entry.name;row.append(name);
      const imageCell=document.createElement('td');if(entry.preview){const image=document.createElement('img');image.src=entry.preview;image.alt='Batch preview of '+entry.name;image.loading='lazy';const inspect=document.createElement('button');inspect.className='batch-inspect-button';inspect.setAttribute('aria-label','Inspect '+entry.name+' at full size');inspect.append(image);inspect.onclick=()=>inspectImage(entry);imageCell.append(inspect);}else imageCell.textContent='—';row.append(imageCell);
      const state=document.createElement('td');const labels={pending:'Waiting',preparing:'Preparing…',ready:'Ready for review',exporting:'Exporting…',exported:'Exported',failed:'Needs attention',conflict:'Edits changed','needs-cutout':'Cutout needed'};state.textContent=(active?(labels[entry.status]||entry.status)+(entry.error?' · '+entry.error:'')+(entry.output_name?' · '+entry.output_name:''):'Selected edits')+(entry.session_id&&pendingSelection(entry.session_id)?' · Selection pending; applied pixels only':'');if(entry.error)state.classList.add('error');row.append(state);tbody.append(row);
    }update();
  }
  function inspectZoom(){const image=get('batch-inspect-image'),value=get('batch-inspect-zoom').value;image.classList.toggle('batch-fit-preview',value==='fit');image.style.width=value==='fit'?'':image.naturalWidth*Number(value)/100+'px';image.style.height='auto';}
  function inspectImage(entry){inspected=entry;get('batch-table-scroll').hidden=true;get('batch-inspector').hidden=false;get('batch-inspect-name').textContent=entry.name;get('batch-inspect-original').setAttribute('aria-pressed','false');get('batch-inspect-original').textContent='Original';get('batch-inspect-zoom').value='fit';get('batch-inspect-image').alt='Full-size treatment preview of '+entry.name;get('batch-inspect-image').src=entry.preview+'?full=true';get('batch-inspect-image').onload=inspectZoom;}
  get('batch-inspect-back').onclick=()=>{get('batch-inspector').hidden=true;get('batch-table-scroll').hidden=false;};get('batch-inspect-zoom').onchange=inspectZoom;
  get('batch-inspect-original').onclick=()=>{const original=get('batch-inspect-original').getAttribute('aria-pressed')!=='true';get('batch-inspect-original').setAttribute('aria-pressed',String(original));get('batch-inspect-image').src=inspected.preview+'?full=true&original='+original;get('batch-inspect-image').alt='Full-size '+(original?'original':'treatment')+' preview of '+inspected.name;get('batch-inspect-original').textContent=original?'Treatment':'Original';};
  async function refreshLists(){
    const [saved,history]=await Promise.all([request('/treatments',undefined,'GET'),request('/jobs',undefined,'GET')]);treatments=saved.items;queues=history.items;
    const preset=get('batch-treatment'),chosen=preset.value;preset.replaceChildren(new Option('Current edits only',''),...treatments.map(value=>new Option(value.name,value.id)));if(treatments.some(value=>value.id===chosen))preset.value=chosen;
    const queue=get('batch-history-select'),previous=queue.value;queue.replaceChildren(...queues.map(value=>new Option(value.name+' · '+new Date(value.created*1000).toLocaleString()+' · '+value.phase,value.id)));if(queues.some(value=>value.id===previous))queue.value=previous;if(active&&queues.some(value=>value.id===active.id))queue.value=active.id;
    get('batch-cache-size').textContent='Batch cache '+bytes(history.bytes)+' · treatments '+bytes(saved.bytes);update();
  }
  function schedule(){clearTimeout(poll);if(active?.running&&dialog.open){const identifier=active.id,version=viewVersion;poll=setTimeout(async()=>{try{const value=await request('/jobs/'+identifier,undefined,'GET');if(version!==viewVersion||active?.id!==identifier)return;active=value;rows();status(active.message);if(!active.running)await refreshLists();}catch(error){if(version===viewVersion)status(error.message,true);}if(version===viewVersion)schedule();},600);}}
  async function show(){if(busy||working)return;++viewVersion;opener=document.activeElement;closeMenus();rememberCurrentView();active=null;pendingFingerprint='';get('batch-applied-only').checked=false;get('batch-name-row').hidden=true;get('batch-inspector').hidden=true;get('batch-table-scroll').hidden=false;selected=new Set(entries().slice(0,100).map(entry=>entry.id));dialog.showModal();rows();status('Select images, choose a treatment, then review previews before exporting.');try{await flushLayerChanges();await refreshLists();const live=queues.find(value=>value.running);if(live){active=live;selected=new Set(live.items.map(item=>item.id));rows();schedule();}}catch(error){status(error.message,true);}}
  button.onclick=show;window.LocalImageBatch={open:show,isOpen:()=>dialog.open};
  get('batch-close').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{++viewVersion;clearTimeout(poll);opener?.focus();});
  get('batch-all').onchange=()=>{const available=active?active.items:entries();selected=get('batch-all').checked?new Set(available.slice(0,100).map(entry=>entry.id)):new Set();rows();};
  get('batch-treatment').onchange=()=>{const value=treatments.find(value=>value.id===get('batch-treatment').value);if(value)get('batch-format').value=value.format;else get('batch-prepare-cutouts').checked=false;update();};
  get('batch-prepare-cutouts').onchange=update;
  get('batch-save-treatment').onclick=()=>{get('batch-name-row').hidden=false;update();get('batch-treatment-name').focus();};get('batch-name-cancel').onclick=()=>{get('batch-name-row').hidden=true;update();};
  get('batch-name-save').onclick=async()=>{if(!pendingAllowed()){status('Acknowledge applied pixels only, or return to apply the pending selection.',true);return;}working=true;update();try{const saved=await request('/treatments',{name:get('batch-treatment-name').value,session_id:session.id,revision:session.revision,format:get('batch-format').value});await refreshLists();get('batch-treatment').value=saved.id;get('batch-name-row').hidden=true;status('Saved '+saved.name+'. Its background is copied; each product keeps its own cutout.');}catch(error){status(error.message,true);}finally{working=false;update();}};
  function confirm(text,action){get('batch-confirm-text').textContent=text;get('batch-confirm-row').hidden=false;get('batch-confirm-yes').onclick=async()=>{get('batch-confirm-row').hidden=true;working=true;update();try{await action();await refreshLists();rows();}catch(error){status(error.message,true);}finally{working=false;update();}};get('batch-confirm-no').onclick=()=>get('batch-confirm-row').hidden=true;}
  get('batch-delete-treatment').onclick=()=>{const id=get('batch-treatment').value;confirm('Remove this saved treatment? Existing queues and image documents keep their copies.',async()=>{await request('/treatments/'+id,undefined,'DELETE');status('Treatment removed.');});};
  get('batch-create').onclick=async()=>{if(busy||working||active||!selected.size)return;if(!pendingAllowed()){status('Acknowledge applied pixels only, or return to apply the pending selection.',true);return;}working=true;update();try{
    // Review rows use queue IDs; new preparation always selects collection IDs.
    const available=entries().filter(entry=>selected.has(entry.id)||active?.items.some(item=>selected.has(item.id)&&item.session_id===entry.session_id));
    if(!available.length)throw Error('Open the source photos and select them for a new queue.');
    const body={treatment_id:get('batch-treatment').value||null,prepare_cutouts:get('batch-prepare-cutouts').checked,qwen_variant:get('batch-qwen-variant').value,format:get('batch-format').value};
    if(collection&&!collection.local){body.collection_id=collection.id;body.entry_ids=available.map(entry=>entry.id);}else{body.sessions=[];for(const [index,entry] of available.entries()){let current;if(!entry.session_id){if(!entry.file)throw Error('Open this photo before preparing its batch.');status('Preparing upload '+(index+1)+' of '+available.length+'…');const form=new FormData();form.append('file',entry.file);current=await(await api('/api/local-remove/import',{method:'POST',body:form})).json();entry.session_id=current.id;}else current=await(await api('/api/local-remove/session/'+entry.session_id)).json();body.sessions.push({session_id:current.id,revision:current.revision});}}
    active=await request('/jobs',body);selected=new Set(active.items.map(item=>item.id));rows();status(active.message);schedule();
  }catch(error){status(error.message,true);}finally{working=false;update();}};
  get('batch-export').onclick=async()=>{if(!pendingAllowed()){status('Acknowledge applied pixels only, or return to apply the pending selection.',true);return;}working=true;update();try{const item_ids=active.items.filter(item=>item.status==='ready'&&selected.has(item.id)).map(item=>item.id);const value=nativeReady?await nativeRequest('batchExportFolder',null,{job_id:active.id,item_ids}):await request('/jobs/'+active.id+'/export',{item_ids});if(value){active=value;rows();status(active.message);schedule();}}catch(error){status(error.message,true);}finally{working=false;update();}};
  get('batch-new-queue').onclick=async()=>{if(working||active?.running)return;++viewVersion;clearTimeout(poll);const previous=active.id,chosen=new Set(selectedRows().map(entry=>entry.session_id));active=null;selected=new Set(entries().filter(entry=>chosen.has(entry.session_id)).map(entry=>entry.id));if(!selected.size)selected=new Set(entries().slice(0,100).map(entry=>entry.id));pendingFingerprint='';get('batch-applied-only').checked=false;get('batch-inspector').hidden=true;get('batch-table-scroll').hidden=false;working=true;rows();try{await refreshLists();if(queues.some(queue=>queue.id===previous))get('batch-history-select').value=previous;status('New queue: choose settings, prepare selected images, then review the new previews.');}catch(error){status(error.message,true);}finally{working=false;update();}};
  get('batch-applied-only').onchange=update;
  get('batch-return-apply').onclick=async()=>{const target=pendingRows()[0];dialog.close();if(target&&target.session_id!==session?.id){const index=collection?.entries.findIndex(entry=>entry.session_id===target.session_id)??-1;if(index>=0)await openCollectionEntry(index);else{const data=openDocuments.get(target.session_id);if(data)await openSession(data);}}message('Apply the pending selection, then open Batch treatment & export again. Your selection is kept.');viewport.focus();};
  get('batch-cancel').onclick=async()=>{try{active=await request('/jobs/'+active.id+'/cancel',{});status('Cancelling after the current image. Existing exports are kept.');}catch(error){status(error.message,true);}};
  get('batch-resume').onclick=async()=>{try{active=await request('/jobs/'+active.id+'/resume',{});rows();schedule();}catch(error){status(error.message,true);}};
  get('batch-load-queue').onclick=async()=>{if(working)return;const version=++viewVersion;clearTimeout(poll);working=true;update();try{const value=await request('/jobs/'+get('batch-history-select').value,undefined,'GET');if(version!==viewVersion)return;active=value;selected=new Set(active.items.map(item=>item.id));rows();status(active.message);schedule();}catch(error){status(error.message,true);}finally{working=false;update();}};
  get('batch-clear-queue').onclick=()=>{const id=get('batch-history-select').value;confirm('Clear this queue’s previews and cached export copies? Original images, editor documents, saved projects and folder exports remain.',async()=>{await request('/jobs/'+id,undefined,'DELETE');if(active?.id===id)active=null;status('Queue cache cleared. Original images and folder exports are kept.');});};
})();
