//! Photoshop menu structure (standard public command names) used to present the full, familiar
//! menu tree, in order, with separators ("---"). Items whose id matches an engine or UI command are
//! live; others render disabled until implemented. Generated from the recorded menu structure.

/// (menu path, label or "---", default shortcut, command id)
pub static CATALOG: &[(&[&str], &str, Option<&str>, &str)] = &[
    (&["File"], "New…", Some("Cmd+N"), "file.new"),
    (&["File"], "Open…", Some("Cmd+O"), "file.open"),
    (&["File"], "Open As…", Some("Cmd+Alt+Shift+O"), "file.openAs"),
    (&["File"], "---", None, "---"),
    (&["File"], "Close", Some("Cmd+W"), "file.close"),
    (&["File"], "Close All", Some("Cmd+Alt+W"), "file.closeAll"),
    (&["File"], "Close Others", Some("Cmd+Alt+P"), "file.closeOthers"),
    (&["File"], "---", None, "---"),
    (&["File"], "Save", Some("Cmd+S"), "file.save"),
    (&["File"], "Save As…", Some("Cmd+Shift+S"), "file.saveAs"),
    (&["File"], "Save a Copy…", Some("Cmd+Alt+S"), "file.saveACopy"),
    (&["File"], "Revert", Some("F12"), "file.revert"),
    (&["File"], "---", None, "---"),
    (&["File", "Export"], "Quick Export as PNG", None, "file.export.quickExportAsPng"),
    (&["File", "Export"], "Export As…", Some("Cmd+Alt+Shift+W"), "file.export.exportAs"),
    (&["File", "Export"], "Export Preferences…", None, "file.export.exportPreferences"),
    (&["File", "Export"], "---", None, "---"),
    (&["File", "Export"], "Save for Web (Legacy)…", Some("Cmd+Alt+Shift+S"), "file.export.saveForWebLegacy"),
    (&["File", "Export"], "---", None, "---"),
    (&["File", "Export"], "Artboards to Files…", None, "file.export.artboardsToFiles"),
    (&["File", "Export"], "Artboards to PDF…", None, "file.export.artboardsToPdf"),
    (&["File", "Export"], "Layers to Files…", None, "file.export.layersToFiles"),
    (&["File", "Export"], "Layer Comps to Files…", None, "file.export.layerCompsToFiles"),
    (&["File", "Export"], "---", None, "---"),
    (&["File", "Export"], "Color Lookup Tables…", None, "file.export.colorLookupTables"),
    (&["File", "Export"], "Data Sets as Files…", None, "file.export.dataSetsAsFiles"),
    (&["File", "Export"], "Paths to Illustrator…", None, "file.export.pathsToIllustrator"),
    (&["File", "Export"], "Render Video…", None, "file.export.renderVideo"),
    (&["File", "Generate"], "Image Assets", None, "file.generate.imageAssets"),
    (&["File"], "---", None, "---"),
    (&["File"], "Place Embedded…", None, "file.placeEmbedded"),
    (&["File"], "Place Linked…", None, "file.placeLinked"),
    (&["File"], "---", None, "---"),
    (&["File"], "Package…", None, "file.package"),
    (&["File"], "---", None, "---"),
    (&["File", "Automate"], "Batch…", None, "file.automate.batch"),
    (&["File", "Automate"], "Create Droplet…", None, "file.automate.createDroplet"),
    (&["File", "Automate"], "---", None, "---"),
    (&["File", "Automate"], "Crop and Straighten Photos", None, "file.automate.cropAndStraightenPhotos"),
    (&["File", "Automate"], "Contact Sheet II…", None, "file.automate.contactSheetII"),
    (&["File", "Automate"], "Conditional Mode Change…", None, "file.automate.conditionalModeChange"),
    (&["File", "Automate"], "Fit Image…", None, "file.automate.fitImage"),
    (&["File", "Automate"], "Lens Correction…", None, "file.automate.lensCorrection"),
    (&["File", "Automate"], "---", None, "---"),
    (&["File", "Automate"], "Merge to HDR Pro…", None, "file.automate.mergeToHdrPro"),
    (&["File", "Automate"], "Photomerge…", None, "file.automate.photomerge"),
    (&["File", "Scripts"], "Image Processor…", None, "file.scripts.imageProcessor"),
    (&["File", "Scripts"], "---", None, "---"),
    (&["File", "Scripts"], "Delete All Empty Layers", None, "file.scripts.deleteAllEmptyLayers"),
    (&["File", "Scripts"], "Flatten All Layer Effects", None, "file.scripts.flattenAllLayerEffects"),
    (&["File", "Scripts"], "Flatten All Masks", None, "file.scripts.flattenAllMasks"),
    (&["File", "Scripts"], "---", None, "---"),
    (&["File", "Scripts"], "Script Events Manager…", None, "file.scripts.scriptEventsManager"),
    (&["File", "Scripts"], "---", None, "---"),
    (&["File", "Scripts"], "Load Files into Stack…", None, "file.scripts.loadFilesIntoStack"),
    (&["File", "Scripts"], "Statistics…", None, "file.scripts.statistics"),
    (&["File", "Scripts"], "---", None, "---"),
    (&["File", "Scripts"], "Browse…", None, "file.scripts.browse"),
    (&["File", "Import"], "Variable Data Sets…", None, "file.import.variableDataSets"),
    (&["File", "Import"], "Video Frames to Layers…", None, "file.import.videoFramesToLayers"),
    (&["File", "Import"], "Notes…", None, "file.import.notes"),
    (&["File", "Import"], "WIA Support…", None, "file.import.wiaSupport"),
    (&["File"], "---", None, "---"),
    (&["File"], "File Info…", Some("Cmd+Alt+Shift+I"), "file.fileInfo"),
    (&["File"], "---", None, "---"),
    (&["File"], "Print…", Some("Cmd+P"), "file.print"),
    (&["File"], "Print One Copy", Some("Cmd+Alt+Shift+P"), "file.printOneCopy"),
    (&["File"], "---", None, "---"),
    (&["File"], "Exit", Some("Cmd+Q"), "file.exit"),
    (&["Edit"], "Undo", None, "edit.undo"),
    (&["Edit"], "Redo", None, "edit.redo"),
    (&["Edit"], "Toggle Last State", Some("Cmd+Alt+Z"), "edit.toggleLastState"),
    (&["Edit"], "Fade…", Some("Cmd+Shift+F"), "edit.fade"),
    (&["Edit"], "---", None, "---"),
    (&["Edit"], "Cut", None, "edit.cut"),
    (&["Edit"], "Copy", None, "edit.copy"),
    (&["Edit"], "Copy Merged", Some("Cmd+Shift+C"), "edit.copyMerged"),
    (&["Edit"], "Paste", None, "edit.paste"),
    (&["Edit", "Paste Special"], "Paste in Place", Some("Cmd+Shift+V"), "edit.pasteSpecial.pasteInPlace"),
    (&["Edit", "Paste Special"], "Paste Into", Some("Cmd+Alt+Shift+V"), "edit.pasteSpecial.pasteInto"),
    (&["Edit", "Paste Special"], "Paste Outside", None, "edit.pasteSpecial.pasteOutside"),
    (&["Edit"], "Clear", None, "edit.clear"),
    (&["Edit"], "---", None, "---"),
    (&["Edit"], "Search…", Some("Cmd+K"), "edit.search"),
    (&["Edit"], "---", None, "---"),
    (&["Edit"], "Check Spelling…", None, "edit.checkSpelling"),
    (&["Edit"], "Find and Replace Text…", None, "edit.findAndReplaceText"),
    (&["Edit"], "---", None, "---"),
    (&["Edit"], "Fill…", Some("Shift+F5"), "edit.fill"),
    (&["Edit"], "Stroke…", None, "edit.stroke"),
    (&["Edit"], "Content-Aware Fill…", None, "edit.contentAwareFill"),
    (&["Edit"], "---", None, "---"),
    (&["Edit"], "Content-Aware Scale", Some("Cmd+Alt+Shift+C"), "edit.contentAwareScale"),
    (&["Edit"], "Puppet Warp", None, "edit.puppetWarp"),
    (&["Edit"], "Perspective Warp", None, "edit.perspectiveWarp"),
    (&["Edit"], "Free Transform", Some("Cmd+T"), "edit.freeTransform"),
    (&["Edit", "Transform"], "Again", Some("Cmd+Shift+T"), "edit.transform.again"),
    (&["Edit", "Transform"], "---", None, "---"),
    (&["Edit", "Transform"], "Scale", None, "edit.transform.scale"),
    (&["Edit", "Transform"], "Rotate", None, "edit.transform.rotate"),
    (&["Edit", "Transform"], "Skew", None, "edit.transform.skew"),
    (&["Edit", "Transform"], "Distort", None, "edit.transform.distort"),
    (&["Edit", "Transform"], "Perspective", None, "edit.transform.perspective"),
    (&["Edit", "Transform"], "Warp", None, "edit.transform.warp"),
    (&["Edit", "Transform"], "---", None, "---"),
    (&["Edit", "Transform"], "Split Warp Horizontally", None, "edit.transform.splitWarpHorizontally"),
    (&["Edit", "Transform"], "Split Warp Vertically", None, "edit.transform.splitWarpVertically"),
    (&["Edit", "Transform"], "Split Warp Crosswise", None, "edit.transform.splitWarpCrosswise"),
    (&["Edit", "Transform"], "Remove Warp Split", None, "edit.transform.removeWarpSplit"),
    (&["Edit", "Transform"], "---", None, "---"),
    (&["Edit", "Transform"], "Rotate 180°", None, "edit.transform.rotate180"),
    (&["Edit", "Transform"], "Rotate 90° Clockwise", None, "edit.transform.rotate90Cw"),
    (&["Edit", "Transform"], "Rotate 90° Counter Clockwise", None, "edit.transform.rotate90Ccw"),
    (&["Edit", "Transform"], "---", None, "---"),
    (&["Edit", "Transform"], "Flip Horizontal", None, "edit.transform.flipHorizontal"),
    (&["Edit", "Transform"], "Flip Vertical", None, "edit.transform.flipVertical"),
    (&["Edit"], "Auto-Align Layers…", None, "edit.autoAlignLayers"),
    (&["Edit"], "Auto-Blend Layers…", None, "edit.autoBlendLayers"),
    (&["Edit"], "---", None, "---"),
    (&["Edit"], "Define Brush Preset…", None, "edit.defineBrushPreset"),
    (&["Edit"], "Define Pattern…", None, "edit.definePattern"),
    (&["Edit"], "Define Custom Shape…", None, "edit.defineCustomShape"),
    (&["Edit"], "---", None, "---"),
    (&["Edit", "Purge"], "Undo", None, "edit.purge.undo"),
    (&["Edit", "Purge"], "Clipboard", None, "edit.purge.clipboard"),
    (&["Edit", "Purge"], "Histories", None, "edit.purge.histories"),
    (&["Edit", "Purge"], "Video Cache", None, "edit.purge.videoCache"),
    (&["Edit", "Purge"], "---", None, "---"),
    (&["Edit", "Purge"], "All", None, "edit.purge.all"),
    (&["Edit"], "---", None, "---"),
    (&["Edit", "Presets"], "Preset Manager…", None, "edit.presets.presetManager"),
    (&["Edit", "Presets"], "---", None, "---"),
    (&["Edit", "Presets"], "Migrate Presets", None, "edit.presets.migratePresets"),
    (&["Edit", "Presets"], "Export/Import Presets…", None, "edit.presets.exportImportPresets"),
    (&["Edit"], "---", None, "---"),
    (&["Edit"], "Color Settings…", Some("Cmd+Shift+K"), "edit.colorSettings"),
    (&["Edit"], "Assign Profile…", None, "edit.assignProfile"),
    (&["Edit"], "Convert to Profile…", None, "edit.convertToProfile"),
    (&["Edit"], "---", None, "---"),
    (&["Edit"], "Keyboard Shortcuts…", Some("Cmd+Alt+Shift+K"), "edit.keyboardShortcuts"),
    (&["Edit"], "Menus…", Some("Cmd+Alt+Shift+M"), "edit.menus"),
    (&["Edit"], "Toolbar…", None, "edit.toolbar"),
    (&["Edit"], "---", None, "---"),
    (&["Edit", "Preferences"], "Settings…", None, "edit.preferences.general"),
    (&["Edit", "Preferences"], "AI Integrations…", None, "edit.preferences.integrations"),
    (&["Edit", "Preferences"], "Interface…", None, "edit.preferences.interface"),
    (&["Edit", "Preferences"], "Workspace…", None, "edit.preferences.workspace"),
    (&["Edit", "Preferences"], "Tools…", None, "edit.preferences.tools"),
    (&["Edit", "Preferences"], "History Log…", None, "edit.preferences.historyLog"),
    (&["Edit", "Preferences"], "File Handling…", None, "edit.preferences.fileHandling"),
    (&["Edit", "Preferences"], "Export…", None, "edit.preferences.export"),
    (&["Edit", "Preferences"], "Performance…", None, "edit.preferences.performance"),
    (&["Edit", "Preferences"], "Scratch Disks…", None, "edit.preferences.scratchDisks"),
    (&["Edit", "Preferences"], "Cursors…", None, "edit.preferences.cursors"),
    (&["Edit", "Preferences"], "Transparency & Gamut…", None, "edit.preferences.transparencyAndGamut"),
    (&["Edit", "Preferences"], "Units & Rulers…", None, "edit.preferences.unitsAndRulers"),
    (&["Edit", "Preferences"], "Guides, Grid & Slices…", None, "edit.preferences.guidesGridAndSlices"),
    (&["Edit", "Preferences"], "Plug-ins…", None, "edit.preferences.plugIns"),
    (&["Edit", "Preferences"], "Type…", None, "edit.preferences.type"),
    (&["Edit", "Preferences"], "Enhanced Controls…", None, "edit.preferences.enhancedControls"),
    (&["Edit", "Preferences"], "Raw Defaults…", None, "edit.preferences.rawDefaults"),
    (&["Image", "Mode"], "Bitmap", None, "image.mode.bitmap"),
    (&["Image", "Mode"], "Grayscale", None, "image.mode.grayscale"),
    (&["Image", "Mode"], "Duotone", None, "image.mode.duotone"),
    (&["Image", "Mode"], "Indexed Color", None, "image.mode.indexedColor"),
    (&["Image", "Mode"], "RGB Color", None, "image.mode.rgb"),
    (&["Image", "Mode"], "CMYK Color", None, "image.mode.cmyk"),
    (&["Image", "Mode"], "Lab Color", None, "image.mode.lab"),
    (&["Image", "Mode"], "Multichannel", None, "image.mode.multichannel"),
    (&["Image", "Mode"], "---", None, "---"),
    (&["Image", "Mode"], "8 Bits/Channel", None, "image.mode.bits8"),
    (&["Image", "Mode"], "16 Bits/Channel", None, "image.mode.bits16"),
    (&["Image", "Mode"], "32 Bits/Channel", None, "image.mode.bits32"),
    (&["Image", "Mode"], "---", None, "---"),
    (&["Image", "Mode"], "Color Table…", None, "image.mode.colorTable"),
    (&["Image"], "---", None, "---"),
    (&["Image", "Adjustments"], "Brightness/Contrast…", None, "image.adjustments.brightnessContrast"),
    (&["Image", "Adjustments"], "Levels…", Some("Cmd+L"), "image.adjustments.levels"),
    (&["Image", "Adjustments"], "Curves…", Some("Cmd+M"), "image.adjustments.curves"),
    (&["Image", "Adjustments"], "Exposure…", None, "image.adjustments.exposure"),
    (&["Image", "Adjustments"], "Vibrance…", None, "image.adjustments.vibrance"),
    (&["Image", "Adjustments"], "Hue/Saturation…", Some("Cmd+U"), "image.adjustments.hueSaturation"),
    (&["Image", "Adjustments"], "Color Balance…", Some("Cmd+B"), "image.adjustments.colorBalance"),
    (&["Image", "Adjustments"], "Black & White…", Some("Cmd+Alt+Shift+B"), "image.adjustments.blackWhite"),
    (&["Image", "Adjustments"], "Photo Filter…", None, "image.adjustments.photoFilter"),
    (&["Image", "Adjustments"], "Channel Mixer…", None, "image.adjustments.channelMixer"),
    (&["Image", "Adjustments"], "Color Lookup…", None, "image.adjustments.colorLookup"),
    (&["Image", "Adjustments"], "---", None, "---"),
    (&["Image", "Adjustments"], "Invert", Some("Cmd+I"), "image.adjustments.invert"),
    (&["Image", "Adjustments"], "Posterize…", None, "image.adjustments.posterize"),
    (&["Image", "Adjustments"], "Threshold…", None, "image.adjustments.threshold"),
    (&["Image", "Adjustments"], "Gradient Map…", None, "image.adjustments.gradientMap"),
    (&["Image", "Adjustments"], "Selective Color…", None, "image.adjustments.selectiveColor"),
    (&["Image", "Adjustments"], "---", None, "---"),
    (&["Image", "Adjustments"], "Shadows/Highlights…", None, "image.adjustments.shadowsHighlights"),
    (&["Image", "Adjustments"], "HDR Toning…", None, "image.adjustments.hdrToning"),
    (&["Image", "Adjustments"], "---", None, "---"),
    (&["Image", "Adjustments"], "Desaturate", Some("Cmd+Shift+U"), "image.adjustments.desaturate"),
    (&["Image", "Adjustments"], "Match Color…", None, "image.adjustments.matchColor"),
    (&["Image", "Adjustments"], "Replace Color…", None, "image.adjustments.replaceColor"),
    (&["Image", "Adjustments"], "Equalize", None, "image.adjustments.equalize"),
    (&["Image"], "---", None, "---"),
    (&["Image"], "Auto Tone", Some("Cmd+Shift+L"), "image.autoTone"),
    (&["Image"], "Auto Contrast", Some("Cmd+Alt+Shift+L"), "image.autoContrast"),
    (&["Image"], "Auto Color", Some("Cmd+Shift+B"), "image.autoColor"),
    (&["Image"], "---", None, "---"),
    (&["Image"], "Image Size…", Some("Cmd+Alt+I"), "image.imageSize"),
    (&["Image"], "Canvas Size…", Some("Cmd+Alt+C"), "image.canvasSize"),
    (&["Image", "Image Rotation"], "180°", None, "image.imageRotation.180"),
    (&["Image", "Image Rotation"], "90° Clockwise", None, "image.imageRotation.90cw"),
    (&["Image", "Image Rotation"], "90° Counter Clockwise", None, "image.imageRotation.90ccw"),
    (&["Image", "Image Rotation"], "Arbitrary…", None, "image.rotation.arbitrary"),
    (&["Image", "Image Rotation"], "---", None, "---"),
    (&["Image", "Image Rotation"], "Flip Canvas Horizontal", None, "image.imageRotation.flipCanvasHorizontal"),
    (&["Image", "Image Rotation"], "Flip Canvas Vertical", None, "image.imageRotation.flipCanvasVertical"),
    (&["Image"], "Crop", None, "image.crop"),
    (&["Image"], "Trim…", None, "image.trim"),
    (&["Image"], "Reveal All", None, "image.revealAll"),
    (&["Image"], "---", None, "---"),
    (&["Image"], "Duplicate…", None, "image.duplicate"),
    (&["Image"], "Apply Image…", None, "image.applyImage"),
    (&["Image"], "Calculations…", None, "image.calculations"),
    (&["Image"], "---", None, "---"),
    (&["Image", "Variables"], "Define…", None, "image.variables.define"),
    (&["Image", "Variables"], "Data Sets…", None, "image.variables.dataSets"),
    (&["Image"], "Apply Data Set…", None, "image.applyDataSet"),
    (&["Image"], "---", None, "---"),
    (&["Image"], "Trap…", None, "image.trap"),
    (&["Image"], "---", None, "---"),
    (&["Image", "Analysis"], "Set Measurement Scale…", None, "image.analysis.setMeasurementScale"),
    (&["Image", "Analysis"], "Select Data Points…", None, "image.analysis.selectDataPoints"),
    (&["Image", "Analysis"], "---", None, "---"),
    (&["Image", "Analysis"], "Record Measurements", None, "image.analysis.recordMeasurements"),
    (&["Image", "Analysis"], "---", None, "---"),
    (&["Image", "Analysis"], "Ruler Tool", None, "image.analysis.rulerTool"),
    (&["Image", "Analysis"], "Count Tool", None, "image.analysis.countTool"),
    (&["Image", "Analysis"], "---", None, "---"),
    (&["Image", "Analysis"], "Place Scale Marker…", None, "image.analysis.placeScaleMarker"),
    (&["Layer", "New"], "Layer…", Some("Cmd+Shift+N"), "layer.new.layer"),
    (&["Layer", "New"], "Layer from Background…", None, "layer.new.layerFromBackground"),
    (&["Layer", "New"], "Group…", None, "layer.new.group"),
    (&["Layer", "New"], "Group from Layers…", None, "layer.new.groupFromLayers"),
    (&["Layer", "New"], "---", None, "---"),
    (&["Layer", "New"], "Artboard…", None, "layer.new.artboard"),
    (&["Layer", "New"], "Artboard from Group…", None, "layer.new.artboardFromGroup"),
    (&["Layer", "New"], "Artboard from Layers…", None, "layer.new.artboardFromLayers"),
    (&["Layer", "New"], "Frame from Layers", None, "layer.new.frameFromLayers"),
    (&["Layer", "New"], "---", None, "---"),
    (&["Layer", "New"], "Layer via Copy", Some("Cmd+J"), "layer.new.layerViaCopy"),
    (&["Layer", "New"], "Layer via Cut", Some("Cmd+Shift+J"), "layer.new.layerViaCut"),
    (&["Layer"], "Duplicate Layer…", None, "layer.duplicate"),
    (&["Layer", "Delete"], "Layer", None, "layer.delete"),
    (&["Layer", "Delete"], "Hidden Layers", None, "layer.delete.hiddenLayers"),
    (&["Layer"], "---", None, "---"),
    (&["Layer"], "Quick Export as PNG", Some("Cmd+Shift+'"), "layer.quickExportAsPng"),
    (&["Layer"], "Export As…", Some("Cmd+Alt+Shift+'"), "layer.exportAs"),
    (&["Layer"], "---", None, "---"),
    (&["Layer"], "Rename Layer", None, "layer.renameLayer"),
    (&["Layer", "Layer Style"], "Blending Options…", None, "layer.layerStyle.blendingOptions"),
    (&["Layer", "Layer Style"], "Bevel & Emboss…", None, "layer.layerStyle.bevelEmboss"),
    (&["Layer", "Layer Style"], "Stroke…", None, "layer.layerStyle.stroke"),
    (&["Layer", "Layer Style"], "Inner Shadow…", None, "layer.layerStyle.innerShadow"),
    (&["Layer", "Layer Style"], "Inner Glow…", None, "layer.layerStyle.innerGlow"),
    (&["Layer", "Layer Style"], "Satin…", None, "layer.layerStyle.satin"),
    (&["Layer", "Layer Style"], "Color Overlay…", None, "layer.layerStyle.colorOverlay"),
    (&["Layer", "Layer Style"], "Gradient Overlay…", None, "layer.layerStyle.gradientOverlay"),
    (&["Layer", "Layer Style"], "Pattern Overlay…", None, "layer.layerStyle.patternOverlay"),
    (&["Layer", "Layer Style"], "Outer Glow…", None, "layer.layerStyle.outerGlow"),
    (&["Layer", "Layer Style"], "Drop Shadow…", None, "layer.layerStyle.dropShadow"),
    (&["Layer", "Layer Style"], "---", None, "---"),
    (&["Layer", "Layer Style"], "Copy Layer Style", None, "layer.layerStyle.copyLayerStyle"),
    (&["Layer", "Layer Style"], "Paste Layer Style", None, "layer.layerStyle.pasteLayerStyle"),
    (&["Layer", "Layer Style"], "Clear Layer Style", None, "layer.layerStyle.clear"),
    (&["Layer", "Layer Style"], "---", None, "---"),
    (&["Layer", "Layer Style"], "Global Light…", None, "layer.layerStyle.globalLight"),
    (&["Layer", "Layer Style"], "Create Layer", None, "layer.layerStyle.createLayer"),
    (&["Layer", "Layer Style"], "Hide All Effects", None, "layer.layerStyle.hideAllEffects"),
    (&["Layer", "Layer Style"], "Scale Effects…", None, "layer.layerStyle.scaleEffects"),
    (&["Layer", "Smart Filter"], "Disable Smart Filters", None, "layer.smartFilter.disableSmartFilters"),
    (&["Layer", "Smart Filter"], "---", None, "---"),
    (&["Layer", "Smart Filter"], "Delete Filter Mask", None, "layer.smartFilter.deleteFilterMask"),
    (&["Layer", "Smart Filter"], "Disable Filter Mask", None, "layer.smartFilter.disableFilterMask"),
    (&["Layer", "Smart Filter"], "Blending Options…", None, "layer.smartFilter.blendingOptions"),
    (&["Layer", "Smart Filter"], "---", None, "---"),
    (&["Layer", "Smart Filter"], "Clear Smart Filters", None, "layer.smartFilter.clearSmartFilters"),
    (&["Layer"], "---", None, "---"),
    (&["Layer", "New Fill Layer"], "Solid Color…", None, "layer.newFillLayer.solidColor"),
    (&["Layer", "New Fill Layer"], "Gradient…", None, "layer.newFillLayer.gradient"),
    (&["Layer", "New Fill Layer"], "Pattern…", None, "layer.newFillLayer.pattern"),
    (&["Layer", "New Adjustment Layer"], "Brightness/Contrast…", None, "layer.newAdjustmentLayer.brightnessContrast"),
    (&["Layer", "New Adjustment Layer"], "Levels…", None, "layer.newAdjustmentLayer.levels"),
    (&["Layer", "New Adjustment Layer"], "Curves…", None, "layer.newAdjustmentLayer.curves"),
    (&["Layer", "New Adjustment Layer"], "Exposure…", None, "layer.newAdjustmentLayer.exposure"),
    (&["Layer", "New Adjustment Layer"], "Vibrance…", None, "layer.newAdjustmentLayer.vibrance"),
    (&["Layer", "New Adjustment Layer"], "Hue/Saturation…", None, "layer.newAdjustmentLayer.hueSaturation"),
    (&["Layer", "New Adjustment Layer"], "Color Balance…", None, "layer.newAdjustmentLayer.colorBalance"),
    (&["Layer", "New Adjustment Layer"], "Black & White…", None, "layer.newAdjustmentLayer.blackWhite"),
    (&["Layer", "New Adjustment Layer"], "Photo Filter…", None, "layer.newAdjustmentLayer.photoFilter"),
    (&["Layer", "New Adjustment Layer"], "Channel Mixer…", None, "layer.newAdjustmentLayer.channelMixer"),
    (&["Layer", "New Adjustment Layer"], "Color Lookup…", None, "layer.newAdjustmentLayer.colorLookup"),
    (&["Layer", "New Adjustment Layer"], "---", None, "---"),
    (&["Layer", "New Adjustment Layer"], "Invert…", None, "layer.newAdjustmentLayer.invert"),
    (&["Layer", "New Adjustment Layer"], "Posterize…", None, "layer.newAdjustmentLayer.posterize"),
    (&["Layer", "New Adjustment Layer"], "Threshold…", None, "layer.newAdjustmentLayer.threshold"),
    (&["Layer", "New Adjustment Layer"], "Gradient Map…", None, "layer.newAdjustmentLayer.gradientMap"),
    (&["Layer", "New Adjustment Layer"], "Selective Color…", None, "layer.newAdjustmentLayer.selectiveColor"),
    (&["Layer"], "Layer Content Options…", None, "layer.layerContentOptions"),
    (&["Layer"], "---", None, "---"),
    (&["Layer", "Layer Mask"], "Reveal All", None, "layer.layerMask.revealAll"),
    (&["Layer", "Layer Mask"], "Hide All", None, "layer.layerMask.hideAll"),
    (&["Layer", "Layer Mask"], "---", None, "---"),
    (&["Layer", "Layer Mask"], "Reveal Selection", None, "layer.layerMask.revealSelection"),
    (&["Layer", "Layer Mask"], "Hide Selection", None, "layer.layerMask.hideSelection"),
    (&["Layer", "Layer Mask"], "From Transparency", None, "layer.layerMask.fromTransparency"),
    (&["Layer", "Layer Mask"], "---", None, "---"),
    (&["Layer", "Layer Mask"], "Delete", None, "layer.layerMask.delete"),
    (&["Layer", "Layer Mask"], "Apply", None, "layer.layerMask.apply"),
    (&["Layer", "Layer Mask"], "---", None, "---"),
    (&["Layer", "Layer Mask"], "Enable Layer Mask", None, "layer.layerMask.enabled"),
    (&["Layer", "Layer Mask"], "Link Layer Mask", None, "layer.layerMask.linked"),
    (&["Layer"], "Mask All Objects", None, "layer.maskAllObjects"),
    (&["Layer", "Vector Mask"], "Reveal All", None, "layer.vectorMask.revealAll"),
    (&["Layer", "Vector Mask"], "Hide All", None, "layer.vectorMask.hideAll"),
    (&["Layer", "Vector Mask"], "Current Path", None, "layer.vectorMask.currentPath"),
    (&["Layer", "Vector Mask"], "---", None, "---"),
    (&["Layer", "Vector Mask"], "Delete", None, "layer.vectorMask.delete"),
    (&["Layer", "Vector Mask"], "---", None, "---"),
    (&["Layer", "Vector Mask"], "Enable Vector Mask", None, "layer.vectorMask.enabled"),
    (&["Layer", "Vector Mask"], "Link Vector Mask", None, "layer.vectorMask.linked"),
    (&["Layer"], "Create Clipping Mask", Some("Cmd+Alt+G"), "layer.createClippingMask"),
    (&["Layer"], "---", None, "---"),
    (&["Layer", "Smart Objects"], "Convert to Smart Object", None, "layer.smartObjects.convertToSmartObject"),
    (&["Layer", "Smart Objects"], "New Smart Object via Copy", None, "layer.smartObjects.newSmartObjectViaCopy"),
    (&["Layer", "Smart Objects"], "---", None, "---"),
    (&["Layer", "Smart Objects"], "Reveal in Finder", None, "layer.smartObjects.revealInFinder"),
    (&["Layer", "Smart Objects"], "---", None, "---"),
    (&["Layer", "Smart Objects"], "Update Modified Content", None, "layer.smartObjects.updateModifiedContent"),
    (&["Layer", "Smart Objects"], "Update All Modified Content", None, "layer.smartObjects.updateAllModifiedContent"),
    (&["Layer", "Smart Objects"], "---", None, "---"),
    (&["Layer", "Smart Objects"], "Edit Contents", None, "layer.smartObjects.editContents"),
    (&["Layer", "Smart Objects"], "Relink to File…", None, "layer.smartObjects.relinkToFile"),
    (&["Layer", "Smart Objects"], "Replace Contents…", None, "layer.smartObjects.replaceContents"),
    (&["Layer", "Smart Objects"], "Export Contents…", None, "layer.smartObjects.exportContents"),
    (&["Layer", "Smart Objects"], "---", None, "---"),
    (&["Layer", "Smart Objects"], "Convert to Linked…", None, "layer.smartObjects.convertToLinked"),
    (&["Layer", "Smart Objects"], "Convert to Embedded", None, "layer.smartObjects.convertToEmbedded"),
    (&["Layer", "Smart Objects"], "Convert to Layers", None, "layer.smartObjects.convertToLayers"),
    (&["Layer", "Smart Objects"], "---", None, "---"),
    (&["Layer", "Smart Objects", "Stack Mode"], "Entropy", None, "layer.smartObjects.stackMode.entropy"),
    (&["Layer", "Smart Objects", "Stack Mode"], "Kurtosis", None, "layer.smartObjects.stackMode.kurtosis"),
    (&["Layer", "Smart Objects", "Stack Mode"], "Maximum", None, "layer.smartObjects.stackMode.maximum"),
    (&["Layer", "Smart Objects", "Stack Mode"], "Mean", None, "layer.smartObjects.stackMode.mean"),
    (&["Layer", "Smart Objects", "Stack Mode"], "Median", None, "layer.smartObjects.stackMode.median"),
    (&["Layer", "Smart Objects", "Stack Mode"], "Minimum", None, "layer.smartObjects.stackMode.minimum"),
    (&["Layer", "Smart Objects", "Stack Mode"], "Range", None, "layer.smartObjects.stackMode.range"),
    (&["Layer", "Smart Objects", "Stack Mode"], "Skewness", None, "layer.smartObjects.stackMode.skewness"),
    (&["Layer", "Smart Objects", "Stack Mode"], "Standard Deviation", None, "layer.smartObjects.stackMode.standardDeviation"),
    (&["Layer", "Smart Objects", "Stack Mode"], "Summation", None, "layer.smartObjects.stackMode.summation"),
    (&["Layer", "Smart Objects", "Stack Mode"], "Variance", None, "layer.smartObjects.stackMode.variance"),
    (&["Layer", "Smart Objects"], "---", None, "---"),
    (&["Layer", "Smart Objects"], "Rasterize", None, "layer.smartObjects.rasterize"),
    (&["Layer", "Smart Objects"], "---", None, "---"),
    (&["Layer", "Smart Objects"], "Warp", None, "layer.smartObjects.warp"),
    (&["Layer", "Smart Objects"], "Perspective Warp", None, "layer.smartObjects.perspectiveWarp"),
    (&["Layer", "Smart Objects"], "Puppet Warp", None, "layer.smartObjects.puppetWarp"),
    (&["Layer", "Video Layers"], "New Blank Video Layer", None, "layer.videoLayers.newBlankVideoLayer"),
    (&["Layer", "Video Layers"], "New Video Layer from File…", None, "layer.videoLayers.newVideoLayerFromFile"),
    (&["Layer", "Video Layers"], "---", None, "---"),
    (&["Layer", "Video Layers"], "Insert Blank Frame", None, "layer.videoLayers.insertBlankFrame"),
    (&["Layer", "Video Layers"], "Duplicate Frame", None, "layer.videoLayers.duplicateFrame"),
    (&["Layer", "Video Layers"], "Delete Frame", None, "layer.videoLayers.deleteFrame"),
    (&["Layer", "Video Layers"], "---", None, "---"),
    (&["Layer", "Video Layers"], "Replace Footage…", None, "layer.videoLayers.replaceFootage"),
    (&["Layer", "Video Layers"], "Interpret Footage…", None, "layer.videoLayers.interpretFootage"),
    (&["Layer", "Video Layers"], "---", None, "---"),
    (&["Layer", "Video Layers"], "Show Altered Video", None, "layer.videoLayers.showAlteredVideo"),
    (&["Layer", "Video Layers"], "---", None, "---"),
    (&["Layer", "Video Layers"], "Restore Frame", None, "layer.videoLayers.restoreFrame"),
    (&["Layer", "Video Layers"], "Restore All Frames", None, "layer.videoLayers.restoreAllFrames"),
    (&["Layer", "Video Layers"], "Reload Frame", None, "layer.videoLayers.reloadFrame"),
    (&["Layer", "Video Layers"], "---", None, "---"),
    (&["Layer", "Video Layers"], "Rasterize", None, "layer.videoLayers.rasterize"),
    (&["Layer", "Rasterize"], "Type", None, "layer.rasterize.type"),
    (&["Layer", "Rasterize"], "Shape", None, "layer.rasterize.shape"),
    (&["Layer", "Rasterize"], "Fill Content", None, "layer.rasterize.fillContent"),
    (&["Layer", "Rasterize"], "Vector Mask", None, "layer.rasterize.vectorMask"),
    (&["Layer", "Rasterize"], "Smart Object", None, "layer.rasterize.smartObject"),
    (&["Layer", "Rasterize"], "Video", None, "layer.rasterize.video"),
    (&["Layer", "Rasterize"], "---", None, "---"),
    (&["Layer", "Rasterize"], "Layer", None, "layer.rasterize.layer"),
    (&["Layer", "Rasterize"], "All Layers", None, "layer.rasterize.allLayers"),
    (&["Layer"], "---", None, "---"),
    (&["Layer"], "New Layer Based Slice", None, "layer.newLayerBasedSlice"),
    (&["Layer"], "---", None, "---"),
    (&["Layer"], "Group Layers", None, "layer.groupLayers"),
    (&["Layer"], "Ungroup Layers", None, "layer.ungroupLayers"),
    (&["Layer"], "Hide Layers", None, "layer.hideLayers"),
    (&["Layer"], "---", None, "---"),
    (&["Layer", "Arrange"], "Bring to Front", Some("Cmd+Shift+]"), "layer.arrange.bringToFront"),
    (&["Layer", "Arrange"], "Bring Forward", Some("Cmd+]"), "layer.arrange.bringForward"),
    (&["Layer", "Arrange"], "Send Backward", Some("Cmd+["), "layer.arrange.sendBackward"),
    (&["Layer", "Arrange"], "Send to Back", Some("Cmd+Shift+["), "layer.arrange.sendToBack"),
    (&["Layer", "Arrange"], "---", None, "---"),
    (&["Layer", "Arrange"], "Reverse", None, "layer.arrange.reverse"),
    (&["Layer", "Combine Shapes"], "Unite Shapes", None, "layer.combineShapes.unite"),
    (&["Layer", "Combine Shapes"], "Subtract Front Shape", None, "layer.combineShapes.subtractFrontShape"),
    (&["Layer", "Combine Shapes"], "Intersect Shape Areas", None, "layer.combineShapes.intersectShapeAreas"),
    (&["Layer", "Combine Shapes"], "Exclude Overlapping Shapes", None, "layer.combineShapes.excludeOverlappingShapes"),
    (&["Layer", "Combine Shapes"], "---", None, "---"),
    (&["Layer", "Combine Shapes"], "Merge Shape Components", None, "layer.combineShapes.mergeShapeComponents"),
    (&["Layer", "Align"], "Top Edges", None, "layer.align.topEdges"),
    (&["Layer", "Align"], "Vertical Centers", None, "layer.align.verticalCenters"),
    (&["Layer", "Align"], "Bottom Edges", None, "layer.align.bottomEdges"),
    (&["Layer", "Align"], "---", None, "---"),
    (&["Layer", "Align"], "Left Edges", None, "layer.align.leftEdges"),
    (&["Layer", "Align"], "Horizontal Centers", None, "layer.align.horizontalCenters"),
    (&["Layer", "Align"], "Right Edges", None, "layer.align.rightEdges"),
    (&["Layer", "Distribute"], "Top Edges", None, "layer.distribute.topEdges"),
    (&["Layer", "Distribute"], "Vertical Centers", None, "layer.distribute.verticalCenters"),
    (&["Layer", "Distribute"], "Bottom Edges", None, "layer.distribute.bottomEdges"),
    (&["Layer", "Distribute"], "---", None, "---"),
    (&["Layer", "Distribute"], "Left Edges", None, "layer.distribute.leftEdges"),
    (&["Layer", "Distribute"], "Horizontal Centers", None, "layer.distribute.horizontalCenters"),
    (&["Layer", "Distribute"], "Right Edges", None, "layer.distribute.rightEdges"),
    (&["Layer", "Distribute"], "---", None, "---"),
    (&["Layer", "Distribute"], "Horizontally", None, "layer.distribute.horizontally"),
    (&["Layer", "Distribute"], "Vertically", None, "layer.distribute.vertically"),
    (&["Layer"], "---", None, "---"),
    (&["Layer"], "Lock Layers…", None, "layer.lockLayers"),
    (&["Layer"], "---", None, "---"),
    (&["Layer"], "Link Layers", None, "layer.linkLayers"),
    (&["Layer"], "Select Linked Layers", None, "layer.selectLinkedLayers"),
    (&["Layer"], "---", None, "---"),
    (&["Layer"], "Merge Layers", Some("Cmd+E"), "layer.mergeLayers"),
    (&["Layer"], "Merge Visible", Some("Cmd+Shift+E"), "layer.mergeVisible"),
    (&["Layer"], "Flatten Image", None, "layer.flattenImage"),
    (&["Layer"], "---", None, "---"),
    (&["Layer", "Matting"], "Color Decontaminate…", None, "layer.matting.colorDecontaminate"),
    (&["Layer", "Matting"], "Defringe…", None, "layer.matting.defringe"),
    (&["Layer", "Matting"], "Remove Black Matte", None, "layer.matting.removeBlackMatte"),
    (&["Layer", "Matting"], "Remove White Matte", None, "layer.matting.removeWhiteMatte"),
    (&["Type", "Panels"], "Character Panel", None, "type.panels.character"),
    (&["Type", "Panels"], "Paragraph Panel", None, "type.panels.paragraph"),
    (&["Type", "Panels"], "Glyphs Panel", None, "type.panels.glyphs"),
    (&["Type", "Panels"], "Character Styles Panel", None, "type.panels.characterStyles"),
    (&["Type", "Panels"], "Paragraph Styles Panel", None, "type.panels.paragraphStyles"),
    (&["Type"], "---", None, "---"),
    (&["Type", "Anti-Alias"], "Sharp", None, "type.antiAlias.sharp"),
    (&["Type", "Anti-Alias"], "Crisp", None, "type.antiAlias.crisp"),
    (&["Type", "Anti-Alias"], "Strong", None, "type.antiAlias.strong"),
    (&["Type", "Anti-Alias"], "Smooth", None, "type.antiAlias.smooth"),
    (&["Type", "Anti-Alias"], "---", None, "---"),
    (&["Type", "Anti-Alias"], "Windows LCD", None, "type.antiAlias.windowsLcd"),
    (&["Type", "Anti-Alias"], "Windows", None, "type.antiAlias.windows"),
    (&["Type", "Orientation"], "Horizontal", None, "type.orientation.horizontal"),
    (&["Type", "Orientation"], "Vertical", None, "type.orientation.vertical"),
    (&["Type", "OpenType"], "Standard Ligatures", None, "type.openType.standardLigatures"),
    (&["Type", "OpenType"], "Contextual Alternates", None, "type.openType.contextualAlternates"),
    (&["Type", "OpenType"], "Discretionary Ligatures", None, "type.openType.discretionaryLigatures"),
    (&["Type", "OpenType"], "Swash", None, "type.openType.swash"),
    (&["Type", "OpenType"], "Oldstyle", None, "type.openType.oldstyle"),
    (&["Type", "OpenType"], "Stylistic Alternates", None, "type.openType.stylisticAlternates"),
    (&["Type", "OpenType"], "Titling Alternates", None, "type.openType.titlingAlternates"),
    (&["Type", "OpenType"], "Ornaments", None, "type.openType.ornaments"),
    (&["Type", "OpenType"], "Ordinals", None, "type.openType.ordinals"),
    (&["Type", "OpenType"], "Fractions", None, "type.openType.fractions"),
    (&["Type"], "---", None, "---"),
    (&["Type"], "Create Work Path", None, "type.createWorkPath"),
    (&["Type"], "Convert to Shape", None, "type.convertToShape"),
    (&["Type"], "---", None, "---"),
    (&["Type"], "Rasterize Type Layer", None, "type.rasterizeTypeLayer"),
    (&["Type"], "---", None, "---"),
    (&["Type"], "Convert to Paragraph Text", None, "type.convertToParagraphText"),
    (&["Type"], "Convert to Point Text", None, "type.convertToPointText"),
    (&["Type"], "Warp Text…", None, "type.warpText"),
    (&["Type"], "---", None, "---"),
    (&["Type", "Font Preview Size"], "Small", None, "type.fontPreviewSize.small"),
    (&["Type", "Font Preview Size"], "Medium", None, "type.fontPreviewSize.medium"),
    (&["Type", "Font Preview Size"], "Large", None, "type.fontPreviewSize.large"),
    (&["Type", "Font Preview Size"], "Extra Large", None, "type.fontPreviewSize.extraLarge"),
    (&["Type", "Font Preview Size"], "Huge", None, "type.fontPreviewSize.huge"),
    (&["Type", "Language Options"], "Default Features", None, "type.languageOptions.defaultFeatures"),
    (&["Type", "Language Options"], "East Asian Features", None, "type.languageOptions.eastAsianFeatures"),
    (&["Type", "Language Options"], "Middle Eastern Features", None, "type.languageOptions.middleEasternFeatures"),
    (&["Type", "Language Options"], "---", None, "---"),
    (&["Type", "Language Options"], "Middle Eastern & South Asian Composer", None, "type.languageOptions.middleEasternAndSouthAsianComposer"),
    (&["Type"], "---", None, "---"),
    (&["Type"], "Update All Text Layers", None, "type.updateAllTextLayers"),
    (&["Type"], "Replace All Missing Fonts", None, "type.replaceAllMissingFonts"),
    (&["Type"], "Resolve Missing Fonts…", None, "type.resolveMissingFonts"),
    (&["Type"], "---", None, "---"),
    (&["Type"], "Paste Lorem Ipsum", None, "type.pasteLoremIpsum"),
    (&["Type"], "---", None, "---"),
    (&["Type"], "Load Default Type Styles", None, "type.loadDefaultTypeStyles"),
    (&["Type"], "Save Default Type Styles", None, "type.saveDefaultTypeStyles"),
    (&["Select"], "All", Some("Cmd+A"), "select.all"),
    (&["Select"], "Deselect", Some("Cmd+D"), "select.deselect"),
    (&["Select"], "Reselect", Some("Cmd+Shift+D"), "select.reselect"),
    (&["Select"], "Inverse Selection", None, "select.inverse"),
    (&["Select"], "Convert to Shape", None, "select.convertToShape"),
    (&["Select"], "---", None, "---"),
    (&["Select"], "All Layers", Some("Cmd+Alt+A"), "select.allLayers"),
    (&["Select"], "Deselect Layers", None, "select.deselectLayers"),
    (&["Select"], "Find Layers", Some("Cmd+Alt+Shift+F"), "select.findLayers"),
    (&["Select"], "Isolate Layers", None, "select.isolateLayers"),
    (&["Select"], "---", None, "---"),
    (&["Select"], "Color Range…", None, "select.colorRange"),
    (&["Select"], "Focus Area…", None, "select.focusArea"),
    (&["Select"], "Subject", None, "select.subject"),
    (&["Select"], "Sky", None, "select.sky"),
    (&["Select"], "Select and Mask…", None, "select.selectAndMask"),
    (&["Select"], "---", None, "---"),
    (&["Select", "Modify"], "Border…", None, "select.modify.border"),
    (&["Select", "Modify"], "Smooth…", None, "select.modify.smooth"),
    (&["Select", "Modify"], "Expand…", None, "select.modify.expand"),
    (&["Select", "Modify"], "Contract…", None, "select.modify.contract"),
    (&["Select", "Modify"], "Feather…", Some("Shift+F6"), "select.modify.feather"),
    (&["Select"], "---", None, "---"),
    (&["Select"], "Grow", None, "select.grow"),
    (&["Select"], "Similar", None, "select.similar"),
    (&["Select"], "---", None, "---"),
    (&["Select"], "Transform Selection", None, "select.transformSelection"),
    (&["Select"], "---", None, "---"),
    (&["Select"], "Edit in Quick Mask Mode", Some("Q"), "select.editInQuickMaskMode"),
    (&["Select"], "---", None, "---"),
    (&["Select"], "Load Selection…", None, "select.loadSelection"),
    (&["Select"], "Save Selection…", None, "select.saveSelection"),
    (&["Filter"], "Last Filter", Some("Cmd+Alt+F"), "filter.lastFilter"),
    (&["Filter"], "---", None, "---"),
    (&["Filter"], "Convert for Smart Filters", None, "filter.convertForSmartFilters"),
    (&["Filter"], "---", None, "---"),
    (&["Filter"], "Filter Gallery…", None, "filter.filterGallery"),
    (&["Filter"], "Camera Raw Filter…", Some("Cmd+Shift+A"), "filter.cameraRaw"),
    (&["Filter"], "Adaptive Wide Angle…", Some("Cmd+Alt+Shift+A"), "filter.adaptiveWideAngle"),
    (&["Filter"], "Lens Correction…", Some("Cmd+Shift+R"), "filter.lensCorrection"),
    (&["Filter"], "Liquify…", Some("Cmd+Shift+X"), "filter.liquify"),
    (&["Filter"], "Vanishing Point…", Some("Cmd+Alt+V"), "filter.vanishingPoint"),
    (&["Filter"], "---", None, "---"),
    (&["Filter", "Blur"], "Average", None, "filter.blur.average"),
    (&["Filter", "Blur"], "Blur", None, "filter.blur.blur"),
    (&["Filter", "Blur"], "Blur More", None, "filter.blur.blurMore"),
    (&["Filter", "Blur"], "Box Blur…", None, "filter.blur.boxBlur"),
    (&["Filter", "Blur"], "Gaussian Blur…", None, "filter.blur.gaussianBlur"),
    (&["Filter", "Blur"], "Lens Blur…", None, "filter.blur.lensBlur"),
    (&["Filter", "Blur"], "Motion Blur…", None, "filter.blur.motionBlur"),
    (&["Filter", "Blur"], "Radial Blur…", None, "filter.blur.radialBlur"),
    (&["Filter", "Blur"], "Shape Blur…", None, "filter.blur.shapeBlur"),
    (&["Filter", "Blur"], "Smart Blur…", None, "filter.blur.smartBlur"),
    (&["Filter", "Blur"], "Surface Blur…", None, "filter.blur.surfaceBlur"),
    (&["Filter", "Blur Gallery"], "Field Blur…", None, "filter.blurGallery.fieldBlur"),
    (&["Filter", "Blur Gallery"], "Iris Blur…", None, "filter.blurGallery.irisBlur"),
    (&["Filter", "Blur Gallery"], "Tilt-Shift…", None, "filter.blurGallery.tiltShift"),
    (&["Filter", "Blur Gallery"], "Path Blur…", None, "filter.blurGallery.pathBlur"),
    (&["Filter", "Blur Gallery"], "Spin Blur…", None, "filter.blurGallery.spinBlur"),
    (&["Filter", "Distort"], "Displace…", None, "filter.distort.displace"),
    (&["Filter", "Distort"], "Pinch…", None, "filter.distort.pinch"),
    (&["Filter", "Distort"], "Polar Coordinates…", None, "filter.distort.polarCoordinates"),
    (&["Filter", "Distort"], "Ripple…", None, "filter.distort.ripple"),
    (&["Filter", "Distort"], "Shear…", None, "filter.distort.shear"),
    (&["Filter", "Distort"], "Spherize…", None, "filter.distort.spherize"),
    (&["Filter", "Distort"], "Twirl…", None, "filter.distort.twirl"),
    (&["Filter", "Distort"], "Wave…", None, "filter.distort.wave"),
    (&["Filter", "Distort"], "ZigZag…", None, "filter.distort.zigZag"),
    (&["Filter", "Noise"], "Add Noise…", None, "filter.noise.addNoise"),
    (&["Filter", "Noise"], "Despeckle", None, "filter.noise.despeckle"),
    (&["Filter", "Noise"], "Dust & Scratches…", None, "filter.noise.dustAndScratches"),
    (&["Filter", "Noise"], "Median…", None, "filter.noise.median"),
    (&["Filter", "Noise"], "Reduce Noise…", None, "filter.noise.reduceNoise"),
    (&["Filter", "Pixelate"], "Color Halftone…", None, "filter.pixelate.colorHalftone"),
    (&["Filter", "Pixelate"], "Crystallize…", None, "filter.pixelate.crystallize"),
    (&["Filter", "Pixelate"], "Facet", None, "filter.pixelate.facet"),
    (&["Filter", "Pixelate"], "Fragment", None, "filter.pixelate.fragment"),
    (&["Filter", "Pixelate"], "Mezzotint…", None, "filter.pixelate.mezzotint"),
    (&["Filter", "Pixelate"], "Mosaic…", None, "filter.pixelate.mosaic"),
    (&["Filter", "Pixelate"], "Pointillize…", None, "filter.pixelate.pointillize"),
    (&["Filter", "Render"], "Flame…", None, "filter.render.flame"),
    (&["Filter", "Render"], "Picture Frame…", None, "filter.render.pictureFrame"),
    (&["Filter", "Render"], "Tree…", None, "filter.render.tree"),
    (&["Filter", "Render"], "---", None, "---"),
    (&["Filter", "Render"], "Clouds", None, "filter.render.clouds"),
    (&["Filter", "Render"], "Difference Clouds", None, "filter.render.differenceClouds"),
    (&["Filter", "Render"], "Fibers…", None, "filter.render.fibers"),
    (&["Filter", "Render"], "Lens Flare…", None, "filter.render.lensFlare"),
    (&["Filter", "Render"], "Lighting Effects…", None, "filter.render.lightingEffects"),
    (&["Filter", "Sharpen"], "Sharpen", None, "filter.sharpen.sharpen"),
    (&["Filter", "Sharpen"], "Sharpen Edges", None, "filter.sharpen.sharpenEdges"),
    (&["Filter", "Sharpen"], "Sharpen More", None, "filter.sharpen.sharpenMore"),
    (&["Filter", "Sharpen"], "Smart Sharpen…", None, "filter.sharpen.smartSharpen"),
    (&["Filter", "Sharpen"], "Unsharp Mask…", None, "filter.sharpen.unsharpMask"),
    (&["Filter", "Stylize"], "Diffuse…", None, "filter.stylize.diffuse"),
    (&["Filter", "Stylize"], "Emboss…", None, "filter.stylize.emboss"),
    (&["Filter", "Stylize"], "Extrude…", None, "filter.stylize.extrude"),
    (&["Filter", "Stylize"], "Find Edges", None, "filter.stylize.findEdges"),
    (&["Filter", "Stylize"], "Oil Paint…", None, "filter.stylize.oilPaint"),
    (&["Filter", "Stylize"], "Solarize", None, "filter.stylize.solarize"),
    (&["Filter", "Stylize"], "Tiles…", None, "filter.stylize.tiles"),
    (&["Filter", "Stylize"], "Trace Contour…", None, "filter.stylize.traceContour"),
    (&["Filter", "Stylize"], "Wind…", None, "filter.stylize.wind"),
    (&["Filter", "Video"], "De-Interlace…", None, "filter.video.deInterlace"),
    (&["Filter", "Video"], "NTSC Colors", None, "filter.video.ntscColors"),
    (&["Filter", "Other…"], "Custom…", None, "filter.other.custom"),
    (&["Filter", "Other…"], "HSB/HSL", None, "filter.other.hsbHsl"),
    (&["Filter", "Other…"], "High Pass…", None, "filter.other.highPass"),
    (&["Filter", "Other…"], "Maximum…", None, "filter.other.maximum"),
    (&["Filter", "Other…"], "Minimum…", None, "filter.other.minimum"),
    (&["Filter", "Other…"], "Offset…", None, "filter.other.offset"),
    (&["View", "Proof Setup"], "Custom…", None, "view.proofSetup.custom"),
    (&["View", "Proof Setup"], "---", None, "---"),
    (&["View", "Proof Setup"], "Working CMYK", None, "view.proofSetup.workingCmyk"),
    (&["View", "Proof Setup"], "Working Cyan Plate", None, "view.proofSetup.workingCyanPlate"),
    (&["View", "Proof Setup"], "Working Magenta Plate", None, "view.proofSetup.workingMagentaPlate"),
    (&["View", "Proof Setup"], "Working Yellow Plate", None, "view.proofSetup.workingYellowPlate"),
    (&["View", "Proof Setup"], "Working Black Plate", None, "view.proofSetup.workingBlackPlate"),
    (&["View", "Proof Setup"], "Working CMY Plate", None, "view.proofSetup.workingCmyPlate"),
    (&["View", "Proof Setup"], "---", None, "---"),
    (&["View", "Proof Setup"], "Legacy Macintosh RGB", None, "view.proofSetup.legacyMacintoshRgb"),
    (&["View", "Proof Setup"], "Internet Standard RGB", None, "view.proofSetup.internetStandardRgb"),
    (&["View", "Proof Setup"], "Monitor RGB", None, "view.proofSetup.monitorRgb"),
    (&["View", "Proof Setup"], "---", None, "---"),
    (&["View", "Proof Setup"], "Color Blindness — Protanopia-type", None, "view.proofSetup.colorBlindnessProtanopia"),
    (&["View", "Proof Setup"], "Color Blindness — Deuteranopia-type", None, "view.proofSetup.colorBlindnessDeuteranopia"),
    (&["View"], "Proof Colors", Some("Cmd+Y"), "view.proofColors"),
    (&["View"], "Gamut Warning", Some("Cmd+Shift+Y"), "view.gamutWarning"),
    (&["View"], "---", None, "---"),
    (&["View", "Pixel Aspect Ratio"], "Custom Pixel Aspect Ratio…", None, "view.pixelAspectRatio.custom"),
    (&["View", "Pixel Aspect Ratio"], "---", None, "---"),
    (&["View", "Pixel Aspect Ratio"], "Square", None, "view.pixelAspectRatio.square"),
    (&["View", "Pixel Aspect Ratio"], "D1/DV NTSC (0.91)", None, "view.pixelAspectRatio.d1DvNtsc"),
    (&["View", "Pixel Aspect Ratio"], "D1/DV PAL (1.09)", None, "view.pixelAspectRatio.d1DvPal"),
    (&["View", "Pixel Aspect Ratio"], "D1/DV NTSC Widescreen (1.21)", None, "view.pixelAspectRatio.d1DvNtscWidescreen"),
    (&["View", "Pixel Aspect Ratio"], "HDV 1080/DVCPRO HD 720 (1.33)", None, "view.pixelAspectRatio.hdv1080"),
    (&["View", "Pixel Aspect Ratio"], "D1/DV PAL Widescreen (1.46)", None, "view.pixelAspectRatio.d1DvPalWidescreen"),
    (&["View", "Pixel Aspect Ratio"], "DVCPRO HD 1080/HDV 1080 (1.5)", None, "view.pixelAspectRatio.dvcproHd1080"),
    (&["View", "Pixel Aspect Ratio"], "Anamorphic 2:1 (2)", None, "view.pixelAspectRatio.anamorphic2To1"),
    (&["View"], "Pixel Aspect Ratio Correction", None, "view.pixelAspectRatioCorrection"),
    (&["View"], "---", None, "---"),
    (&["View"], "32-bit Preview Options…", None, "view.thirtyTwoBitPreviewOptions"),
    (&["View"], "---", None, "---"),
    (&["View"], "Zoom In", Some("Cmd+="), "view.zoomIn"),
    (&["View"], "Zoom Out", Some("Cmd+-"), "view.zoomOut"),
    (&["View"], "Fit on Screen", None, "view.fitOnScreen"),
    (&["View"], "Fit Layer(s) on Screen", None, "view.fitLayersOnScreen"),
    (&["View"], "Fit Artboard on Screen", None, "view.fitArtboardOnScreen"),
    (&["View"], "100%", Some("Cmd+1"), "view.actualPixels"),
    (&["View"], "200%", None, "view.twoHundredPercent"),
    (&["View"], "Print Size", None, "view.printSize"),
    (&["View"], "---", None, "---"),
    (&["View"], "Flip Horizontal", None, "view.flipHorizontal"),
    (&["View", "Screen Mode"], "Standard Screen Mode", None, "view.screenMode.standard"),
    (&["View", "Screen Mode"], "Full Screen Mode With Menu Bar", None, "view.screenMode.fullScreenWithMenuBar"),
    (&["View", "Screen Mode"], "Full Screen Mode", None, "view.screenMode.fullScreen"),
    (&["View"], "---", None, "---"),
    (&["View"], "Extras", Some("Cmd+H"), "view.extras"),
    (&["View", "Show"], "Layer Edges", None, "view.show.layerEdges"),
    (&["View", "Show"], "Selection Edges", None, "view.show.selectionEdges"),
    (&["View", "Show"], "Target Path", Some("Cmd+Shift+H"), "view.show.targetPath"),
    (&["View", "Show"], "Grid", Some("Cmd+'"), "view.show.grid"),
    (&["View", "Show"], "Guides", Some("Cmd+;"), "view.show.guides"),
    (&["View", "Show"], "Canvas Guides", None, "view.show.canvasGuides"),
    (&["View", "Show"], "Artboard Guides", None, "view.show.artboardGuides"),
    (&["View", "Show"], "Count", None, "view.show.count"),
    (&["View", "Show"], "Smart Guides", None, "view.show.smartGuides"),
    (&["View", "Show"], "Slices", None, "view.show.slices"),
    (&["View", "Show"], "Notes", None, "view.show.notes"),
    (&["View", "Show"], "Pixel Grid", None, "view.show.pixelGrid"),
    (&["View", "Show"], "Brush Preview", None, "view.show.brushPreview"),
    (&["View", "Show"], "Mesh", None, "view.show.mesh"),
    (&["View", "Show"], "Edit Pins", None, "view.show.editPins"),
    (&["View", "Show"], "---", None, "---"),
    (&["View", "Show"], "All", None, "view.show.all"),
    (&["View", "Show"], "Show Extras Options…", None, "view.show.showExtrasOptions"),
    (&["View"], "---", None, "---"),
    (&["View"], "Rulers", Some("Cmd+R"), "view.rulers"),
    (&["View"], "---", None, "---"),
    (&["View"], "Snap", Some("Cmd+Shift+;"), "view.snap"),
    (&["View", "Snap To"], "Guides", None, "view.snapTo.guides"),
    (&["View", "Snap To"], "Grid", None, "view.snapTo.grid"),
    (&["View", "Snap To"], "Layers", None, "view.snapTo.layers"),
    (&["View", "Snap To"], "Slices", None, "view.snapTo.slices"),
    (&["View", "Snap To"], "Document Bounds", None, "view.snapTo.documentBounds"),
    (&["View", "Snap To"], "---", None, "---"),
    (&["View", "Snap To"], "All", None, "view.snapTo.all"),
    (&["View"], "---", None, "---"),
    (&["View"], "Lock Guides", Some("Cmd+Alt+;"), "view.lockGuides"),
    (&["View"], "Clear Guides", None, "view.clearGuides"),
    (&["View"], "Clear Selected Artboard Guides", None, "view.clearSelectedArtboardGuides"),
    (&["View"], "Clear Canvas Guides", None, "view.clearCanvasGuides"),
    (&["View"], "New Guide…", None, "view.newGuide"),
    (&["View"], "New Guide Layout…", None, "view.newGuideLayout"),
    (&["View"], "New Guides From Shape", None, "view.newGuidesFromShape"),
    (&["View"], "---", None, "---"),
    (&["View"], "Lock Slices", None, "view.lockSlices"),
    (&["View"], "Clear Slices", None, "view.clearSlices"),
    (&["View"], "---", None, "---"),
    (&["View"], "Pattern Preview", None, "view.patternPreview"),
    (&["View"], "Pixel Art Preview", None, "view.pixelArtPreview"),
    (&["Window", "Arrange"], "Tile All Vertically", None, "window.arrange.tileAllVertically"),
    (&["Window", "Arrange"], "Tile All Horizontally", None, "window.arrange.tileAllHorizontally"),
    (&["Window", "Arrange"], "2-up Vertical", None, "window.arrange.twoUpVertical"),
    (&["Window", "Arrange"], "2-up Horizontal", None, "window.arrange.twoUpHorizontal"),
    (&["Window", "Arrange"], "3-up Vertical", None, "window.arrange.threeUpVertical"),
    (&["Window", "Arrange"], "3-up Horizontal", None, "window.arrange.threeUpHorizontal"),
    (&["Window", "Arrange"], "3-up Stacked", None, "window.arrange.threeUpStacked"),
    (&["Window", "Arrange"], "4-up", None, "window.arrange.fourUp"),
    (&["Window", "Arrange"], "6-up", None, "window.arrange.sixUp"),
    (&["Window", "Arrange"], "---", None, "---"),
    (&["Window", "Arrange"], "Consolidate All to Tabs", None, "window.arrange.consolidateAllToTabs"),
    (&["Window", "Arrange"], "Cascade", None, "window.arrange.cascade"),
    (&["Window", "Arrange"], "Tile", None, "window.arrange.tile"),
    (&["Window", "Arrange"], "---", None, "---"),
    (&["Window", "Arrange"], "Float in Window", None, "window.arrange.floatInWindow"),
    (&["Window", "Arrange"], "Float All in Windows", None, "window.arrange.floatAllInWindows"),
    (&["Window", "Arrange"], "---", None, "---"),
    (&["Window", "Arrange"], "New Window for Document", None, "window.arrange.newWindowForDocument"),
    (&["Window", "Arrange"], "---", None, "---"),
    (&["Window", "Arrange"], "Match Zoom", None, "window.arrange.matchZoom"),
    (&["Window", "Arrange"], "Match Location", None, "window.arrange.matchLocation"),
    (&["Window", "Arrange"], "Match Rotation", None, "window.arrange.matchRotation"),
    (&["Window", "Arrange"], "Match All", None, "window.arrange.matchAll"),
    (&["Window", "Workspace"], "Essentials", None, "window.workspace.essentials"),
    (&["Window", "Workspace"], "Photography", None, "window.workspace.photography"),
    (&["Window", "Workspace"], "Painting", None, "window.workspace.painting"),
    (&["Window", "Workspace"], "Pixel Art", None, "window.workspace.pixelArt"),
    (&["Window", "Workspace"], "Graphic and Web", None, "window.workspace.graphicAndWeb"),
    (&["Window", "Workspace"], "Motion", None, "window.workspace.motion"),
    (&["Window", "Workspace"], "---", None, "---"),
    (&["Window", "Workspace"], "Reset Workspace", None, "window.workspace.resetWorkspace"),
    (&["Window", "Workspace"], "New Workspace…", None, "window.workspace.newWorkspace"),
    (&["Window", "Workspace"], "Delete Workspace…", None, "window.workspace.deleteWorkspace"),
    (&["Window", "Workspace"], "---", None, "---"),
    (&["Window", "Workspace"], "Keyboard Shortcuts…", Some("Cmd+Alt+Shift+K"), "edit.keyboardShortcuts"),
    (&["Window", "Workspace"], "Lock Workspace", None, "window.workspace.lockWorkspace"),
    (&["Window"], "---", None, "---"),
    (&["Window"], "Actions", Some("Alt+F9"), "window.panel.actions"),
    (&["Window"], "Adjustments", None, "window.panel.adjustments"),
    (&["Window"], "Brush Settings", Some("F5"), "window.panel.brushSettings"),
    (&["Window"], "Brushes", None, "window.panel.brushes"),
    (&["Window"], "Channels", None, "window.panel.channels"),
    (&["Window"], "Character", None, "window.panel.character"),
    (&["Window"], "Character Styles", None, "window.panel.characterStyles"),
    (&["Window"], "Clone Source", None, "window.panel.cloneSource"),
    (&["Window"], "Color", Some("F6"), "window.panel.color"),
    (&["Window"], "Glyphs", None, "window.panel.glyphs"),
    (&["Window"], "Gradients", None, "window.panel.gradients"),
    (&["Window"], "Histogram", None, "window.panel.histogram"),
    (&["Window"], "History", None, "window.panel.history"),
    (&["Window"], "Info", Some("F8"), "window.panel.info"),
    (&["Window"], "Layer Comps", None, "window.panel.layerComps"),
    (&["Window"], "Layers", Some("F7"), "window.panel.layers"),
    (&["Window"], "Measurement Log", None, "window.panel.measurementLog"),
    (&["Window"], "Modifier Keys", None, "window.panel.modifierKeys"),
    (&["Window"], "Navigator", None, "window.panel.navigator"),
    (&["Window"], "Notes", None, "window.panel.notes"),
    (&["Window"], "Paragraph", None, "window.panel.paragraph"),
    (&["Window"], "Paragraph Styles", None, "window.panel.paragraphStyles"),
    (&["Window"], "Paths", None, "window.panel.paths"),
    (&["Window"], "Patterns", None, "window.panel.patterns"),
    (&["Window"], "Properties", None, "window.panel.properties"),
    (&["Window"], "Shapes", None, "window.panel.shapes"),
    (&["Window"], "Styles", None, "window.panel.styles"),
    (&["Window"], "Swatches", None, "window.panel.swatches"),
    (&["Window"], "Timeline", None, "window.panel.timeline"),
    (&["Window"], "Tool Presets", None, "window.panel.toolPresets"),
    (&["Window"], "---", None, "---"),
    (&["Window"], "Options", None, "window.panel.options"),
    (&["Window"], "Tools", None, "window.panel.tools"),
];
