#!/usr/bin/env python3
"""Offline generation: python scripts/engine_colour_data.py ENGINE_SOURCES.
Only stdlib; input archives are read-only. See licenses/rawler-NOTICE.md.
"""
import json, re, sys, tomllib, struct, hashlib
from pathlib import Path
src = Path(sys.argv[1])
root = Path(__file__).resolve().parents[1]
def norm(s): return ''.join(c for c in s.upper() if c.isalnum())
def floats(v): return '['+', '.join(repr(float(x)) for x in v)+']'
def matrix(v): return '['+', '.join(floats(v[i:i+3]) for i in range(0,9,3))+']'
records={}
for p in sorted((src/'dnglab/dnglab-0.8.0/rawler/data/cameras').rglob('*.toml')):
    d=tomllib.loads(p.read_text()); c=d.get('cameras',{}).get('color_matrix',{})
    a,b=c.get('A'),c.get('D65')
    if not (a or b) or any(len(v)!=9 for v in [a,b] if v): continue
    # aliases include the exact EXIF names and the clean names. Never fabricate a second illuminant.
    aliases=[(d.get('make',''), d.get('model','')), (d.get('clean_make',''),d.get('clean_model',''))]
    for alias in d.get('model_aliases',[]):
        if isinstance(alias,list): aliases.append((d.get('make',''),alias[0]))
    for make,model in aliases:
        if not model: continue
        key=norm(make+model); records.setdefault(key,(a,b,str(p.relative_to(src)),17 if a else 0,21 if b else 0))
# JSON comments removed without modifying strings.
s=(src/'src/rt_camconst.json').read_text()
s=re.sub(r'("(?:\\.|[^"\\])*"|/\*.*?\*/|//[^\n]*)',lambda m:m[0] if m[0].startswith('"') else '',s,flags=re.S)
rt=json.loads(s)
filled=0
for d in rt['camera_constants']:
    v=d.get('dcraw_matrix'); names=d.get('make_model',[])
    if isinstance(names,str): names=[names]
    if not v or len(v)!=9: continue
    for name in names:
        k=norm(name)
        if k not in records:
            records[k]=(None,[x/10000 for x in v],'RawTherapee rtengine/camconst.json',0,21); filled+=1
out=['//! Generated by scripts/engine_colour_data.py; DO NOT EDIT.\n//! rawler v0.8.0 (LGPL-2.1-or-later, elected GPL-3 under section 3); RawTherapee gaps GPL-3.0-or-later.\n//! See licenses/rawler-NOTICE.md. Only three-channel matrices; missing illuminants stay missing.\n',
     'use crate::{ColorData, Mat3};\n',
     'pub fn normalized(s: &str) -> String { s.chars().filter(char::is_ascii_alphanumeric).flat_map(char::to_uppercase).collect() }\n',
     'pub fn get(make: &str, model: &str) -> Option<([Option<Mat3>; 2], [u16; 2])> {\n let key = normalized(&format!("{make}{model}"));\n let index = DATA.binary_search_by_key(&key.as_str(), |r| r.0).ok()?;\n let (_, matrices, illuminants) = DATA[index]; Some((matrices, illuminants))\n}\n',
     'pub fn fill(color: &mut ColorData, make: &str, model: &str) {\n if color.color_matrix.iter().any(Option::is_some) { return; }\n if let Some((m,i)) = get(make,model) { color.color_matrix=m; color.illuminant=i; }\n}\n',
     'pub const DATA: &[(&str, [Option<Mat3>; 2], [u16; 2])] = &[\n']
for k,(a,b,p,i,j) in sorted(records.items()):
    ms=', '.join('None' if v is None else 'Some(Mat3('+matrix(v)+'))' for v in (a,b))
    out.append(f'    // {p}\n    ("{k}", [{ms}], [{i}, {j}]),\n')
out.append('];\n')
(root/'crates/lc-raw/src/camera_matrices.rs').write_text(''.join(out))
# Extract every active monotone preset, in upstream priority order (camera before maker).
s=(src/'dt/src/iop/basecurve.c').read_text(); s=s[s.index('static const basecurve_preset_t basecurve_camera_presets'):s.index('#undef m')]
presets=[]
for line in s.splitlines():
    line=line.strip()
    if not line.startswith('{') or '{ m }' not in line and '{m}' not in line: continue
    names=re.findall(r'"([^"\n]*)"',line)
    pts=re.findall(r'\{\s*([0-9]+\.[0-9]+)\s*,\s*([0-9]+\.[0-9]+)\s*\}',line)
    if len(names)<3 or len(pts)<2: continue
    presets.append((names[1],names[2],pts))
out=['//! darktable src/iop/basecurve.c presets at 733bd69f32cac7ff5e41025115942772add1f088.\n//! GPL-3.0-or-later; generated by scripts/engine_colour_data.py. See licenses/darktable-NOTICE.md.\n', 'pub const PRESETS: &[(&str, &str, &[[f32;2]])] = &[\n']
for make,model,pts in presets:
    out.append(f'({json.dumps(make)}, {json.dumps(model)}, &['+', '.join('['+x+', '+y+']' for x,y in pts)+']),\n')
out.append('];\n'); (root/'crates/lc-pipeline/src/base_curve_data.rs').write_text(''.join(out))
# Explicit in-file rights allowlist; unclear, Adobe, Dworak and Dr Slony are excluded.
dest=root/'crates/lc-raw/data/dcp'; dest.mkdir(parents=True,exist_ok=True)
manifest=[]
for p in sorted((src/'dcp/all').glob('*.dcp')):
    d=p.read_bytes(); e='<' if d[:2]==b'II' else '>'; off=struct.unpack_from(e+'I',d,4)[0]; n=struct.unpack_from(e+'H',d,off)[0]; tags={}
    for i in range(n):
        at=off+2+12*i; tag,typ,cnt,val=struct.unpack_from(e+'HHII',d,at)
        if typ==2:
            pos=val if cnt>4 else at+8; tags[tag]=d[pos:pos+cnt].rstrip(b'\0').decode('latin1')
    rights=tags.get(50942,'').lower()
    if rights not in ('public domain','rawtherapee cc0','cc0'): continue
    name=p.name; (dest/name).write_bytes(d)
    manifest.append({'file':name,'model':tags.get(50708,''),'copyright':tags[50942],'sha256':hashlib.sha256(d).hexdigest()})
(dest/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
(root/'crates/lc-raw/src/dcp_bundled.rs').write_text('// Generated CC0/public-domain allowlist. See data/dcp/manifest.json.\npub const BUNDLED: &[(&str, &[u8])] = &[\n'+''.join(f'({json.dumps(m["model"])}, include_bytes!("../data/dcp/{m["file"]}")),\n' for m in manifest)+'];\n')
print(f'{len(records)} matrix keys ({filled} RT gaps), {len(presets)} base presets, {len(manifest)} DCPs')
