//! Attributions: everything Local Image uses from other projects — ported algorithms, data, AI
//! models, assets, the projects it grew from and every Rust crate — with what it is used for, its
//! licence (the full text where we ship one) and a link.
//!
//! The data is `assets/attributions.json`, generated by `cargo xtask attributions` and built into
//! the binary together with the licence files it names (see `build.rs`). [`show`] draws the
//! searchable page; the Library/Develop Settings, Compositing Preferences and both About dialogs
//! embed it through thin wrappers that open links with their own link service.

use std::sync::OnceLock;

use egui::{RichText, Ui};
use serde::Deserialize;

include!(concat!(env!("OUT_DIR"), "/licence_texts.rs"));

/// The generated data file.
pub const JSON: &str = include_str!("../../../assets/attributions.json");

#[derive(Clone, Debug, Default, PartialEq, Eq, Deserialize)]
pub struct Entry {
    pub name: String,
    #[serde(default)]
    pub version: Option<String>,
    #[serde(default)]
    pub author: Option<String>,
    #[serde(default)]
    pub used_for: Option<String>,
    /// Upstream file(s) or component the entry is about.
    #[serde(default)]
    pub upstream: Option<String>,
    #[serde(default)]
    pub commit: Option<String>,
    /// Our file(s) that port or use it.
    #[serde(default)]
    pub ours: Option<String>,
    #[serde(default)]
    pub licence: String,
    /// Licence or notice files (paths from the repository root) whose text is built in.
    #[serde(default)]
    pub licence_files: Vec<String>,
    #[serde(default)]
    pub url: Option<String>,
}

impl Entry {
    /// Does every word of `query` (lower-case) occur in one of the entry's fields?
    pub fn matches(&self, query: &str) -> bool {
        let fields = [
            Some(self.name.as_str()),
            self.version.as_deref(),
            self.author.as_deref(),
            self.used_for.as_deref(),
            self.upstream.as_deref(),
            self.ours.as_deref(),
            Some(self.licence.as_str()),
            self.url.as_deref(),
        ];
        let hay: String = fields.iter().flatten().map(|f| f.to_lowercase()).collect::<Vec<_>>().join("\n");
        query.split_whitespace().all(|w| hay.contains(w))
    }
}

#[derive(Clone, Debug, Default, PartialEq, Eq, Deserialize)]
pub struct Section {
    pub id: String,
    pub title: String,
    #[serde(default)]
    pub intro: Option<String>,
    #[serde(default)]
    pub entries: Vec<Entry>,
}

#[derive(Clone, Debug, Default, PartialEq, Eq, Deserialize)]
pub struct Attributions {
    pub app: Entry,
    pub sections: Vec<Section>,
}

impl Attributions {
    pub fn section(&self, id: &str) -> Option<&Section> {
        self.sections.iter().find(|s| s.id == id)
    }

    /// Every entry, with its section.
    pub fn entries(&self) -> impl Iterator<Item = (&Section, &Entry)> {
        self.sections.iter().flat_map(|s| s.entries.iter().map(move |e| (s, e)))
    }
}

/// The built-in attributions (parsed once).
pub fn data() -> &'static Attributions {
    static DATA: OnceLock<Attributions> = OnceLock::new();
    DATA.get_or_init(|| serde_json::from_str(JSON).unwrap_or_default())
}

/// The full text of a licence file the attributions name (`licenses/darktable-NOTICE.md`).
pub fn licence_text(path: &str) -> Option<&'static str> {
    LICENCE_TEXTS.iter().find(|(p, _)| *p == path).map(|(_, t)| *t)
}

// ------------------------------------------------------------------------------ view

/// The page's state, kept in egui's memory under the caller's salt.
#[derive(Clone, Debug, Default)]
struct ViewState {
    query: String,
    /// (entry key, licence file) whose text is shown.
    licence: Option<(String, String)>,
}

fn state_id(salt: &str) -> egui::Id {
    egui::Id::new(("li-attributions", salt))
}

/// Set the search text of the page drawn with `salt` (automation and tests).
pub fn set_query(ctx: &egui::Context, salt: &str, query: &str) {
    ctx.data_mut(|d| d.get_temp_mut_or_default::<ViewState>(state_id(salt)).query = query.to_string());
}

/// What happened on the page this frame.
#[derive(Clone, Debug, Default)]
pub struct Output {
    /// A link was clicked: open it in the browser.
    pub open_url: Option<String>,
    /// Each entry drawn (name, rect), for the host's automation registry.
    pub rows: Vec<(String, egui::Rect)>,
    /// The search field.
    pub search: Option<egui::Rect>,
}

/// UI text in the host's language: `tr("Search attributions…")`.
pub type Translate<'a> = &'a dyn Fn(&'static str) -> String;

/// Draw the Attributions page: a search field, then one collapsible section per kind (Rust crates
/// start collapsed; a search opens every section with a match). `salt` keeps the state of pages in
/// different dialogs apart; the list scrolls within `max_height`.
pub fn show(ui: &mut Ui, salt: &str, max_height: f32, tr: Translate<'_>) -> Output {
    let id = state_id(salt);
    let mut st = ui.data_mut(|d| d.get_temp::<ViewState>(id)).unwrap_or_default();
    let mut out = Output::default();
    let data = data();
    let r = ui.add(egui::TextEdit::singleline(&mut st.query).id(id.with("search")).hint_text(tr("Search attributions…")).desired_width(f32::INFINITY));
    out.search = Some(r.rect);
    ui.add_space(4.0);
    let query = st.query.trim().to_lowercase();
    egui::ScrollArea::vertical().id_salt(id.with("scroll")).max_height(max_height).auto_shrink([false, true]).show(ui, |ui| {
        if query.is_empty() || data.app.matches(&query) {
            entry_ui(ui, "app", &data.app, &mut st, &mut out, tr);
            ui.add_space(6.0);
        }
        let mut any = false;
        for s in &data.sections {
            let shown: Vec<(usize, &Entry)> = s.entries.iter().enumerate().filter(|(_, e)| query.is_empty() || e.matches(&query)).collect();
            if shown.is_empty() {
                continue;
            }
            any = true;
            let title = format!("{} ({})", tr_dynamic(tr, &s.title), shown.len());
            let header = egui::CollapsingHeader::new(RichText::new(title).strong()).id_salt(id.with(&s.id)).default_open(s.id != "crates");
            let header = if query.is_empty() { header } else { header.open(Some(true)) };
            header.show(ui, |ui| {
                if let Some(intro) = &s.intro {
                    ui.label(RichText::new(intro).small().weak());
                    ui.add_space(2.0);
                }
                for (i, e) in shown {
                    entry_ui(ui, &format!("{}/{i}", s.id), e, &mut st, &mut out, tr);
                }
            });
        }
        if !any && !query.is_empty() {
            ui.label(RichText::new(tr("No matches.")).weak());
        }
    });
    ui.data_mut(|d| d.insert_temp(id, st));
    out
}

/// Section titles come from the data; the host may translate them.
fn tr_dynamic(tr: Translate<'_>, s: &str) -> String {
    match s {
        "Algorithms & code ports" => tr("Algorithms & code ports"),
        "Data" => tr("Data"),
        "AI models" => tr("AI models"),
        "Assets" => tr("Assets"),
        "Upstream projects Local Image grew from" => tr("Upstream projects Local Image grew from"),
        "Rust crates" => tr("Rust crates"),
        other => other.to_string(),
    }
}

fn short_commit(c: &str) -> &str {
    c.get(..10).unwrap_or(c)
}

/// `https://github.com/a/b/blob/…` → `github.com/a/b/blob/…`, shortened.
fn short_url(url: &str) -> String {
    let s = url.trim_start_matches("https://").trim_start_matches("http://").trim_end_matches('/');
    if s.chars().count() > 48 { format!("{}…", s.chars().take(47).collect::<String>()) } else { s.to_string() }
}

fn entry_ui(ui: &mut Ui, key: &str, e: &Entry, st: &mut ViewState, out: &mut Output, tr: Translate<'_>) {
    let r = ui.vertical(|ui| {
        ui.horizontal_wrapped(|ui| {
            ui.label(RichText::new(&e.name).strong());
            if let Some(v) = &e.version {
                ui.label(RichText::new(v).weak());
            }
            if let Some(url) = &e.url
                && ui.link(RichText::new(short_url(url)).small()).on_hover_text(url).clicked()
            {
                out.open_url = Some(url.clone());
            }
        });
        if let Some(u) = &e.used_for {
            ui.label(RichText::new(u).small());
        }
        let mut details: Vec<String> = Vec::new();
        if let Some(a) = &e.author {
            details.push(a.clone());
        }
        if let Some(u) = &e.upstream {
            details.push(u.clone());
        }
        if let Some(c) = &e.commit {
            details.push(format!("@ {}", short_commit(c)));
        }
        if let Some(o) = &e.ours {
            details.push(format!("→ {o}"));
        }
        if !details.is_empty() {
            ui.label(RichText::new(details.join(" · ")).small().weak());
        }
        ui.horizontal_wrapped(|ui| {
            ui.spacing_mut().item_spacing.x = 6.0;
            ui.label(RichText::new(&e.licence).small().weak());
            for f in &e.licence_files {
                if licence_text(f).is_none() {
                    continue;
                }
                let name = f.rsplit('/').next().unwrap_or(f);
                let open = st.licence.as_ref().is_some_and(|(k, lf)| k == key && lf == f);
                let r = ui.selectable_label(open, RichText::new(name).small()).on_hover_text(tr("Show licence text"));
                if r.clicked() {
                    st.licence = if open { None } else { Some((key.to_string(), f.clone())) };
                }
            }
        });
        if let Some((k, f)) = &st.licence
            && k == key
            && let Some(text) = licence_text(f)
        {
            egui::Frame::group(ui.style()).show(ui, |ui| {
                egui::ScrollArea::vertical().id_salt(("licence", key, f.as_str())).max_height(220.0).show(ui, |ui| {
                    ui.add(egui::Label::new(RichText::new(text).monospace().small()).selectable(true));
                });
            });
        }
    });
    out.rows.push((e.name.clone(), r.response.rect));
    ui.add_space(4.0);
}

#[cfg(test)]
mod tests {
    use super::*;

    fn names(section: &str) -> Vec<&'static str> {
        data().section(section).unwrap_or_else(|| panic!("section {section}")).entries.iter().map(|e| e.name.as_str()).collect()
    }

    #[test]
    fn the_data_parses_and_has_every_section() {
        let d = data();
        assert_eq!(d.app.name, "Local Image");
        for id in ["ports", "data", "models", "assets", "upstream", "crates"] {
            assert!(d.section(id).is_some_and(|s| !s.entries.is_empty()), "{id}");
        }
        assert!(names("ports").contains(&"darktable"));
        assert!(names("data").contains(&"LensFun database"));
        assert!(names("assets").contains(&"Lucide icons"));
        assert!(names("upstream").contains(&"LightCraft") && names("upstream").contains(&"PhotoCraft"));
        for c in ["egui", "wgpu", "lensfun"] {
            assert!(names("crates").contains(&c), "{c}");
        }
    }

    #[test]
    fn every_licence_file_is_built_in() {
        for (_, e) in data().entries().chain(std::iter::once((&data().sections[0], &data().app))) {
            for f in &e.licence_files {
                assert!(licence_text(f).is_some_and(|t| !t.trim().is_empty()), "{}: {f}", e.name);
            }
        }
        assert!(licence_text("LICENSE").is_some_and(|t| t.contains("GNU GENERAL PUBLIC LICENSE")));
    }

    #[test]
    fn search_matches_every_word_in_any_field() {
        let dt = data().entries().map(|(_, e)| e).find(|e| e.name == "darktable").unwrap();
        assert!(dt.matches("darktable"));
        assert!(dt.matches("gpl darktable"));
        assert!(!dt.matches("darktable lucide"));
    }

    /// The page draws, filters and reports rows and links.
    #[test]
    fn the_page_filters_by_search() {
        let ctx = egui::Context::default();
        let tr = |s: &'static str| s.to_string();
        let run = |q: &str| {
            set_query(&ctx, "test", q);
            let mut out = Output::default();
            for _ in 0..2 {
                let mut full = ctx.run_ui(egui::RawInput::default(), |ui| {
                    out = show(ui, "test", 10_000.0, &tr);
                });
                full.textures_delta.clear();
            }
            out.rows.into_iter().map(|(n, _)| n).collect::<Vec<_>>()
        };
        let all = run("");
        assert!(all.contains(&"darktable".to_string()) && all.contains(&"Lucide icons".to_string()));
        assert!(!all.contains(&"wgpu".to_string()), "Rust crates start collapsed");
        let wgpu = run("wgpu");
        assert!(wgpu.contains(&"wgpu".to_string()), "a search opens the crates: {wgpu:?}");
        assert!(!wgpu.contains(&"darktable".to_string()));
        assert!(run("no such thing at all").is_empty());
    }
}
