//! Integration tests for ICC profile writing: encode ↔ parse round trips,
//! invariants of generated bytes, deterministic output, concurrency and
//! error handling for malformed input.

use photocraft_cms::pipeline::Stage;
use photocraft_cms::profile::{Lut, LutKind};
use photocraft_cms::synth::{self, CmykParams};
use photocraft_cms::{Clut, CmsError, ColorSpace, Curve, Pcs, Profile, ProfileClass};

fn small_cmyk_params() -> CmykParams {
    CmykParams { grid_a2b: 2, grid_b2a: 2, ..Default::default() }
}

/// A cheap CMYK profile used as a base for mutation; generation is kept tiny.
fn base_profile() -> Profile {
    synth::cmyk_profile(&small_cmyk_params())
}

/// Builds a LUT with the requested dimensions and kind. The stage layout is
/// `[input curves, CLUT, output curves]`, which is accepted by all three LUT
/// encoders for both A2B and B2A directions.
fn make_lut(kind: LutKind, inputs: usize, outputs: usize) -> Lut {
    let grid: usize = 2;
    let data_len = grid.pow(inputs as u32) * outputs;
    let clut = Clut::new(vec![grid; inputs], outputs, vec![0.5f32; data_len]);
    Lut { kind, inputs, outputs, stages: vec![Stage::Curves(vec![Curve::Identity; inputs]), Stage::Clut(clut), Stage::Curves(vec![Curve::Identity; outputs])] }
}

fn parse_tag_offset(bytes: &[u8], sig: &[u8; 4]) -> Option<usize> {
    if bytes.len() < 132 {
        return None;
    }
    let count = u32::from_be_bytes([bytes[128], bytes[129], bytes[130], bytes[131]]) as usize;
    for i in 0..count {
        let off = 132 + i * 12;
        if &bytes[off..off + 4] == sig {
            let tag_off = u32::from_be_bytes([bytes[off + 4], bytes[off + 5], bytes[off + 6], bytes[off + 7]]) as usize;
            return Some(tag_off);
        }
    }
    None
}

#[test]
fn synthetic_cmyk_round_trip_preserves_header_fields() {
    let p = base_profile();
    let bytes = p.to_bytes();
    let q = Profile::parse(&bytes).expect("parse encoded profile");

    assert_eq!(q.class, ProfileClass::Output);
    assert_eq!(q.color_space, ColorSpace::Cmyk);
    assert_eq!(q.pcs, Pcs::Lab);
    assert_eq!(q.rendering_intent, p.rendering_intent);
    assert_eq!(q.description, p.description);
    assert_eq!(q.copyright, p.copyright);
    for (a, b) in q.white_point.iter().zip(p.white_point.iter()) {
        assert!((a - b).abs() < 1e-6, "white point changed: {a} != {b}");
    }
    assert_eq!(q.channels(), 4);
}

#[test]
fn synthetic_cmyk_round_trip_preserves_lut_presence() {
    let p = base_profile();
    let q = Profile::parse(&p.to_bytes()).expect("parse");
    for slot in q.a2b.iter().chain(q.b2a.iter()) {
        assert!(slot.is_some(), "expected a LUT in every slot");
    }
}

#[test]
fn synthetic_cmyk_lut_kind_is_lut16() {
    let p = base_profile();
    let q = Profile::parse(&p.to_bytes()).expect("parse");
    assert!(q.a2b.iter().all(|l| matches!(l.as_ref().map(|l| l.kind), Some(LutKind::Lut16))));
    assert!(q.b2a.iter().all(|l| matches!(l.as_ref().map(|l| l.kind), Some(LutKind::Lut16))));
}

#[test]
fn matrix_trc_rgb_round_trip() {
    let mut p = base_profile();
    p.color_space = ColorSpace::Rgb;
    p.pcs = Pcs::Xyz;
    p.a2b = [None, None, None];
    p.b2a = [None, None, None];
    let expected_matrix = [[0.4124, 0.3576, 0.1805], [0.2126, 0.7152, 0.0722], [0.0193, 0.1192, 0.9505]];
    p.matrix = Some(expected_matrix);
    p.trc = Some([Curve::Gamma(2.2), Curve::Gamma(2.2), Curve::Gamma(2.2)]);
    p.gray_trc = None;
    let bytes = p.with_encoded_bytes().to_bytes();

    let q = Profile::parse(&bytes).expect("parse matrix/TRC profile");
    assert_eq!(q.color_space, ColorSpace::Rgb);
    assert_eq!(q.pcs, Pcs::Xyz);
    assert!(q.matrix.is_some());
    assert!(q.trc.is_some());
    let m = q.matrix.unwrap();
    for row in 0..3 {
        for col in 0..3 {
            assert!((m[row][col] - expected_matrix[row][col]).abs() < 1e-4);
        }
    }
    for (a, b) in q.trc.as_ref().unwrap().iter().zip([Curve::Gamma(2.2), Curve::Gamma(2.2), Curve::Gamma(2.2)]) {
        match (a, &b) {
            (Curve::Gamma(x), Curve::Gamma(y)) => assert!((*x - *y).abs() < 1e-3, "gamma mismatch: {x} vs {y}"),
            other => panic!("expected Curve::Gamma, got {other:?}"),
        }
    }
    assert!(q.a2b.iter().all(Option::is_none));
    assert!(q.b2a.iter().all(Option::is_none));
}

#[test]
fn gray_trc_round_trip() {
    let mut p = base_profile();
    p.color_space = ColorSpace::Gray;
    p.pcs = Pcs::Xyz;
    p.a2b = [None, None, None];
    p.b2a = [None, None, None];
    p.matrix = None;
    p.trc = None;
    p.gray_trc = Some(Curve::Gamma(2.2));
    let bytes = p.with_encoded_bytes().to_bytes();

    let q = Profile::parse(&bytes).expect("parse gray profile");
    assert_eq!(q.color_space, ColorSpace::Gray);
    let parsed_gray = q.gray_trc.expect("gray_trc exists");
    match parsed_gray {
        Curve::Gamma(g) => assert!((g - 2.2).abs() < 1e-3, "gamma mismatch: {g}"),
        other => panic!("expected Curve::Gamma, got {other:?}"),
    }
    assert!(q.a2b.iter().all(Option::is_none));
    assert!(q.b2a.iter().all(Option::is_none));
}

#[test]
fn lab_identity_profile_round_trip() {
    let mut p = base_profile();
    p.color_space = ColorSpace::Lab;
    p.a2b = [None, None, None];
    p.b2a = [None, None, None];
    p.matrix = None;
    p.trc = None;
    p.gray_trc = None;
    let q = Profile::parse(&p.with_encoded_bytes().to_bytes()).expect("parse Lab profile");
    assert_eq!(q.color_space, ColorSpace::Lab);
    assert_eq!(q.pcs, Pcs::Lab);
    assert!(q.a2b.iter().all(Option::is_none));
    assert!(q.b2a.iter().all(Option::is_none));
}

#[test]
fn rgb_lut8_mft_round_trip() {
    let mut p = base_profile();
    p.color_space = ColorSpace::Rgb;
    p.a2b = [None, None, None];
    p.b2a = [None, None, None];
    p.a2b[1] = Some(make_lut(LutKind::Lut8, 3, 3));
    let q = Profile::parse(&p.with_encoded_bytes().to_bytes()).expect("parse lut8 profile");
    let lut = q.a2b[1].as_ref().expect("a2b colorimetric LUT");
    assert_eq!(lut.kind, LutKind::Lut8);
    assert_eq!(lut.inputs, 3);
    assert_eq!(lut.outputs, 3);
}

#[test]
fn rgb_lut16_mft_round_trip() {
    let mut p = base_profile();
    p.color_space = ColorSpace::Rgb;
    p.a2b = [None, None, None];
    p.b2a = [None, None, None];
    p.a2b[1] = Some(make_lut(LutKind::Lut16, 3, 3));
    let q = Profile::parse(&p.with_encoded_bytes().to_bytes()).expect("parse lut16 profile");
    let lut = q.a2b[1].as_ref().expect("a2b colorimetric LUT");
    assert_eq!(lut.kind, LutKind::Lut16);
    assert_eq!(lut.inputs, 3);
    assert_eq!(lut.outputs, 3);
}

#[test]
fn rgb_lut_ab_round_trip() {
    let mut p = base_profile();
    p.color_space = ColorSpace::Rgb;
    p.a2b = [None, None, None];
    p.b2a = [None, None, None];
    p.a2b[1] = Some(make_lut(LutKind::Ab, 3, 3));
    let q = Profile::parse(&p.with_encoded_bytes().to_bytes()).expect("parse lutAB profile");
    let lut = q.a2b[1].as_ref().expect("a2b colorimetric LUT");
    assert_eq!(lut.kind, LutKind::Ab);
    assert_eq!(lut.inputs, 3);
    assert_eq!(lut.outputs, 3);
}

#[test]
fn b2a_lut_round_trip() {
    let mut p = base_profile();
    p.color_space = ColorSpace::Rgb;
    p.a2b = [None, None, None];
    p.b2a = [None, None, None];
    p.b2a[1] = Some(make_lut(LutKind::Lut16, 3, 3));
    let q = Profile::parse(&p.with_encoded_bytes().to_bytes()).expect("parse B2A profile");
    let lut = q.b2a[1].as_ref().expect("b2a colorimetric LUT");
    assert_eq!(lut.kind, LutKind::Lut16);
    assert_eq!(lut.inputs, 3);
    assert_eq!(lut.outputs, 3);
}

#[test]
fn black_point_and_chad_round_trip() {
    let mut p = base_profile();
    p.black_point = Some([0.1, 0.2, 0.3]);
    p.chad = Some([[1.1, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 0.9]]);
    let q = Profile::parse(&p.with_encoded_bytes().to_bytes()).expect("parse with bkpt/chad");
    assert!(q.black_point.is_some());
    assert!(q.chad.is_some());
    for (a, b) in q.black_point.unwrap().iter().zip([0.1, 0.2, 0.3]) {
        assert!((a - b).abs() < 1e-4);
    }
    let m = q.chad.unwrap();
    for (row, expected) in m.iter().zip([[1.1, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 0.9]]) {
        for (v, e) in row.iter().zip(expected) {
            assert!((v - e).abs() < 1e-4);
        }
    }
}

#[test]
fn unicode_description_and_copyright_round_trip() {
    let mut p = base_profile();
    p.description = "Photocraft 🙂 coated CMYK".into();
    p.copyright = "© 2024".into();
    let expected_description = p.description.clone();
    let expected_copyright = p.copyright.clone();
    let q = Profile::parse(&p.with_encoded_bytes().to_bytes()).expect("parse Unicode metadata");
    assert_eq!(q.description, expected_description);
    assert_eq!(q.copyright, expected_copyright);
}

#[test]
fn encode_is_deterministic() {
    let p = base_profile();
    let b1 = p.clone().with_encoded_bytes().to_bytes();
    let b2 = p.clone().with_encoded_bytes().to_bytes();
    assert_eq!(b1.as_slice(), b2.as_slice(), "re-encoding identical profile must be byte-identical");
}

#[test]
fn to_bytes_returns_original_for_parsed_profile() {
    let p = base_profile();
    let original = p.to_bytes();
    let parsed = Profile::parse(&original).expect("parse");
    let round = parsed.to_bytes();
    assert_eq!(original.as_slice(), round.as_slice());
}

#[test]
fn with_encoded_bytes_overrides_original() {
    let p = base_profile();
    let original = p.to_bytes().clone();
    let mut p2 = p.clone();
    p2.description = "changed".into();
    let changed = p2.with_encoded_bytes().to_bytes();
    assert_ne!(original.as_slice(), changed.as_slice());
}

#[test]
fn parse_truncated_returns_truncated() {
    let bytes = base_profile().to_bytes();
    let err = Profile::parse(&bytes[..bytes.len() - 1]).expect_err("truncated must fail");
    assert_eq!(err, CmsError::Truncated);
}

#[test]
fn parse_too_short_returns_truncated() {
    let small = [0u8; 100];
    assert_eq!(Profile::parse(&small), Err(CmsError::Truncated));
}

#[test]
fn parse_bad_signature_returns_bad_signature() {
    let mut bytes = base_profile().to_bytes().to_vec();
    bytes[36..40].copy_from_slice(b"not ");
    assert_eq!(Profile::parse(&bytes), Err(CmsError::BadSignature));
}

#[test]
fn parse_too_many_tags_returns_invalid() {
    let mut bytes = base_profile().to_bytes().to_vec();
    bytes[128..132].copy_from_slice(&(1025u32).to_be_bytes());
    match Profile::parse(&bytes) {
        Err(CmsError::Invalid(_)) => {}
        other => panic!("expected Invalid error, got {other:?}"),
    }
}

#[test]
fn parse_declared_size_larger_than_actual_is_tolerated() {
    let mut bytes = base_profile().to_bytes().to_vec();
    let fake_size = bytes.len() + 1000;
    bytes[0..4].copy_from_slice(&(fake_size as u32).to_be_bytes());
    assert!(Profile::parse(&bytes).is_ok());
}

#[test]
fn parse_lut_with_zero_grid_points_returns_invalid() {
    let bytes = base_profile().to_bytes();
    let mut bytes = bytes.to_vec();
    let off = parse_tag_offset(&bytes, b"A2B0").expect("find A2B0 tag");
    bytes[off + 10] = 0; // grid points byte of mft2 tag
    match Profile::parse(&bytes) {
        Err(CmsError::Invalid(_)) => {}
        other => panic!("expected Invalid error for zero grid, got {other:?}"),
    }
}

#[test]
fn parse_invalid_curve_type_returns_unsupported() {
    // The writer only emits `curv` or `para`. Force an unknown curve type by
    // corrupting the first curve tag in a matrix/TRC profile.
    let mut p = base_profile();
    p.color_space = ColorSpace::Rgb;
    p.a2b = [None, None, None];
    p.b2a = [None, None, None];
    p.matrix = Some([[0.4124, 0.3576, 0.1805], [0.2126, 0.7152, 0.0722], [0.0193, 0.1192, 0.9505]]);
    p.trc = Some([Curve::Gamma(2.2), Curve::Gamma(2.2), Curve::Gamma(2.2)]);
    p.gray_trc = None;
    let mut bytes = p.with_encoded_bytes().to_bytes().to_vec();
    let off = parse_tag_offset(&bytes, b"rTRC").expect("find rTRC tag");
    bytes[off..off + 4].copy_from_slice(b"bad ");
    match Profile::parse(&bytes) {
        Err(CmsError::Unsupported(_)) => {}
        other => panic!("expected Unsupported error for curve type, got {other:?}"),
    }
}

#[test]
fn concurrent_encode_parse_no_deadlock() {
    let seed = base_profile();
    let bytes = seed.to_bytes();
    let shared = std::sync::Arc::new(bytes.to_vec());
    let (tx, rx) = std::sync::mpsc::channel();

    for _ in 0..8 {
        let shared = shared.clone();
        let tx = tx.clone();
        std::thread::spawn(move || {
            let parsed = Profile::parse(&shared).expect("parse in thread");
            let encoded = parsed.with_encoded_bytes().to_bytes();
            tx.send(encoded.len()).expect("send result");
        });
    }
    drop(tx);

    let deadline = std::time::Duration::from_secs(5);
    let mut received = 0;
    while received < 8 {
        rx.recv_timeout(deadline).expect("thread did not finish in time");
        received += 1;
    }
}

#[test]
fn profile_channels_matches_color_space() {
    let mut p = base_profile();
    for (cs, expected) in [(ColorSpace::Gray, 1), (ColorSpace::Rgb, 3), (ColorSpace::Cmyk, 4), (ColorSpace::Lab, 3), (ColorSpace::Xyz, 3)] {
        p.color_space = cs;
        assert_eq!(p.channels(), expected);
    }
}

#[test]
fn gray_as_rgb_round_trip() {
    let mut p = base_profile();
    p.color_space = ColorSpace::Gray;
    p.pcs = Pcs::Xyz;
    p.a2b = [None, None, None];
    p.b2a = [None, None, None];
    p.matrix = None;
    p.trc = None;
    p.gray_trc = Some(Curve::Gamma(2.2));
    let gray_rgb = p.gray_as_rgb().expect("gray_as_rgb");
    assert_eq!(gray_rgb.color_space, ColorSpace::Rgb);
    assert!(gray_rgb.matrix.is_some());
    assert!(gray_rgb.trc.is_some());
    assert!(gray_rgb.gray_trc.is_none());

    let q = Profile::parse(&gray_rgb.with_encoded_bytes().to_bytes()).expect("parse gray-as-rgb");
    assert_eq!(q.color_space, ColorSpace::Rgb);
    assert!(q.matrix.is_some());
    assert!(q.trc.is_some());
    assert!(q.gray_trc.is_none());
}

#[test]
fn same_colors_returns_true_for_identical_encoded() {
    let p = base_profile();
    let q = Profile::parse(&p.to_bytes()).expect("parse");
    assert!(p.same_colors(&q));
    assert!(q.same_colors(&p));
}
